export type CultureItem={section:string;title:string;summary:string;why:string;href:string;source:string;date:string};
export const cultureNews:CultureItem[]=[
 {section:'Kulturnyheter',title:'SVT:s besparingar kommer att märkas i höstens utbud',summary:'Ett sparpaket på 355 miljoner kronor innebär färre titlar och billigare produktioner, enligt SVT:s vd.',why:'Besparingen påverkar både publikens utbud och den svenska produktionsmarknaden.',href:'https://www.svt.se/kultur/svts-vd-besparingarna-kommer-att-markas-i-utbudet',source:'SVT Kultur',date:'28 augusti 2026'},
 {section:'Kulturnyheter',title:'Kultursverige kräver besked om bio, AI och arbetsvillkor',summary:'Kulturarbetare pressar partierna inför valet om bland annat biografmoms, ersättningar och skydd mot otillåten AI-användning.',why:'Valbeskeden kan påverka villkoren för skapande, distribution och publikens tillgång till kultur.',href:'https://www.svt.se/kultur/kultursverige-staller-politikerna-mot-vaggen',source:'SVT Kultur',date:'28 augusti 2026'},
 {section:'TV & strömning',title:'Klassiker får nya liv i höstens stora tv-serier',summary:'Nya tolkningar av bland annat East of Eden, Carrie och Harry Potter präglar höstens svenska streamingutbud.',why:'Omtolkningarna visar hur rättighetsägare kombinerar välkända berättelser med nya publikgrupper.',href:'https://www.svt.se/kultur/kritikern-har-ar-de-basta-tv-serierna-att-stromma-hosten-2026',source:'SVT Kultur',date:'26 augusti 2026'}
];
export const newBooks:CultureItem[]=[
 {section:'Ny bok · Roman',title:'Kjell Westö avslutar en berättelse med Coda',summary:'Kjell Westös nya bok Coda gavs ut den 20 augusti och presenteras som ett nytt skönlitterärt verk i höstens utgivning.',why:'Westös författarskap återkommer till minne, tid och nordisk historia – frågor som får ny resonans i en orolig samtid.',href:'https://aterforsaljare.bonnierforlagen.se/bocker/293633/coda/',source:'Bonnierförlagen',date:'20 augusti 2026'},
 {section:'Ny bok · Unga',title:'Ny bok öppnar samtalet om idrott och mens',summary:'Frida Ejderstedts Kan vi snacka om det? tar upp träning, tävling, smärta och menscykel för unga läsare.',why:'Boken fyller ett kunskapsgap där kropp, idrott och prestationskrav länge har behandlats var för sig.',href:'https://www.bonnierforlagen.se/',source:'Bonnierförlagen',date:'27 augusti 2026'},
 {section:'Ny facklitteratur',title:'Höstens fackböcker rör sig mellan mat, historia och samhälle',summary:'Förlagens aktuella utgivning spänner från biografier och samtidspolitik till hälsa och mat.',why:'Fackutgivningen ger en tidig bild av vilka frågor förlagen tror att läsarna vill förstå under hösten.',href:'https://www.bonnierforlagen.se/',source:'Bonnierförlagen',date:'28 augusti 2026'}
];
export const newFilms:CultureItem[]=[
 {section:'Ny film · Dokumentär',title:'Siri Hustvedt – Dance Around the Self får svensk biopremiär',summary:'Dokumentären om författaren och tänkaren Siri Hustvedt har premiär den 28 augusti.',why:'Filmen binder samman litteratur, identitet och forskning om hur jaget formas.',href:'https://www.filmstaden.se/premiarer-pa-bio/',source:'Filmstaden',date:'28 augusti 2026'},
 {section:'Ny film · Svenskt',title:'En stark svensk filmhöst tar form',summary:'Filminstitutets höstpresentation samlar nya svenska långfilmer, från regidebuter till dokumentärer och genrefilm.',why:'Premiärlistan visar både bredden och finansieringsvillkoren i svensk filmproduktion.',href:'https://www.filminstitutet.se/sv/nyheter/2026/hostens-svenska-filmpremiarer/',source:'Svenska Filminstitutet',date:'26 augusti 2026'},
 {section:'Ny film · Familj',title:'Marsupilami och Salto, Pus & en bucketlist har premiär',summary:'Två nya familjefilmer når svenska biografer den 28 augusti med humor, vänskap och äventyr i centrum.',why:'Familjefilmen är en viktig del av biografernas återväxt och publikvanor.',href:'https://www.folketsbio.se/kommande-filmer/',source:'Folkets Bio och Filmstaden',date:'28 augusti 2026'}
];
export const newMusic:CultureItem[]=[
 {section:'Ny musik · Live',title:'Andreas Aleman möter P4-publiken på Musikplats',summary:'Soul- och jazzartisten spelar direktsänt med sitt band den 28 augusti.',why:'Livescenen ger ny svensk musik en publik utanför de stora kommersiella spellistorna.',href:'https://www.sverigesradio.se/artikel/andreas-aleman-moter-p4-publiken-live-i-en-konsert-pa-musikplats',source:'Sveriges Radio',date:'28 augusti 2026'},
 {section:'Ny musik · Album',title:'Toussaint Chiza presenterar sin nya musik efter karriärens omstart',summary:'Efter ett nytt album tidigare i år återvänder Toussaint Chiza till livescenen med ett mer personligt uttryck.',why:'Förflyttningen från tv-genombrott till ett självständigt artistprojekt visar hur en lång karriär kan byggas efter den första berömmelsen.',href:'https://www.sverigesradio.se/artikel/musikplatsen-ar-tillbaka-sasongens-forsta-show',source:'Sveriges Radio',date:'21 augusti 2026'},
 {section:'Ny musik · Singel',title:'Mauro Scocco är tillbaka med Allt Just Nu',summary:'Låten är den första singeln från ett kommande album och Scoccos första nya projekt efter ett längre uppehåll.',why:'Återkomsten prövar hur ett etablerat låtskrivarskap fungerar i dagens singel- och streamingekonomi.',href:'https://www.sverigesradio.se/artikel/ar-tillbaka-med-ny-musik-ingen-vanlig-mauro-scocco-lat',source:'Sveriges Radio',date:'2 juni 2026'}
];
export type CultureProfile={slug:string;role:string;name:string;title:string;intro:string;sections:{heading:string;paragraphs:string[]}[];ideas:string[];sources:{label:string;url:string}[]};
export const cultureProfiles:CultureProfile[]=[
 {slug:'hannah-arendt',role:'Filosof',name:'Hannah Arendt',title:'Hannah Arendt och ansvaret att tänka själv',intro:'Arendt undersökte totalitarism, makt och vad som händer när människor slutar bedöma sina egna handlingar.',sections:[{heading:'Det offentliga rummet',paragraphs:['För Hannah Arendt var politik mer än administration. Politik uppstår när människor träder fram inför varandra, talar och handlar i en gemensam värld. Det offentliga rummet är därför både en plats och en relation.','När offentligheten försvagas blir människor mer isolerade och lättare att styra genom rädsla eller propaganda. Arendts perspektiv gör dagens frågor om medier och digitala plattformar särskilt relevanta.']},{heading:'Den banala ondskan',paragraphs:['Arendts omstridda formulering om ondskans banalitet handlade inte om att brott är obetydliga. Hon ville visa hur fruktansvärda handlingar kan utföras av människor som har slutat tänka kritiskt kring sitt ansvar.','Poängen är krävande: regler och order befriar inte individen från omdöme. Att tänka själv är inte bara en intellektuell förmåga utan en moralisk uppgift.']},{heading:'Varför läsa Arendt nu?',paragraphs:['I en tid av polariserade informationsmiljöer påminner Arendt om skillnaden mellan fakta, åsikt och lögn. En gemensam värld kräver att människor kan vara oense utan att förneka verkligheten de delar.']}],ideas:['Makt skapas när människor handlar tillsammans.','Frihet behöver ett offentligt rum där människor kan framträda.','Individen har ansvar även när en organisation eller stat ger order.'],sources:[{label:'Stanford Encyclopedia of Philosophy: Hannah Arendt',url:'https://plato.stanford.edu/entries/arendt/'},{label:'Encyclopaedia Britannica: Hannah Arendt',url:'https://www.britannica.com/biography/Hannah-Arendt'}]},
 {slug:'daniel-kahneman',role:'Psykolog',name:'Daniel Kahneman',title:'Daniel Kahneman visade varför vårt tänkande ofta lurar oss',intro:'Kahnemans forskning förändrade synen på beslut genom att visa hur intuition, genvägar och sammanhang påverkar våra bedömningar.',sections:[{heading:'Snabbt och långsamt tänkande',paragraphs:['Kahneman beskrev två sätt att tänka. Det snabba är intuitivt, automatiskt och användbart i vardagen. Det långsamma kräver koncentration och används när vi räknar, jämför eller ifrågasätter vårt första intryck.','Modellen är en pedagogisk förenkling, men den hjälper oss att förstå varför vi ibland svarar snabbt på en annan fråga än den vi faktiskt fick.']},{heading:'Förlust väger tyngre än vinst',paragraphs:['Tillsammans med Amos Tversky visade Kahneman att människor ofta reagerar starkare på en förlust än på en lika stor vinst. Det påverkar investeringar, politik och vardagsbeslut.','Vi kan därför hålla fast vid dåliga alternativ för länge eller undvika en rimlig risk eftersom den möjliga förlusten känns mer konkret än vinsten.']},{heading:'Ett verktyg, inte ett facit',paragraphs:['Kunskap om tankefel gör oss inte immuna mot dem. Det mest praktiska är att skapa processer som bromsar viktiga beslut: jämföra basfrekvenser, skriva ned antaganden och låta andra granska resonemanget.']}],ideas:['Intuition är snabb och användbar men systematiskt felbar.','Förluster upplevs ofta starkare än motsvarande vinster.','Bra beslut kräver processer som kan korrigera första intrycket.'],sources:[{label:'Nobel Prize: Daniel Kahneman – facts',url:'https://www.nobelprize.org/prizes/economic-sciences/2002/kahneman/facts/'},{label:'American Psychological Association: Daniel Kahneman',url:'https://www.apa.org/monitor/2012/02/kahneman'}]}
];
export const cultureProfileBySlug=Object.fromEntries(cultureProfiles.map(profile=>[profile.slug,profile]));
