export type CultureItem={section:string;title:string;summary:string;why:string;href:string;source:string;date:string};
export const cultureNews:CultureItem[]=[
 {section:'Film',title:'Woman Unknown vinner Guldlejonet i Venedig',summary:'May el-Toukhys efterkrigsdrama Woman Unknown vann Guldlejonet. Mathilde Arcel utsågs samtidigt till bästa skådespelare för sin huvudroll.',why:'Dubbelsegern ger en dansk-svensk-lettisk samproduktion ett starkt internationellt genomslag och riktar nytt ljus mot kvinnors villkor i både filmhistorien och dagens filmindustri.',href:'https://www.reuters.com/business/media-telecom/woman-unknown-wins-best-film-venice-festival-2026-09-12/',source:'Reuters',date:'12 september 2026'},
 {section:'Dokumentär',title:'NAZA får juryns specialpris efter starkt mottagande i Venedig',summary:'Dokumentären NAZA av Yuval Abraham och Rachel Szor fick juryns specialpris efter sin premiär på filmfestivalen i Venedig.',why:'Priset visar hur dokumentärfilm åter har blivit en central arena för politiska vittnesmål, samtidigt som verkets anklagelser kommer att fortsätta granskas och debatteras.',href:'https://www.reuters.com/business/media-telecom/woman-unknown-wins-best-film-venice-festival-2026-09-12/',source:'Reuters',date:'12 september 2026'},
 {section:'Film',title:'Jeremy Thomas lämnar efter sig fem decennier av orädd filmkonst',summary:'Den brittiske producenten bakom bland annat Den siste kejsaren, Crash och Sexy Beast har avlidit, 77 år gammal.',why:'Thomas karriär visar vilken betydelse en risktagande producent kan ha för filmer som annars skulle ha haft svårt att nå en internationell publik.',href:'https://www.theguardian.com/film/2026/sep/12/jeremy-thomas-producer-the-last-emperor-sexy-beast-dies',source:'The Guardian',date:'12 september 2026'},
 {section:'Svensk film',title:'Finländsk film lockar hemmapubliken – Sverige halkar efter',summary:'Sverige och Finland satsar ungefär lika mycket offentliga pengar per invånare på film, men den finländska hemmapubliken väljer nationell film i betydligt högre grad.',why:'Skillnaden pekar mot betydelsen av återkommande publikfavoriter, marknadsföring och berättelser som upplevs som lokalt förankrade.',href:'https://www.svt.se/kultur/finlandarna-gar-pa-finsk-film-sverige-halkar-efter',source:'SVT Kultur',date:'10 september 2026'}
];
export const newBooks:CultureItem[]=[
 {section:'Ny bok · Samhälle',title:'Naomi Klein granskar techmiljardärernas politiska makt',summary:'I End Times Fascism, skriven med Astra Taylor, undersöker Naomi Klein hur extrem rikedom, teknikmakt och kriser vävs samman.',why:'Boken placerar tekniksektorns ledare i en bredare diskussion om demokrati, klimat och privat makt över gemensamma framtidsbeslut.',href:'https://www.theguardian.com/books/2026/sep/12/naomi-klein-extreme-wealth-has-a-deranging-effect-it-turns-you-into-a-supremacist',source:'The Guardian',date:'12 september 2026'},
 {section:'Ny bok · Barn',title:'Julia Donaldson avslutar Gruffalo-serien med Gruffalo Granny',summary:'Den brittiska barnboksförfattaren återvänder till sin mest kända berättelse i en bok om sagor, familj och generationer.',why:'Donaldsons genomslag visar hur högläsning, rytm och återkommande figurer kan skapa ett gemensamt litterärt språk mellan barn och vuxna.',href:'https://www.theguardian.com/books/2026/sep/12/julia-donaldson-am-i-the-gruffalo-granny-not-really-im-the-mouse',source:'The Guardian',date:'12 september 2026'},
 {section:'Ny bok · Mat',title:'Jay Rayner förenar restaurangminnen och recept i ny bok',summary:'Nights Out in the Kitchen samlar den brittiske kritikerns erfarenheter från 25 år av restaurangbevakning tillsammans med recept och personliga berättelser.',why:'Boken öppnar för en diskussion om kritikens ansvar när en recension både ska underhålla läsaren och kan påverka människors försörjning.',href:'https://www.reuters.com/lifestyle/culture-current/jay-rayner-responsibility-restaurant-criticism-2026-09-12/',source:'Reuters',date:'12 september 2026'}
];
export const newFilms:CultureItem[]=[
 {section:'Ny film · Musikal',title:'Rebel Wilson återvänder med Girl Group',summary:'Musikalkomedin om en avdankad popstjärna som får handleda en grupp unga tjejer hade premiär på filmfestivalen i Toronto.',why:'Filmen använder fem årtionden av tjejgruppsmusik för att förena populärkulturell nostalgi med en berättelse om vänskap och nya chanser.',href:'https://www.reuters.com/business/media-telecom/rebel-wilsons-new-film-celebrates-girl-power-after-setback-directorial-debut-2026-09-12/',source:'Reuters',date:'12 september 2026'},
 {section:'Ny film · Thriller',title:'Courteney Cox dramatiserar det ökända pizzabombarfallet',summary:'Evil Genius med Patricia Arquette och David Harbour är Courteney Cox första långfilm som regissör på 12 år och premiärvisades i Toronto.',why:'Filmen prövar hur verkliga tragedier kan gestaltas med både mörk humor och psykologiskt drama utan att förlora offrens perspektiv.',href:'https://www.reuters.com/business/media-telecom/courteney-cox-thriller-tells-dysfunctional-love-story-behind-pizza-bomber-case-2026-09-12/',source:'Reuters',date:'12 september 2026'},
 {section:'Ny film · Fantasy',title:'Practical Magic 2 leder veckans filmpremiärer',summary:'Sandra Bullock och Nicole Kidman återvänder i uppföljaren, medan musikdokumentären om Pulp och flera nya dramafilmer också når publiken.',why:'Veckans utbud visar hur biograferna kombinerar välkända varumärken med dokumentärer och smalare drama för att locka olika publikgrupper.',href:'https://www.theguardian.com/culture/2026/sep/12/entertainment-guide-week-ahead-practical-magic-saint-etienne-neagley-cinema-theatre-art-music',source:'The Guardian',date:'12 september 2026'}
];
export const newMusic:CultureItem[]=[
 {section:'Ny musik · Dokumentär',title:'Musikdokumentären blir konsertbranschens nya bioscen',summary:'Nya filmer om Oasis, Pulp, K-popgrupper och äldre rockakter visar hur musikindustrin använder bioduken för att förlänga turnéer och artistberättelser.',why:'Formatet förenar biografens gemenskap med streamingtidens fanekonomi och ger både nya och etablerade artister ytterligare en distributionskanal.',href:'https://www.theguardian.com/culture/2026/sep/11/from-oasis-to-k-pop-music-is-going-mad-for-the-big-screen-documentary',source:'The Guardian',date:'11 september 2026'},
 {section:'Ny musik · Album',title:'Bloc Party och Sylvan Esso hör till veckans stora albumsläpp',summary:'Bloc Party släpper Anatomy of a Brief Romance och Sylvan Esso albumet Ow ∞ i en vecka med ett brett internationellt musikutbud.',why:'Samtidiga släpp från etablerade alternativakter visar hur albumformatet behåller sin betydelse trots en musikmarknad som styrs av enskilda låtar och spellistor.',href:'https://www.theguardian.com/culture/2026/sep/12/entertainment-guide-week-ahead-practical-magic-saint-etienne-neagley-cinema-theatre-art-music',source:'The Guardian',date:'12 september 2026'},
 {section:'Ny musik · Live',title:'Saint Etienne tar farväl av publiken på sin sista turné',summary:'Den brittiska gruppen ger sig ut på sin sista Storbritanniensturné som en del av en stark höstvecka för livemusiken.',why:'Avskedsturnén visar hur konserten blivit en viktig plats för att förvalta ett långt artistarv när den inspelade musiken lever vidare digitalt.',href:'https://www.theguardian.com/culture/2026/sep/12/entertainment-guide-week-ahead-practical-magic-saint-etienne-neagley-cinema-theatre-art-music',source:'The Guardian',date:'12 september 2026'}
];
export const cultureItems=[...cultureNews,...newBooks,...newFilms,...newMusic];
export const cultureSlug=(title:string)=>title.toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
export const cultureItemBySlug=Object.fromEntries(cultureItems.map(item=>[cultureSlug(item.title),item]));
export type CultureProfile={slug:string;role:string;name:string;title:string;intro:string;sections:{heading:string;paragraphs:string[]}[];ideas:string[];sources:{label:string;url:string}[]};
export const cultureProfiles:CultureProfile[]=[
 {slug:'hannah-arendt',role:'Filosof',name:'Hannah Arendt',title:'Hannah Arendt och ansvaret att tänka själv',intro:'Arendt undersökte totalitarism, makt och vad som händer när människor slutar bedöma sina egna handlingar.',sections:[{heading:'Det offentliga rummet',paragraphs:['För Hannah Arendt var politik mer än administration. Politik uppstår när människor träder fram inför varandra, talar och handlar i en gemensam värld. Det offentliga rummet är därför både en plats och en relation.','När offentligheten försvagas blir människor mer isolerade och lättare att styra genom rädsla eller propaganda. Arendts perspektiv gör dagens frågor om medier och digitala plattformar särskilt relevanta.']},{heading:'Den banala ondskan',paragraphs:['Arendts omstridda formulering om ondskans banalitet handlade inte om att brott är obetydliga. Hon ville visa hur fruktansvärda handlingar kan utföras av människor som har slutat tänka kritiskt kring sitt ansvar.','Poängen är krävande: regler och order befriar inte individen från omdöme. Att tänka själv är inte bara en intellektuell förmåga utan en moralisk uppgift.']},{heading:'Varför läsa Arendt nu?',paragraphs:['I en tid av polariserade informationsmiljöer påminner Arendt om skillnaden mellan fakta, åsikt och lögn. En gemensam värld kräver att människor kan vara oense utan att förneka verkligheten de delar.']}],ideas:['Makt skapas när människor handlar tillsammans.','Frihet behöver ett offentligt rum där människor kan framträda.','Individen har ansvar även när en organisation eller stat ger order.'],sources:[{label:'Stanford Encyclopedia of Philosophy: Hannah Arendt',url:'https://plato.stanford.edu/entries/arendt/'},{label:'Encyclopaedia Britannica: Hannah Arendt',url:'https://www.britannica.com/biography/Hannah-Arendt'}]},
 {slug:'daniel-kahneman',role:'Psykolog',name:'Daniel Kahneman',title:'Daniel Kahneman visade varför vårt tänkande ofta lurar oss',intro:'Kahnemans forskning förändrade synen på beslut genom att visa hur intuition, genvägar och sammanhang påverkar våra bedömningar.',sections:[{heading:'Snabbt och långsamt tänkande',paragraphs:['Kahneman beskrev två sätt att tänka. Det snabba är intuitivt, automatiskt och användbart i vardagen. Det långsamma kräver koncentration och används när vi räknar, jämför eller ifrågasätter vårt första intryck.','Modellen är en pedagogisk förenkling, men den hjälper oss att förstå varför vi ibland svarar snabbt på en annan fråga än den vi faktiskt fick.']},{heading:'Förlust väger tyngre än vinst',paragraphs:['Tillsammans med Amos Tversky visade Kahneman att människor ofta reagerar starkare på en förlust än på en lika stor vinst. Det påverkar investeringar, politik och vardagsbeslut.','Vi kan därför hålla fast vid dåliga alternativ för länge eller undvika en rimlig risk eftersom den möjliga förlusten känns mer konkret än vinsten.']},{heading:'Ett verktyg, inte ett facit',paragraphs:['Kunskap om tankefel gör oss inte immuna mot dem. Det mest praktiska är att skapa processer som bromsar viktiga beslut: jämföra basfrekvenser, skriva ned antaganden och låta andra granska resonemanget.']}],ideas:['Intuition är snabb och användbar men systematiskt felbar.','Förluster upplevs ofta starkare än motsvarande vinster.','Bra beslut kräver processer som kan korrigera första intrycket.'],sources:[{label:'Nobel Prize: Daniel Kahneman – facts',url:'https://www.nobelprize.org/prizes/economic-sciences/2002/kahneman/facts/'},{label:'American Psychological Association: Daniel Kahneman',url:'https://www.apa.org/monitor/2012/02/kahneman'}]}
];
export const cultureProfileBySlug=Object.fromEntries(cultureProfiles.map(profile=>[profile.slug,profile]));
