import type { Story } from '../components/Cards';
import type { Feature } from '../components/Editorial';
export const lead:Story={section:'Världen',title:'Hormuzavtal närmar sig – men sundet förblir stängt',summary:'Iran uppger att förhandlingarna med Oman är inne i ett slutskede. Ett avtal kan ändra sjöfartslederna genom Hormuzsundet, men innebär ännu inte att den strategiska vattenvägen öppnas för normal trafik.',href:'/artikel/veckans-analys'};
export const topStories:Story[]=[
{section:'Sverige',title:'AI får större roll i valrörelsen',summary:'Inför riksdagsvalet använder väljare AI för att jämföra politik och söka svar. Samtidigt växer frågorna om manipulation, källkritik och hur tekniken påverkar valdebatten.',href:'/artikel/ai-i-valrorelsen-2026'},
{section:'Världen',title:'Ny rysk attack mot Odesas hamn',summary:'Ryssland har slagit mot hamn- och energiinfrastruktur i Odesa. Attacken skadade hamnen och orsakade omfattande strömavbrott i regionen.',href:'/artikel/odesa-hamn-attack'},
{section:'Kultur',title:'The Weeknd fyller Stockholm under tre konsertkvällar',summary:'The Weeknd spelar tre kvällar i Solna under sin rekordstora världsturné. Stockholm är turnéns enda nordiska stopp.',href:'/artikel/the-weeknd-stockholm-2026'}
];
export const swedenStories:Story[]=[
{section:'Demokrati',title:'Det första svenska valet i en vardag präglad av generativ AI',summary:'Valmyndigheter och medier ställs inför ett nytt slags påverkansrisk när övertygande falskt material kan skapas på några minuter.'},
{section:'Arbetsmarknad',title:'Tillväxten återvänder – men jobben släpar efter',summary:'Den ekonomiska återhämtningen är ojämn och kompetensgapet blir en allt tydligare politisk konflikt.'},
{section:'Energi',title:'Solkraften vänder upp och ned på dygnets elpriser',summary:'Mitt på dagen kan priset nu vara lägre än under natten, vilket förändrar hushållens incitament.'},
{section:'Samhälle',title:'Institutionernas trovärdighet blir en valfråga',summary:'Från migrationspolitik till valinformation ökar kraven på tydlighet, spårbarhet och förtroende.'},
{section:'Kommuner',title:'Lokala investeringar blir nationell ekonomisk fråga',summary:'Skolor, vatten och kollektivtrafik kräver investeringar samtidigt som många kommuner pressas av högre kostnader.'},
{section:'Utbildning',title:'Kompetensbristen flyttar fokus till yrkesutbildning',summary:'När arbetsgivare söker erfarenhet som inte finns blir utbildningens koppling till arbetsmarknaden central.'}
];
export const cultureStories:Story[]=[
{section:'Nacka · Kultur',title:'Nackas första kulturreservat invigs på lördag',summary:'Baggenstäkets kulturreservat invigs den 29 augusti klockan 11–13 kring Gammeludden och norra sidan av Stäket.',href:'https://www.nacka.se/pa-gang-i-nacka/'},
{section:'Nacka · Historia',title:'Hembygdsmuseet öppnar i Nyckelviken',summary:'På lördag håller Nacka hembygdsmuseum öppet och visar lokalt vardagsliv från 1800-talet.',href:'https://www.nacka.se/pa-gang-i-nacka/'},
{section:'Medier',title:'SVT:s besparingar kommer att märkas i höstens utbud',summary:'Ett sparpaket på 355 miljoner kronor innebär färre titlar och billigare produktioner, enligt SVT:s vd.',href:'https://www.svt.se/kultur/svts-vd-besparingarna-kommer-att-markas-i-utbudet'},
{section:'Kulturpolitik',title:'Kultursverige pressar partierna om bio, AI och arbetsvillkor',summary:'Kulturarbetare från olika delar av landet kräver besked inför valet om bland annat biografmoms och skydd mot AI.',href:'https://www.svt.se/kultur/kultursverige-staller-politikerna-mot-vaggen'},
{section:'Musik',title:'Yasin skildrar fattigdom, flykt och kriminalitet i ny låt',summary:'Den självbiografiska låten 1991 lyfts av Kulturnytt för sin direkta och personliga berättelse.',href:'https://www.sverigesradio.se/grupp/18771'},
{section:'Kulturdebatt',title:'Vem får definiera den gemensamma kulturen?',summary:'Debatten om bibliotek, public service, kulturstöd och AI handlar i grunden om vem som får tillgång till offentligheten.',href:'/kulturdebatt'}
];
export const worldFeatures:Feature[]=[
{section:'Mellanöstern · Eskalering',title:'USA och Iran utbyter nya attacker – Gulfstaterna dras närmare konflikten',summary:'USA har angripit iranska raketramper på Larakön och Iran har svarat mot amerikanska mål i Jordanien. Förenade arabemiraten uppger samtidigt att en iransk drönare stoppats över landets territorialvatten.',href:'/artikel/usa-iran-gulfstaterna',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Hormuz_map.png?width=1200',imageCredit:'Karta över Hormuzsundet · Wikimedia Commons',meta:'Uppdaterad 31 augusti kl. 14.30'},
{section:'Ukraina · Kriget',title:'Ryska drönarangrepp mot Kyiv inne på femte dagen',summary:'Nästan oavbrutna flyglarm stör transporter och vardagsliv i Ukrainas huvudstad. Fyra personer skadades på måndagen efter en våg som enligt Ukraina syftar till att trötta ut både luftförsvar och civilbefolkning.',href:'https://www.reuters.com/world/europe/russian-drone-barrage-kyiv-enters-fifth-day-disrupting-life-across-capital-2026-08-31/',image:'https://cassette.sphdigital.com.sg/image/straitstimes/d61a1cfa70d0ac99cf9d682f8ab2f2925c4fdb1c6084abe90bca321baf32d86e',imageCredit:'Räddningsarbete i Ukraina · EPA · augusti 2026',meta:'Uppdaterad 31 augusti kl. 11.22'},
{section:'Nepal · Naturkatastrof',title:'Hundratals söks i tunnlar efter dödliga översvämningar',summary:'Räddningslag söker människor som befaras vara instängda i vattenkraftstunnlar efter störtfloder och jordskred nära gränsen mellan Nepal och Tibet. Nya sjöar och fortsatt dåligt väder försvårar arbetet.',href:'https://www.reuters.com/world/china/nepal-teams-seek-hundreds-trapped-hydropower-tunnels-after-deadly-floods-2026-08-31/',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Nepal.svg?width=900',imageCredit:'Nepals flagga · Wikimedia Commons',meta:'Uppdaterad 31 augusti kl. 10.30'},
{section:'Ukraina · Diplomati',title:'Modi uppmanar Putin att avsluta kriget för mänsklighetens skull',summary:'Indiens premiärminister Narendra Modi sade vid mötet i Bisjkek att kriget måste få ett slut. Indien fortsätter samtidigt att köpa stora mängder rysk olja och behåller nära ekonomiska band till Moskva.',href:'https://www.reuters.com/world/europe/indias-modi-tells-russias-putin-that-war-ukraine-must-end-humanitys-sake-2026-08-31/',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20India.svg?width=1000',imageCredit:'Indiens flagga · Wikimedia Commons',meta:'Uppdaterad 31 augusti kl. 14.00'},
{section:'Klimat · Hav',title:'Korallreven hinner inte återhämta sig mellan värmechockerna',summary:'En global sammanställning från närmare 37 000 platser visar att tiden mellan omfattande blekningsepisoder har krympt till fem–sex år. Det är för kort för många rev att bygga upp motståndskraft igen.',href:'https://www.reuters.com/business/environment/coral-bleaching-occurring-too-frequently-reefs-recover-scientists-say-2026-08-31/',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Coral%20Reef.jpg?width=1000',imageCredit:'Korallrev · Wikimedia Commons',meta:'Uppdaterad 31 augusti kl. 09.45'},
{section:'Världsekonomi · Energi',title:'Oljepriset väntas ligga över 80 dollar när Hormuzrisken består',summary:'En Reutersenkät bland 31 ekonomer och analytiker visar att störningar kopplade till USA–Iran-konflikten håller uppe prognoserna. Svagare kinesisk efterfrågan begränsar samtidigt uppgången.',href:'https://www.reuters.com/world/asia-pacific/oil-hold-above-80-barrel-middle-east-supply-risks-persist-2026-08-31/',image:'https://commons.wikimedia.org/wiki/Special:FilePath/BlankMap-World.svg?width=1000',imageCredit:'Världskarta · Wikimedia Commons',meta:'Uppdaterad 31 augusti kl. 13.50'}
];
