import type {DeskDepthItem,DeskSource} from '../components/DeskDepth';
type Desk={intro:string;items:DeskDepthItem[];sources:DeskSource[]};

export const knowledgeDepth:Desk={intro:'Kunskapssidorna ska inte bara definiera begrepp. De ska visa hur läsaren granskar siffror, skiljer samband från orsak och använder bakgrunden för att förstå dagens nyheter.',items:[
 {title:'Så läser du en uppgift kritiskt',news:'En siffra blir begriplig först när tidsperiod, jämförelse och mätmetod är kända. Samma utveckling kan se dramatisk eller obetydlig ut beroende på vilken startpunkt som väljs.',analysis:'Läsaren behöver därför fråga vem som har mätt, vad som ingår och vad som saknas. Officiell statistik är ofta bästa utgångspunkten, men även den måste tolkas i sitt sammanhang.',depth:'Kunskap uppstår när flera oberoende uppgifter pekar åt samma håll och osäkerheten redovisas öppet. NackaPedia kopplar därför definitioner till tidslinjer, nyckelpunkter och relaterade artiklar.'},
 {title:'Skillnaden mellan fakta, prognos och analys',news:'Fakta beskriver verifierade förhållanden. En prognos är en modellbaserad bedömning av framtiden, medan analysen förklarar vilka mekanismer som kan driva utvecklingen.',analysis:'När kategorierna blandas ihop kan en osäker bedömning uppfattas som ett fastslaget resultat. Tydlig märkning gör det lättare att förstå vad som kan ändras.',depth:'En bra analys ska kunna motbevisas. Den bör ange vilka observationer som stöder slutsatsen, vilka alternativa förklaringar som finns och vilka nya besked som skulle kräva en omprövning.'},
 {title:'Från ordlista till större sammanhang',news:'Begrepp som inflation, språkmodell och riskpremie används ofta som om alla menar samma sak. I praktiken rymmer de metodval och antaganden som påverkar slutsatsen.',analysis:'Ordlistan är därför början, inte slutet. När ett begrepp kopplas till historia, mätning och praktiska följder blir det ett verktyg för självständig bedömning.',depth:'Målet är att läsaren ska kunna återvända till kunskapssidan när en ny händelse inträffar och förstå både vad som är nytt och vad som följer ett äldre mönster.'}
],sources:[{label:'SCB: statistik och metod',url:'https://www.scb.se/'},{label:'Riksbanken: förklaringar och penningpolitik',url:'https://www.riksbank.se/sv/penningpolitik/'},{label:'EU-kommissionen: AI och reglering',url:'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai'}]};

export const aiDepth:Desk={intro:'AI Insight följer steget från imponerande demonstrationer till system som påverkar arbete, demokrati och offentliga beslut.',items:[
 {title:'AI flyttar från verktyg till arbetsflöde',news:'Organisationer går från enskilda chattverktyg till system som söker information, skriver utkast, granskar data och föreslår nästa åtgärd i flera steg.',analysis:'Produktivitetsvinsten kan bli större, men också kostnaden för ett fel. När samma misstag upprepas automatiskt kan bristande kvalitet spridas genom en hel verksamhet.',depth:'Det viktigaste är därför inte bara modellvalet utan processen runt modellen: behörigheter, källkontroll, loggning, mänskligt godkännande och tydligt ansvar när ett beslut får konsekvenser.'},
 {title:'Valrörelsen blir ett test av informationsmiljön',news:'Generativ AI gör det billigare att skapa övertygande text, bild, ljud och video. Samtidigt använder väljare AI-tjänster för att sammanfatta partiernas politik.',analysis:'Tekniken kan öka tillgången till information men också göra avsändare och originalkällor svårare att identifiera. Plattformarnas märkning och mediernas verifiering blir demokratisk infrastruktur.',depth:'Det långsiktiga svaret kan inte vara att misstro allt digitalt innehåll. Samhället behöver spårbar publicering, snabb rättelse, mediekunnighet och primärkällor som går att kontrollera utan specialverktyg.'},
 {title:'Kompetens blir viktigare när modellerna förbättras',news:'Bättre modeller minskar vissa enkla fel men gör samtidigt svaren mer övertygande. Användaren måste fortfarande kunna bedöma rimlighet, metod och källa.',analysis:'Yrken försvinner sällan i ett enda steg. Arbetsuppgifter omfördelas, kvalitetskrav förändras och den som kan kombinera ämneskunskap med AI får ett övertag.',depth:'Utbildning behöver därför omfatta både praktisk användning och förmåga att avstå. Att veta när en modell saknar rätt data eller när ett mänskligt samtal krävs blir en central professionell färdighet.'}
],sources:[{label:'EU-kommissionen: AI-förordningen',url:'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai'},{label:'OECD AI Policy Observatory',url:'https://oecd.ai/'},{label:'NIST: AI Risk Management Framework',url:'https://www.nist.gov/itl/ai-risk-management-framework'}]};

export const scienceDepth:Desk={intro:'Forskningsnyheter behöver tåla en hårdare granskning än själva pressmeddelandet. Här sätts resultaten i metodiskt, kliniskt och samhälleligt sammanhang.',items:[
 {title:'Ett genombrott är början på prövningen',news:'Många forskningsnyheter bygger på ett första experiment, en liten patientgrupp eller en modell som testats i kontrollerad miljö.',analysis:'Resultatet kan vara viktigt utan att vara redo för bred användning. Reproducerbarhet, jämförelsegrupp och långsiktig säkerhet avgör hur stark evidensen verkligen är.',depth:'Vägen från laboratorium till samhälle innehåller oberoende replikation, större studier, regulatorisk granskning och uppföljning efter införandet. Varje steg kan både bekräfta och begränsa det ursprungliga fyndet.'},
 {title:'Medicinsk AI förändrar ansvarskedjan',news:'AI används allt närmare patienten, bland annat för bildanalys, matchning till kliniska studier och stöd under operationer.',analysis:'När rådet påverkar ett pågående vårdbeslut måste systemets osäkerhet vara synlig. Läkaren behöver kunna avvika, och händelsen måste gå att rekonstruera i efterhand.',depth:'Sjukhusens upphandling, datakvalitet och rapportering av avvikelser blir lika viktiga som algoritmens precision. Teknikens värde mäts ytterst i patientutfall, inte i hur avancerad modellen verkar.'},
 {title:'Vetenskapens nya flaskhals är oberoende kontroll',news:'Kraftfulla modeller och dyr laboratorieutrustning koncentreras till ett mindre antal företag och universitet.',analysis:'Det kan skynda på forskning men försvåra oberoende granskning. Om data, kod eller beräkningsresurser saknas blir resultatet svårare att pröva.',depth:'Öppen metodredovisning och samarbete mellan institutioner blir därför centralt. Forskningen måste kunna skilja verklig förbättring från resultat som beror på ett särskilt testmaterial eller en resurs som få andra kan använda.'}
],sources:[{label:'Nature: forskningsnyheter och originalstudier',url:'https://www.nature.com/'},{label:'NIH: medicinsk forskning',url:'https://www.nih.gov/'},{label:'EU-kommissionen: forskning och innovation',url:'https://research-and-innovation.ec.europa.eu/'}]};

export const stockholmDepth:Desk={intro:'Stockholmsbevakningen förklarar hur trafik, bostäder, trygghet och kommunala beslut hänger ihop över stadsdelsgränserna.',items:[
 {title:'Bostadsbyggandet avgör mer än antalet nya lägenheter',news:'Nya bostäder kräver mark, finansiering, detaljplan, vägar, kollektivtrafik, skolor och annan kommunal service.',analysis:'När räntor och byggkostnader stiger kan projekt försenas även om efterfrågan är stor. Konsekvensen blir längre köer, högre trösklar för unga och större press på befintliga områden.',depth:'Den relevanta frågan är därför vilken typ av bostäder som byggs, var de placeras och om infrastrukturen kommer samtidigt. Ett högt planmål utan genomförbara projekt förbättrar inte bostadsmarknaden.'},
 {title:'Trafikbeslut fördelar tid och tillgänglighet',news:'Förändringar i kollektivtrafik, vägar och parkering påverkar olika grupper beroende på bostadsort, arbetstid och möjlighet att välja färdsätt.',analysis:'En åtgärd kan minska utsläpp och trängsel men samtidigt skapa nya kostnader för den som saknar alternativ. Därför måste restid, kapacitet, tillgänglighet och fördelning bedömas tillsammans.',depth:'Stockholms kommun, Region Stockholm och staten styr olika delar av systemet. Tydlig ansvarsfördelning är nödvändig för att löften ska kunna följas från beslut till finansiering och faktisk trafik.'},
 {title:'Lokala beslut blir regionala konsekvenser',news:'Arbetsplatser, bostäder och service är fördelade över flera kommuner medan invånarna rör sig över administrativa gränser varje dag.',analysis:'En kommun kan vinna skatteunderlag av en etablering medan grannkommunen får mer trafik eller behov av bostäder. Samordningen påverkar om regionen växer effektivt eller bygger in nya flaskhalsar.',depth:'Lokal journalistik behöver därför följa både den enskilda nämnden och det regionala sambandet. Först då går det att se vem som fattar beslutet, vem som betalar och vilka invånare som påverkas.'}
],sources:[{label:'Stockholms stad: beslut och statistik',url:'https://start.stockholm/'},{label:'Region Stockholm',url:'https://www.regionstockholm.se/'},{label:'Trafikverket: Stockholm',url:'https://www.trafikverket.se/'}]};

export const swedenDepth:Desk={intro:'Sverigesidan går längre än valrörelsens utspel och knyter samman ekonomi, välfärd, säkerhet och regeringsfrågan.',items:[
 {title:'Valet avgör mandat men inte automatiskt regeringen',news:'Partiernas röda linjer gör flera matematiska majoriteter politiskt svåra. Statsministerfrågan följs dessutom av förhandlingar om budget och sakpolitik.',analysis:'En regering kan tolereras av riksdagen men ändå sakna stabilt stöd för större reformer. Små mandatförskjutningar kan därför få större effekt än blockens samlade röstandel antyder.',depth:'Efter valdagen blir ansvar och kompromissförmåga centrala. Väljarna behöver kunna se skillnaden mellan regeringsmedverkan, budgetsamarbete och stöd i enskilda frågor.'},
 {title:'Återhämtningen prövas på arbetsmarknaden',news:'Starkare BNP och lägre inflation ger en bättre makrobild, men hushållens konsumtion och sysselsättningen utvecklas långsammare.',analysis:'Väljare bedömer ekonomin genom lön, boendekostnad och jobbtrygghet snarare än ett nationellt genomsnitt. Därför kan statistisk återhämtning och ekonomisk oro finnas samtidigt.',depth:'En bred vändning kräver fler arbetade timmar, investeringar och produktivitetsökningar som också når kommunernas skatteunderlag. Annars blir förbättringen ojämn mellan regioner och grupper.'},
 {title:'Säkerhetspolitiken blir en lång budgetfråga',news:'Försvar, beredskap, energisystem och stöd till Ukraina kräver fleråriga beslut snarare än enstaka krispaket.',analysis:'Nya åtaganden konkurrerar med välfärd och investeringar om arbetskraft och offentliga resurser. Politikens trovärdighet avgörs av finansiering och genomförandekapacitet.',depth:'Det större perspektivet är att säkerhet inte bara består av militär förmåga. Robust elförsörjning, transporter, sjukvård, informationssäkerhet och förtroende för institutioner avgör hur samhället klarar långvarig press.'}
],sources:[{label:'SCB: Sverige i siffror',url:'https://www.scb.se/'},{label:'Valmyndigheten: val 2026',url:'https://www.val.se/'},{label:'Regeringen: svensk säkerhetspolitik',url:'https://www.regeringen.se/regeringens-politik/sakerhetspolitik/'}]};

export const analysisDepth:Desk={intro:'Analysdelen visar inte bara en slutsats utan också hur den har byggts, vilka invändningar som finns och vad som skulle kunna ändra bedömningen.',items:[
 {title:'Från händelse till mekanism',news:'En nyhet berättar vad som har hänt. Analysen försöker identifiera den mekanism som kopplar händelsen till ekonomi, makt, institutioner eller människors beteende.',analysis:'Den starkaste förklaringen är inte alltid den mest dramatiska. Den ska passa kända fakta, förklara mer än ett enskilt fall och tåla jämförelse med alternativa orsaker.',depth:'Därför innehåller varje längre analys huvudtes, belagda fakta, konsekvenser, osäkerheter och signaler att följa. Läsaren ska kunna se var faktaunderlaget slutar och redaktionens tolkning börjar.'},
 {title:'Konsekvenser kommer i olika tidsskalor',news:'Den omedelbara effekten kan synas i priser, beslut eller opinion medan institutionella och sociala följder tar månader eller år.',analysis:'En kortsiktig vinnare kan bli långsiktig förlorare om anpassningen förändrar investeringar eller förtroende. Analysen måste därför skilja reaktion från varaktig förändring.',depth:'Scenarier används inte som exakta prognoser utan som prövning av resonemanget. De visar vilka antaganden som bär slutsatsen och vilka händelser som skulle leda utvecklingen åt ett annat håll.'},
 {title:'Osäkerhet gör analysen starkare',news:'Källor kan vara ofullständiga, parter kan ha egna intressen och statistik kan publiceras med eftersläpning.',analysis:'Att redovisa osäkerhet är inte ett tecken på svaghet. Det hindrar en rimlig tolkning från att presenteras som säker kunskap och gör senare rättelser begripliga.',depth:'NackaSidan placerar därför källorna sist men tydligt, efter nyhet, analys och fördjupning. Läsaren kan följa underlaget, väga redaktionens slutsats och själv gå vidare till primärkällorna.'}
],sources:[{label:'Reuters: internationell nyhetsrapportering',url:'https://www.reuters.com/'},{label:'SVT Nyheter',url:'https://www.svt.se/nyheter/'},{label:'SCB: officiell svensk statistik',url:'https://www.scb.se/'}]};
