import type {LiveNewsItem} from '../lib/liveNews';

export const editorialEconomyNews:LiveNewsItem[]=[
 {title:'Riksbankens räntebesked står i centrum för svenska hushåll och företag',link:'https://www.riksbank.se/sv/press-och-publicerat/kalender/',published:'2026-09-23T18:30:00Z',source:'Riksbanken',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,summary:'Riksbanken publicerar ett nytt penningpolitiskt beslut den 24 september. Styrräntan är inför beskedet 1,75 procent. Marknaden följer särskilt hur energipriser, inflation och konjunktur påverkar räntebanan.'},
 {title:'Svenska hushåll lånar mer samtidigt som konsumtionen stiger',link:'https://www.scb.se/',published:'2026-09-23T17:45:00Z',source:'SCB',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,summary:'SCB:s senaste statistik visar att hushållens årliga lånetillväxt har ökat och att konsumtionen steg i augusti. Utvecklingen tyder på bättre aktivitet, men hushållens marginaler är fortfarande känsliga för räntor och priser.'},
 {title:'Kronan och bolånen väntar på nya signaler om svensk ränta',link:'https://www.riksbank.se/sv/statistik/',published:'2026-09-23T16:50:00Z',source:'Riksbanken',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,summary:'Kronkursen och bankernas finansieringskostnader påverkas av förväntningarna inför Riksbankens besked. En oförändrad styrränta behöver inte innebära oförändrade bolåneräntor, eftersom marknadsräntor och konkurrens också spelar in.'},
 {title:'Oljepriset nära 100 dollar gör inflationen svårare att bedöma',link:'https://www.reuters.com/business/energy/oil-rises-slightly-ahead-potential-us-iran-talks-2026-09-22/',published:'2026-09-22T20:30:00Z',source:'Reuters · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,summary:'Oljepriset ligger nära 100 dollar per fat medan marknaden följer samtalen mellan USA och Iran. Ett varaktigt högt oljepris kan öka transport- och produktionskostnader och göra räntesänkningar svårare.'},
 {title:'Kinas yuan når flerårshögsta inför mötet mellan Xi och Trump',link:'https://www.reuters.com/world/asia-pacific/yuan-hits-fresh-multi-year-peak-pboc-eases-curb-ahead-trump-xi-summit-2026-09-21/',published:'2026-09-22T14:20:00Z',source:'Reuters · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,summary:'Yuanen har stärkts till sin högsta nivå på mer än tre år. Rörelsen kopplas till centralbankens mindre hårda motstånd mot en starkare valuta och förväntningar inför USA–Kina-mötet om handel och tullar.'},
 {title:'EU:s nya industriplan kan rita om leveranskedjorna',link:'https://www.reuters.com/world/uk/what-is-brussels-made-eu-law-why-is-britain-worried-2026-09-22/',published:'2026-09-22T12:10:00Z',source:'Reuters · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,summary:'Förslaget Made in EU ska gynna europeiskt innehåll och produktion med låga utsläpp i strategiska sektorer. Reglerna kan påverka svensk industri inom stål, fordon, batterier, energi och offentlig upphandling.'},
 {title:'Europa riskerar brist på flygbränsle under fjärde kvartalet',link:'https://www.reuters.com/business/energy/europe-faces-q4-jet-fuel-supply-deficit-even-south-korea-becomes-latest-big-2026-09-21/',published:'2026-09-21T15:35:00Z',source:'Reuters · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,summary:'Europeiska lager av flygbränsle är pressade och importen från bland annat Sydkorea ökar. Bristen kan höja kostnaderna för flygbolag och resenärer och visar Europas känslighet för störningar i energihandeln.'},
 {title:'Kinas exportstyrka höjer insatsen i handelssamtalen med USA',link:'https://www.reuters.com/world/china/xi-rolls-into-trump-summit-with-chinas-trade-engine-roaring-2026-09-21/',published:'2026-09-21T11:15:00Z',source:'Reuters · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,summary:'Kinas export har fortsatt växa trots amerikanska tullar. Inför toppmötet blir en förlängd handelsfred viktigare än stora genombrott, med direkta följder för industriföretag, jordbruk och globala marknader.'}
];
