import type {LiveNewsItem} from '../lib/liveNews';
export const editorialEconomyNews:LiveNewsItem[]=[
 {title:'Sveriges handelsnetto visar underskott på 11,9 miljarder kronor',link:'https://www.scb.se/hitta-statistik/statistik-efter-amne/naringsverksamhet-och-utrikeshandel/utrikeshandel/utrikeshandel-med-varor/pong/statistiknyhet/varuexport-varuimport-och-handelsnetto-augusti-2026-i-lopande-priser/',published:'2026-09-28T08:00:00+02:00',source:'SCB',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,image:'https://commons.wikimedia.org/wiki/Special:FilePath/Port%20of%20Gothenburg.jpg?width=1200',summary:'Varuhandeln gav ett underskott på 11,9 miljarder kronor i augusti. Siffran blir viktig för bedömningen av exportindustrin, kronan och hur svag internationell efterfrågan påverkar svensk tillväxt.'},
 {title:'Svensk varuhandel försvagades i juli',link:'https://www.scb.se/hitta-statistik/statistik-efter-amne/naringsverksamhet-och-utrikeshandel/utrikeshandel/utrikeshandel-med-varor/pong/statistiknyhet/export-och-import-av-varor-juli-2026-i-lopande-och-fasta-priser/',published:'2026-09-28T07:59:00+02:00',source:'SCB',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,image:'https://commons.wikimedia.org/wiki/Special:FilePath/Container%20ship%20at%20sea.jpg?width=1200',summary:'Både export och import utvecklades svagare i juli jämfört med juni. Nedgången visar att svensk industri fortfarande påverkas av osäker världshandel och försiktiga investeringar.'},
 {title:'USA och Kina förbereder möjliga tullsänkningar',link:'https://www.aljazeera.com/economy/2026/9/28/us-china-list-goods-recommended-for-tariff-cuts-following-trump-xi-summit',published:'2026-09-28T06:24:33Z',source:'Al Jazeera · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,image:'https://commons.wikimedia.org/wiki/Special:FilePath/Flags%20of%20the%20United%20States%20and%20China.jpg?width=1200',summary:'Länderna har pekat ut varor som kan få lägre tullar efter Trump–Xi-mötet. Ett genomförande skulle minska kostnader i vissa leveranskedjor men lämnar teknik- och säkerhetskonflikterna olösta.'},
 {title:'Storbritannien utlovar en ny industrialiseringsvåg',link:'https://www.bbc.co.uk/news/articles/cjdx53edkglgo',published:'2026-09-28T03:01:47Z',source:'BBC Business · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,image:'https://ichef.bbci.co.uk/ace/standard/1024/cpsprodpb/44ef/live/05e9aa10-bac1-11f1-b327-372771fd59f2.jpg',summary:'Den brittiska regeringen vill stärka industri, investeringar och produktivitet. Avgörande blir om politiken löser energi-, kompetens- och finansieringsproblem i stället för att stanna vid nya stödprogram.'},
 {title:'Stor del av Storbritanniens matproduktion finns i områden med torkarisk',link:'https://www.theguardian.com/business/2026/sep/27/most-of-uks-essential-food-supply-grown-in-drought-risk-areas-report-warns',published:'2026-09-27T16:24:27Z',source:'The Guardian · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,image:'https://i.guim.co.uk/img/media/2caccc1073149a04f14f7198d611d1f9ce0502a4/414_0_4172_3338/master/4172.jpg?width=1200&quality=85&auto=format&fit=max',summary:'En ny rapport varnar för att viktiga grödor odlas i områden där vattenbrist kan bli vanligare. Klimatrisker blir därmed en fråga om matpriser, investeringar och försörjningssäkerhet.'},
 {title:'Förstagångsköpare behöver omkring 17 000 pund i eget kapital',link:'https://www.bbc.co.uk/news/articles/cqvgy09kep21o',published:'2026-09-27T23:20:43Z',source:'BBC Business · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,image:'https://commons.wikimedia.org/wiki/Special:FilePath/Terraced%20houses%20in%20England.jpg?width=1200',summary:'Den brittiska bostadsmarknaden visar hur höga kontantinsatser stänger ute unga hushåll. Situationen har tydliga paralleller till svenska storstäder där sparande, familjestöd och kreditvillkor avgör inträdet.'},
 {title:'Avanti West Coast ska förstatligas i mars',link:'https://www.bbc.co.uk/news/articles/c60qxk7d2539o',published:'2026-09-28T03:05:50Z',source:'BBC Business · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,image:'https://commons.wikimedia.org/wiki/Special:FilePath/Avanti%20West%20Coast%20train.jpg?width=1200',summary:'Den brittiska tågoperatören förs över i statlig regi. Beslutet blir ett test av om offentlig kontroll kan förbättra punktlighet och service utan att kostnaderna stiger.'},
 {title:'Lime fördubblar vinsten när cykelresorna ökar',link:'https://www.theguardian.com/world/2026/sep/27/lime-bike-profits-double-rider-numbers-surge-england',published:'2026-09-27T14:24:16Z',source:'The Guardian · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,image:'https://commons.wikimedia.org/wiki/Special:FilePath/LimeBike.jpg?width=1200',summary:'Fler resenärer väljer delade elcyklar i England och bolagets vinst har fördubblats. Tillväxten visar både efterfrågan på mikromobilitet och kommunernas behov av tydliga regler för parkering och säkerhet.'}
];
