import type {LiveNewsItem} from '../lib/liveNews';
export const editorialEconomyNews:LiveNewsItem[]=[
 {title:'Riksbankschefen varnar nästa regering: löften måste finansieras',link:'https://www.svt.se/nyheter/inrikes/riksbankschefens-varning-till-regeringen-annars-gar-inte-ekvationen-ihop',published:'2026-09-26T15:45:00Z',source:'SVT Ekonomi',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,summary:'Riksbankschefen varnar för att ofinansierade reformer kan öka efterfrågan och göra inflationsarbetet svårare. Budskapet till nästa regering är att budgetlöften behöver vägas mot skatter, besparingar eller ett tydligt finanspolitiskt utrymme.'},
 {title:'Oro i Hormuz håller energipriser och inflation i fokus',link:'https://www.theguardian.com/world/2026/sep/26/trump-dismiss-iran-seven-day-peace-deal-hormuz',published:'2026-09-26T16:20:00Z',source:'The Guardian · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,summary:'Donald Trump avvisar Irans förslag om en sju dagars uppgörelse kring Hormuzsundet. Fortsatt osäkerhet kan höja kostnaderna för olja, frakt och försäkringar och därmed bromsa inflationsnedgången.'},
 {title:'Ny brittisk modell ska hjälpa förstagångsköpare in på bostadsmarknaden',link:'https://www.theguardian.com/politics/2026/sep/26/andy-burnham-announces-new-scheme-for-first-time-home-buyers-england',published:'2026-09-26T14:50:00Z',source:'The Guardian · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,summary:'Ett nytt förslag i England ska sänka tröskeln för förstagångsköpare. Debatten speglar ett internationellt problem: höga priser, svag nyproduktion och dyrare finansiering stänger ute unga hushåll.'},
 {title:'En liten komponent bromsar USA:s militära produktion',link:'https://www.nytimes.com/2026/09/26/business/ball-screws-military-production.html',published:'2026-09-26T13:40:00Z',source:'New York Times · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Hög',local:false,summary:'Brist på precisionskomponenten kulskruvar har blivit en flaskhals i amerikansk försvarsproduktion. Fallet visar hur sårbara avancerade leveranskedjor är när få leverantörer behärskar kritisk tillverkning.'},
 {title:'AI pressar advokatbyråernas modell med debiterade timmar',link:'https://www.nytimes.com/2026/09/26/business/dealbook/ai-law-discount-billable-hour.html',published:'2026-09-26T12:55:00Z',source:'New York Times · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,summary:'När AI gör research och dokumentarbete snabbare kräver kunder lägre priser och nya avtalsformer. Tekniken kan flytta värdet från arbetad tid till resultat, ansvar och specialistkunskap.'},
 {title:'Storbritannien skärper arbetet mot dyr vidareförsäljning av biljetter',link:'https://www.theguardian.com/business/2026/sep/26/work-intensifying-uk-laws-stamp-out-concert-ticket-touts',published:'2026-09-26T11:30:00Z',source:'The Guardian · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,summary:'Nya regler mot professionella biljettuppköpare förbereds. Frågan gäller konkurrens och konsumentskydd på digitala marknadsplatser där automatiserade köp kan driva upp priserna.'},
 {title:'Handelskonflikten med Kanada märks i Maines gränsekonomi',link:'https://www.theguardian.com/us-news/ng-interactive/2026/sep/26/maine-voters-canada-trump-trade-war',published:'2026-09-26T10:40:00Z',source:'The Guardian · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,summary:'Företag och väljare i Maine beskriver svagare gränshandel när konflikten mellan USA och Kanada fördjupas. Lokala ekonomier visar hur tullar får följder långt från de nationella förhandlingsrummen.'},
 {title:'USA:s oljeavtal med Venezuela möter nya frågor',link:'https://www.theguardian.com/us-news/2026/sep/26/donald-trump-oil-deal-with-venezuela',published:'2026-09-26T09:35:00Z',source:'The Guardian · svensk sammanfattning',sourceSection:'Ekonomi',section:'Ekonomi',priority:'Medel',local:false,summary:'Avtalet kan påverka utbud, sanktioner och energipriser men väcker frågor om villkor och geopolitisk risk. Marknaden behöver skilja politiska besked från faktiska och uthålliga leveranser.'}
];
