export const editorial365 = [
  {section:'Sverige · Val 2026',date:'23 augusti',title:'Oppositionen leder stort när valrörelsen går in i slutspurten',summary:'En Verianmätning för SVT ger de fyra rödgröna partierna 53,9 procent mot 43,9 procent för regeringsunderlaget. Socialdemokraterna är största parti på 30,5 procent.',why:'Med tre veckor kvar till valdagen blir ekonomi, trygghet, migration, brott och energiförsörjning centrala frågor i slutspurten.',source:'Reuters',href:'https://www.reuters.com/world/europe/swedish-opposition-holds-big-lead-ahead-september-vote-poll-shows-2026-08-18/'},
  {section:'Sverige',date:'23 augusti',title:'Skolattacken i Fagersta sätter tryggheten i fokus',summary:'En person dödades och tre skadades vid attacken mot Brinellgymnasiet i Fagersta. En 18-årig misstänkt greps efter polisinsatsen.',why:'Händelsen väcker nya frågor om skolors säkerhet och hur våldsdåd kan förebyggas.',source:'Reuters',href:'https://www.reuters.com/world/europe/several-people-injured-sword-attack-swedish-school-municipality-says-2026-08-21/'},
  {section:'Utrikes · Ukraina',date:'23 augusti',title:'Zelenskyj varnar för val mitt under kriget',summary:'Ukrainas president säger att ett nationellt val under pågående krig riskerar att splittra landet. Ukrainas lag förbjuder val under krigstillstånd.',why:'Frågan går rakt in i Ukrainas demokratiska legitimitet samtidigt som miljontals människor är på flykt, i ockuperade områden eller vid fronten.',source:'Reuters',href:'https://www.reuters.com/world/europe/wartime-election-would-destroy-ukraine-zelenskiy-says-2026-08-23/'},
  {section:'Utrikes · Europa',date:'23 augusti',title:'Europas ledare samlar Ukrainas stödkoalition',summary:'Frankrike, Storbritannien och Tyskland ska leda måndagens möte med Coalition of the Willing. Zelenskyj deltar från Kyiv.',why:'Mötet blir ett test på Europas förmåga att hålla ihop stödet när kriget fortsätter och de diplomatiska genombrotten uteblir.',source:'Reuters',href:'https://www.reuters.com/world/europe/french-british-german-leaders-co-chair-meeting-ukraine-monday-2026-08-21/'},
  {section:'Utrikes · USA',date:'23 augusti',title:'Trump går mot mellanårsval med flera utrikespolitiska låsningar',summary:'Iran, Gaza och Ukraina är fortfarande olösta samtidigt som högre bensinpriser och inflation ökar det inrikespolitiska trycket.',why:'USA:s politiska läge påverkar både säkerhetspolitiken i Europa och möjligheten till diplomatiska uppgörelser i Mellanöstern.',source:'Reuters',href:'https://www.reuters.com/world/us/trump-heads-into-midterms-short-foreign-policy-wins-2026-08-22/'},
  {section:'Nacka · Skola',date:'21 augusti',title:'SAO-jobb ska ge högstadieelever riktig arbetslivserfarenhet',summary:'Nacka kommun har ingått en avsiktsförklaring med Nästa generation Sverige om en modell där högstadieelever får betalt arbete inom ramen för undervisningen.',why:'Modellen kan skapa tidigare kontakt mellan unga och arbetslivet och blir samtidigt en konkret lokal skolfråga inför valet.',source:'Nacka kommun',href:'https://www.nacka.se/'},
  {section:'Nacka · Val 2026',date:'21 augusti',title:'Valaffischerna är uppe – kommunen förtydligar reglerna',summary:'Inför valet den 13 september har kommunen publicerat ett klargörande om vad som gäller för valaffischering runt om i Nacka.',why:'När förtidsröstningen närmar sig flyttar valrörelsen från program och debatter ut i det offentliga rummet.',source:'Nacka kommun',href:'https://www.nacka.se/nyheter-start/'},
  {section:'Nacka · Fritid',date:'17 augusti',title:'Nackas Fritidsbibliotek har öppnat',summary:'Nackabor kan nu kostnadsfritt låna bland annat skateboards, sovsäckar, simutrustning och bollar vid Nacka sportcentrum.',why:'Gratis utlåning sänker tröskeln till fritidsaktiviteter och kan göra idrott och friluftsliv tillgängligt för fler.',source:'Nacka kommun',href:'https://www.nacka.se/nyheter-start/'},
  {section:'Nacka · Trafik',date:'14 augusti',title:'Nya pendelbåtsbryggan i Nacka strand är i trafik',summary:'SL och skärgårdstrafiken började använda den nya bryggan den 17 augusti.',why:'Bättre sjötrafik ger fler alternativ till bil och buss när Nacka växer och stora trafikprojekt pågår.',source:'Nacka kommun',href:'https://www.nacka.se/nyheter-start/'},
  {section:'Nacka · Trafiksäkerhet',date:'13 augusti',title:'Skolstarten sätter fokus på barnen i trafiken',summary:'Kommunen uppmanar trafikanter att vara extra uppmärksamma när skolorna öppnar efter sommarlovet.',why:'Ökad trafik kring skolor sammanfaller med att många yngre barn börjar röra sig mer självständigt.',source:'Nacka kommun',href:'https://www.nacka.se/nyheter-start/'}
] as const;
