export const editorial365 = [
  {section:'Nacka · Val 2026',date:'23 augusti',title:'Tre dagar kvar till förtidsröstningen i Nacka',summary:'Förtidsröstningen inför valen till riksdag, region och kommun startar onsdag 26 augusti och fortsätter varje dag fram till valdagen 13 september.',why:'Nu går valrörelsen in i ett skarpare skede. NackaSidan följer både de praktiska valfrågorna och de lokala politiska skiljelinjerna.',source:'Nacka kommun',href:'https://www.nacka.se/kommun--politik/delta-och-paverka/val-2026/'},
  {section:'Sverige · Val 2026',date:'23 augusti',title:'Oppositionen leder med tio procentenheter inför valet',summary:'Verians mätning för SVT ger de fyra oppositionspartierna 53,9 procent mot 43,9 procent för regeringsunderlaget. Socialdemokraterna är största parti på 30,5 procent.',why:'Med valdagen den 13 september närmar sig slutspurten snabbt och väljarnas syn på ekonomi, trygghet, migration, brott och energi blir avgörande.',source:'Reuters',href:'https://www.reuters.com/world/europe/swedish-opposition-holds-big-lead-ahead-september-vote-poll-shows-2026-08-18/'},
  {section:'Sverige · Trygghet',date:'23 augusti',title:'Polisen granskar nätmiljöer efter skolattacken i Fagersta',summary:'Utredarna undersöker om den misstänkte 18-åringen påverkats av nätmiljöer där tidigare skolattacker och massvåld glorifieras. En 17-årig flicka dödades och två pojkar skadades svårt.',why:'Utredningen fördjupar frågan om skoltrygghet och hur våldsbejakande nätmiljöer kan påverka unga.',source:'Reuters',href:'https://www.reuters.com/world/europe/swedish-police-probe-online-networks-after-teenage-girl-killed-school-sword-2026-08-22/'},
  {section:'Utrikes · Gaza',date:'23 augusti',title:'Medlare varnar för att nya attacker försvårar Gaza-processen',summary:'Turkiet, Egypten och Qatar säger att de senaste israeliska attackerna i Gaza riskerar att undergräva försöken att genomföra planen för att avsluta konflikten.',why:'Oenigheten om ordningen mellan Hamas avväpning och israeliskt tillbakadragande är fortfarande ett centralt hinder för en hållbar uppgörelse.',source:'Reuters',href:'https://www.reuters.com/world/middle-east/turkey-egypt-qatar-condemn-israeli-attacks-gaza-call-israel-comply-with-2026-08-20/'},
  {section:'Utrikes · Iran/USA',date:'23 augusti',title:'Iran avfärdar USA:s nya sanktionshot',summary:'Teheran säger att Washingtons planerade nya ekonomiska sanktioner inte kommer att tvinga Iran att ge efter. Osäkerheten kring Hormuzsundet fortsätter samtidigt att prägla energimarknaden.',why:'Konflikten påverkar energipriser, världshandel och säkerhetsläget i hela Mellanöstern.',source:'Reuters',href:'https://www.reuters.com/world/asia-pacific/iran-says-new-sanctions-threatened-by-desperate-us-will-fail-2026-08-23/'},
  {section:'Ekonomi · Energi',date:'23 augusti',title:'Hormuzoron håller oljepriset på hög nivå',summary:'Brentoljan steg tidigare i veckan till nära den högsta nivån på fyra veckor när osäkerheten kring exporten genom Hormuz ökade.',why:'Dyrare olja kan snabbt slå mot inflation, transporter, företag och hushåll även i Sverige.',source:'Reuters',href:'https://www.reuters.com/business/energy/oil-edges-up-uncertainty-over-exports-through-hormuz-2026-08-19/'},
  {section:'Sport · Norden',date:'23 augusti',title:'Nordiska fotbollsförbund tappar förtroendet för FIFA-ledningen',summary:'Sex nordiska fotbollsförbund, däribland Sveriges, säger gemensamt att de saknar förtroende för Gianni Infantino och kräver reformer av FIFA:s styrning.',why:'Konflikten handlar om makt, transparens och kommersiellt inflytande över världens största idrott.',source:'Reuters',href:'https://www.reuters.com/sports/soccer/nordic-nations-say-they-have-lost-confidence-infantino-fifa-governance-2026-08-23/'},
  {section:'Nacka · Skola',date:'21 augusti',title:'SAO-jobb ska ge högstadieelever riktig arbetslivserfarenhet',summary:'Nacka kommun har ingått en avsiktsförklaring med Nästa generation Sverige om en modell där högstadieelever får betalt arbete inom ramen för undervisningen.',why:'Modellen kan skapa tidigare kontakt mellan unga och arbetslivet och blir samtidigt en konkret lokal skolfråga inför valet.',source:'Nacka kommun',href:'https://www.nacka.se/'},
  {section:'Nacka · Val 2026',date:'21 augusti',title:'Valaffischerna är uppe – kommunen förtydligar reglerna',summary:'Inför valet den 13 september har kommunen publicerat ett klargörande om vad som gäller för valaffischering runt om i Nacka.',why:'När förtidsröstningen närmar sig flyttar valrörelsen från program och debatter ut i det offentliga rummet.',source:'Nacka kommun',href:'https://www.nacka.se/nyheter-start/'},
  {section:'Nacka · Äldreomsorg',date:'17 augusti',title:'Nackabor kan nominera till årets Ess-utmärkelse',summary:'Till den 7 september kan kunder, anhöriga och medarbetare nominera personer och team som gjort särskild skillnad för äldre i kommunen.',why:'Utmärkelsen ger en konkret ingång till kvalitet, bemötande och arbetsvillkor i äldreomsorgen.',source:'Nacka kommun',href:'https://www.nacka.se/nyheter-start/'},
  {section:'Nacka · Fritid',date:'17 augusti',title:'Nackas Fritidsbibliotek har öppnat',summary:'Nackabor kan nu kostnadsfritt låna bland annat skateboards, sovsäckar, simutrustning och bollar vid Nacka sportcentrum.',why:'Gratis utlåning sänker tröskeln till fritidsaktiviteter och kan göra idrott och friluftsliv tillgängligt för fler.',source:'Nacka kommun',href:'https://www.nacka.se/nyheter-start/'},
  {section:'Nacka · Trafik',date:'14 augusti',title:'Nya pendelbåtsbryggan i Nacka strand är i trafik',summary:'SL och skärgårdstrafiken började använda den nya bryggan den 17 augusti.',why:'Bättre sjötrafik ger fler alternativ till bil och buss när Nacka växer och stora trafikprojekt pågår.',source:'Nacka kommun',href:'https://www.nacka.se/nyheter-start/'}
] as const;
