export type EuCountry = {
  code: string; flag: string; name: string; capital: string; capitalPopulation: string;
  area: string; population: string; headOfState: string; headOfGovernment: string;
  nextElection: string; gdpPerCapita: string; industries: string[];
};

export const euCountries: EuCountry[] = [
 {code:'AT',flag:'🇦🇹',name:'Österrike',capital:'Wien',capitalPopulation:'cirka 2,0 miljoner',area:'83 879',population:'9,2 miljoner',headOfState:'President Alexander Van der Bellen',headOfGovernment:'Förbundskansler Christian Stocker',nextElection:'Parlamentsval senast 2029',gdpPerCapita:'cirka 59 000 USD',industries:['maskiner','fordon','turism','kemi','livsmedel']},
 {code:'BE',flag:'🇧🇪',name:'Belgien',capital:'Bryssel',capitalPopulation:'cirka 1,25 miljoner i regionen',area:'30 689',population:'11,9 miljoner',headOfState:'Kung Philippe, ingen president',headOfGovernment:'Premiärminister Bart De Wever',nextElection:'Federalt val 2029',gdpPerCapita:'cirka 57 000 USD',industries:['kemi och läkemedel','livsmedel','metall','logistik','finans']},
 {code:'BG',flag:'🇧🇬',name:'Bulgarien',capital:'Sofia',capitalPopulation:'cirka 1,28 miljoner',area:'110 994',population:'6,4 miljoner',headOfState:'President Iliana Iotova',headOfGovernment:'Premiärminister Rumen Radev',nextElection:'Nästa parlamentsval enligt ny mandatperiod',gdpPerCapita:'cirka 18 000 USD',industries:['IT och outsourcing','maskiner','metall','livsmedel','turism']},
 {code:'HR',flag:'🇭🇷',name:'Kroatien',capital:'Zagreb',capitalPopulation:'cirka 770 000',area:'56 594',population:'3,9 miljoner',headOfState:'President Zoran Milanović',headOfGovernment:'Premiärminister Andrej Plenković',nextElection:'Parlamentsval senast 2028',gdpPerCapita:'cirka 24 000 USD',industries:['turism','livsmedel','varv','läkemedel','IT']},
 {code:'CY',flag:'🇨🇾',name:'Cypern',capital:'Nicosia',capitalPopulation:'cirka 330 000 i tätorten',area:'9 251',population:'0,94 miljoner',headOfState:'President Nikos Christodoulides',headOfGovernment:'Presidenten är även regeringschef, ingen premiärminister',nextElection:'Presidentval 2028',gdpPerCapita:'cirka 39 000 USD',industries:['turism','sjöfart','finans','fastigheter','IT-tjänster']},
 {code:'CZ',flag:'🇨🇿',name:'Tjeckien',capital:'Prag',capitalPopulation:'cirka 1,40 miljoner',area:'78 871',population:'10,9 miljoner',headOfState:'President Petr Pavel',headOfGovernment:'Premiärminister Andrej Babiš',nextElection:'Parlamentsval senast 2029',gdpPerCapita:'cirka 32 000 USD',industries:['fordon','maskiner','elektronik','metall','öl och livsmedel']},
 {code:'DK',flag:'🇩🇰',name:'Danmark',capital:'Köpenhamn',capitalPopulation:'cirka 670 000 i kommunen',area:'42 952',population:'6,0 miljoner',headOfState:'Kung Frederik X, ingen president',headOfGovernment:'Statsminister Mette Frederiksen',nextElection:'Folketingsval senast 2026',gdpPerCapita:'cirka 72 000 USD',industries:['läkemedel','sjöfart','livsmedel','vindkraft','design och teknik']},
 {code:'EE',flag:'🇪🇪',name:'Estland',capital:'Tallinn',capitalPopulation:'cirka 462 000',area:'45 335',population:'1,37 miljoner',headOfState:'President Alar Karis',headOfGovernment:'Premiärminister Kristen Michal',nextElection:'Parlamentsval 2027',gdpPerCapita:'cirka 31 000 USD',industries:['IT','elektronik','trävaror','telekom','logistik']},
 {code:'FI',flag:'🇫🇮',name:'Finland',capital:'Helsingfors',capitalPopulation:'cirka 685 000',area:'338 455',population:'5,64 miljoner',headOfState:'President Alexander Stubb',headOfGovernment:'Statsminister Petteri Orpo',nextElection:'Riksdagsval 2027',gdpPerCapita:'cirka 53 000 USD',industries:['skog och papper','maskiner','elektronik','kemi','spel och mjukvara']},
 {code:'FR',flag:'🇫🇷',name:'Frankrike',capital:'Paris',capitalPopulation:'cirka 2,1 miljoner i kommunen',area:'551 695',population:'68,6 miljoner',headOfState:'President Emmanuel Macron',headOfGovernment:'Premiärminister Sébastien Lecornu',nextElection:'Presidentval 2027',gdpPerCapita:'cirka 46 000 USD',industries:['flyg och försvar','fordon','lyxvaror','turism','energi och jordbruk']},
 {code:'DE',flag:'🇩🇪',name:'Tyskland',capital:'Berlin',capitalPopulation:'cirka 3,9 miljoner',area:'357 588',population:'83,6 miljoner',headOfState:'President Frank-Walter Steinmeier',headOfGovernment:'Förbundskansler Friedrich Merz',nextElection:'Förbundsdagsval senast 2029',gdpPerCapita:'cirka 56 000 USD',industries:['fordon','maskiner','kemi','elektronik','läkemedel']},
 {code:'GR',flag:'🇬🇷',name:'Grekland',capital:'Aten',capitalPopulation:'cirka 640 000 i kommunen',area:'131 957',population:'10,4 miljoner',headOfState:'President Konstantinos Tasoulas',headOfGovernment:'Premiärminister Kyriakos Mitsotakis',nextElection:'Parlamentsval senast 2027',gdpPerCapita:'cirka 25 000 USD',industries:['turism','sjöfart','livsmedel','energi','metall']},
 {code:'HU',flag:'🇭🇺',name:'Ungern',capital:'Budapest',capitalPopulation:'cirka 1,69 miljoner',area:'93 030',population:'9,6 miljoner',headOfState:'President Tamás Sulyok',headOfGovernment:'Premiärminister Péter Magyar',nextElection:'Parlamentsval senast 2030',gdpPerCapita:'cirka 23 000 USD',industries:['fordon','elektronik','läkemedel','livsmedel','batterier']},
 {code:'IE',flag:'🇮🇪',name:'Irland',capital:'Dublin',capitalPopulation:'cirka 630 000 i kommunen',area:'70 273',population:'5,5 miljoner',headOfState:'President Catherine Connolly',headOfGovernment:'Taoiseach Micheál Martin',nextElection:'Parlamentsval senast 2029',gdpPerCapita:'cirka 112 000 USD, påverkas starkt av multinationella bolag',industries:['läkemedel','medicinteknik','IT','finans','livsmedel']},
 {code:'IT',flag:'🇮🇹',name:'Italien',capital:'Rom',capitalPopulation:'cirka 2,75 miljoner',area:'302 073',population:'58,9 miljoner',headOfState:'President Sergio Mattarella',headOfGovernment:'Premiärminister Giorgia Meloni',nextElection:'Parlamentsval senast 2027',gdpPerCapita:'cirka 40 000 USD',industries:['maskiner','fordon','mode','livsmedel','turism']},
 {code:'LV',flag:'🇱🇻',name:'Lettland',capital:'Riga',capitalPopulation:'cirka 605 000',area:'64 589',population:'1,85 miljoner',headOfState:'President Edgars Rinkēvičs',headOfGovernment:'Premiärminister Andris Kulbergs',nextElection:'Parlamentsval 2026',gdpPerCapita:'cirka 23 000 USD',industries:['trävaror','livsmedel','transport','IT','maskiner']},
 {code:'LT',flag:'🇱🇹',name:'Litauen',capital:'Vilnius',capitalPopulation:'cirka 610 000',area:'65 300',population:'2,89 miljoner',headOfState:'President Gitanas Nausėda',headOfGovernment:'Premiärminister Inga Ruginienė',nextElection:'Parlamentsval 2028',gdpPerCapita:'cirka 29 000 USD',industries:['tillverkning','laser och teknik','livsmedel','möbler','fintech']},
 {code:'LU',flag:'🇱🇺',name:'Luxemburg',capital:'Luxemburg',capitalPopulation:'cirka 136 000',area:'2 586',population:'0,68 miljoner',headOfState:'Storhertig Guillaume, ingen president',headOfGovernment:'Premiärminister Luc Frieden',nextElection:'Parlamentsval 2028',gdpPerCapita:'cirka 138 000 USD',industries:['finans','fondförvaltning','stål','satelliter','logistik']},
 {code:'MT',flag:'🇲🇹',name:'Malta',capital:'Valletta',capitalPopulation:'cirka 6 000',area:'316',population:'0,57 miljoner',headOfState:'President Myriam Spiteri Debono',headOfGovernment:'Premiärminister Robert Abela',nextElection:'Parlamentsval senast 2027',gdpPerCapita:'cirka 42 000 USD',industries:['turism','finans','spel','elektronik','läkemedel']},
 {code:'NL',flag:'🇳🇱',name:'Nederländerna',capital:'Amsterdam',capitalPopulation:'cirka 940 000',area:'41 865',population:'18,1 miljoner',headOfState:'Kung Willem-Alexander, ingen president',headOfGovernment:'Premiärminister Rob Jetten',nextElection:'Nästa parlamentsval enligt mandatperioden',gdpPerCapita:'cirka 68 000 USD',industries:['handel och logistik','jordbruksteknik','kemi','elektronik','finans']},
 {code:'PL',flag:'🇵🇱',name:'Polen',capital:'Warszawa',capitalPopulation:'cirka 1,86 miljoner',area:'312 696',population:'36,5 miljoner',headOfState:'President Karol Nawrocki',headOfGovernment:'Premiärminister Donald Tusk',nextElection:'Parlamentsval 2027',gdpPerCapita:'cirka 25 000 USD',industries:['maskiner','fordon','livsmedel','IT','möbler']},
 {code:'PT',flag:'🇵🇹',name:'Portugal',capital:'Lissabon',capitalPopulation:'cirka 575 000 i kommunen',area:'92 226',population:'10,7 miljoner',headOfState:'President António José Seguro',headOfGovernment:'Premiärminister Luís Montenegro',nextElection:'Parlamentsval senast 2029',gdpPerCapita:'cirka 29 000 USD',industries:['turism','textil','fordonsdelar','kork och papper','tekniktjänster']},
 {code:'RO',flag:'🇷🇴',name:'Rumänien',capital:'Bukarest',capitalPopulation:'cirka 1,72 miljoner',area:'238 397',population:'19,0 miljoner',headOfState:'President Nicușor Dan',headOfGovernment:'Premiärminister Ilie Bolojan',nextElection:'Parlamentsval 2028',gdpPerCapita:'cirka 20 000 USD',industries:['fordon','IT','maskiner','energi','jordbruk']},
 {code:'SK',flag:'🇸🇰',name:'Slovakien',capital:'Bratislava',capitalPopulation:'cirka 480 000',area:'49 035',population:'5,42 miljoner',headOfState:'President Peter Pellegrini',headOfGovernment:'Premiärminister Robert Fico',nextElection:'Parlamentsval 2027',gdpPerCapita:'cirka 26 000 USD',industries:['fordon','elektronik','maskiner','metall','kemi']},
 {code:'SI',flag:'🇸🇮',name:'Slovenien',capital:'Ljubljana',capitalPopulation:'cirka 300 000',area:'20 273',population:'2,13 miljoner',headOfState:'President Nataša Pirc Musar',headOfGovernment:'Premiärminister Janez Janša',nextElection:'Parlamentsval senast 2030',gdpPerCapita:'cirka 34 000 USD',industries:['fordonsdelar','läkemedel','maskiner','elektronik','turism']},
 {code:'ES',flag:'🇪🇸',name:'Spanien',capital:'Madrid',capitalPopulation:'cirka 3,42 miljoner',area:'505 990',population:'49,1 miljoner',headOfState:'Kung Felipe VI, ingen president',headOfGovernment:'Premiärminister Pedro Sánchez',nextElection:'Parlamentsval senast 2027',gdpPerCapita:'cirka 35 000 USD',industries:['turism','fordon','livsmedel','förnybar energi','kemi']},
 {code:'SE',flag:'🇸🇪',name:'Sverige',capital:'Stockholm',capitalPopulation:'cirka 1,0 miljon i kommunen',area:'447 425',population:'10,6 miljoner',headOfState:'Kung Carl XVI Gustaf, ingen president',headOfGovernment:'Statsminister Ulf Kristersson',nextElection:'Riksdagsval 13 september 2026',gdpPerCapita:'cirka 57 000 USD',industries:['fordon','telekom','maskiner','läkemedel','skog och gruvor']}
];
