export const frontPageLongReads:Record<string,{heading:string;paragraphs:string[]}[]>={
 'iran-kriget-dyrt-dodlage':[
  {heading:'Hur ett dödläge förändrar maktbalansen',paragraphs:['Ett utdraget krig gynnar inte automatiskt den militärt starkaste parten. Avgörande blir i stället vem som kan ersätta materiel, finansiera staten och behålla tillräckligt stöd från befolkningen och sina internationella partners. Iran kan tåla stora ekonomiska kostnader om ledningen behåller kontrollen över säkerhetsapparaten, men priset blir ett samhälle där allt fler resurser går till överlevnad och allt färre till utveckling.','Motståndarsidan måste samtidigt väga fortsatt press mot risken för regional spridning. Hårdare angrepp kan försvaga iransk kapacitet, men också utlösa attacker mot sjöfart, energianläggningar eller allierade i regionen. Det gör varje militärt beslut till en ekonomisk kalkyl för betydligt fler länder än de direkt krigförande.']},
  {heading:'Tre möjliga vägar framåt',paragraphs:['Det första scenariot är ett fortsatt lågintensivt dödläge där blockad, sporadiska angrepp och indirekta förhandlingar pågår parallellt. Det andra är en begränsad uppgörelse om sjöfart eller vapenvila utan att grundkonflikten löses. Det tredje är en ny eskalering efter en incident som någon part uppfattar som omöjlig att lämna obesvarad.','Det mest realistiska diplomatiska arbetet börjar därför med mindre överenskommelser. En fungerande incidentmekanism kring Hormuz, humanitära undantag och verifierbara begränsningar av vissa attacker kan minska risken även om parternas politiska mål förblir oförenliga.']},
  {heading:'Vad det betyder för Sverige',paragraphs:['Sverige påverkas genom energipriser, industrins transportkostnader och hushållens inflation. En varaktig riskpremie på olja och frakt kan bromsa den ekonomiska återhämtningen även om Sverige inte köper stora mängder energi direkt från regionen.','Konflikten pressar också Europas politiska prioriteringar. När mer uppmärksamhet och pengar går till Mellanöstern blir det svårare att samtidigt finansiera Ukraina, försvar, klimatomställning och ekonomiska reformer.']}
 ],
 'vatikanen-moskva-fredsvag':[
  {heading:'Vad Vatikanen faktiskt kan påverka',paragraphs:['Vatikanens diplomati arbetar ofta utan stora offentliga utspel. Dess nätverk kan förmedla kontakter, samla information och pröva formuleringar som parterna ännu inte vill äga offentligt. Den rollen är särskilt användbar i frågor om fångar, bortförda barn, civila och religiösa institutioner.','Begränsningen är att Vatikanen varken kan erbjuda säkerhetsgarantier eller tvinga fram eftergifter. Ett samtal kan därför vara viktigt utan att förändra fronten. Värdet ligger i att en kanal finns kvar den dag då de politiska och militära kostnaderna gör en uppgörelse mer attraktiv.']},
  {heading:'Den svåra balansen mellan neutralitet och tydlighet',paragraphs:['För att medla behöver Vatikanen kunna tala med Moskva, men varje tecken på moralisk likställning mellan angripare och försvarare kan skada förtroendet i Ukraina. Samtidigt kan en alltför konfrontativ linje stänga tillträdet till de personer man försöker påverka.','Det gör språket centralt. Humanitära frågor kan ibland behandlas separat från territoriella och säkerhetspolitiska krav, men de får inte användas för att ge sken av en fredsprocess som saknar verkligt innehåll.']},
  {heading:'Vad Europa bör läsa in i besöket',paragraphs:['Europa bör se besöket som ett komplement, inte en ersättning, till den egna politiken. Militärt stöd, sanktioner och diplomatiska kanaler fyller olika funktioner och måste bedömas var för sig.','Om små humanitära avtal kan genomföras och kontrolleras skapas praktisk erfarenhet av kontakt. Det kan senare bli byggstenar i en bredare process, men endast om Ukraina själv har en central roll.']}
 ],
 'regional-diplomati-irankriget':[
  {heading:'Varför grannländerna har mer att förlora',paragraphs:['Gulfstaternas ekonomiska modeller bygger på förutsägbara transporter, internationella investeringar och fungerande flyg- och hamntrafik. Ett längre krig hotar därför inte bara oljeexporten utan också ambitionen att utveckla handel, turism, finans och teknik.','Pakistan påverkas genom säkerhet, energi och inrikespolitisk stabilitet. Landets relationer i flera riktningar kan ge diplomatiskt tillträde, men gör också varje ställningstagande känsligt.']},
  {heading:'Så kan en begränsad överenskommelse se ut',paragraphs:['Ett första avtal behöver inte lösa kärnfrågorna. Det kan handla om säkerhetszoner för handelssjöfart, gemensamma kontaktpunkter vid incidenter och tydliga besked om vilka typer av mål som ska undantas.','För att fungera krävs verifiering. Om parterna inte litar på varandras uppgifter måste en tredje part kunna kontrollera händelser och snabbt kommunicera vad som faktiskt har inträffat.']},
  {heading:'Konsekvenser bortom regionen',paragraphs:['En nedtrappning skulle kunna sänka försäkrings- och fraktkostnader innan energiflödena är helt normaliserade. Marknader reagerar på risk, och trovärdiga samtal kan därför få ekonomisk effekt tidigt.','Ett misslyckande skulle få motsatt verkan. Företag kan permanent välja längre handelsvägar och bygga om leveranskedjor, vilket gör kostnadsökningen mer långvarig än själva striderna.']}
 ],
 'gaza-vapenvila-under-press':[
  {heading:'Skillnaden mellan vapenvila och verklig säkerhet',paragraphs:['En vapenvila mäts ofta i antalet attacker, men för civila handlar säkerhet också om möjligheten att få vård, hitta bostad, röra sig och försörja familjen. Om vardagen inte förbättras förlorar avtalet gradvis legitimitet.','Samtidigt behöver incidenter kunna hanteras utan automatisk upptrappning. En mekanism för snabb faktainsamling och kontakt mellan parterna kan vara lika viktig som själva avtalet när uppgifter och ansvar bestrids.']},
  {heading:'Återuppbyggnaden är också en maktfråga',paragraphs:['Pengar och byggmaterial ger inflytande. Den aktör som kontrollerar tillstånd, leveranser och lokala kontrakt kan forma både ekonomin och den framtida politiska ordningen. Därför blir återuppbyggnaden en del av konflikten, inte bara följden av den.','Givarländer vill undvika att resurser används militärt eller försvinner genom korruption. För hårda kontrollsystem kan dock göra återuppbyggnaden så långsam att misstron och desperationen växer.']},
  {heading:'Vad en hållbar process kräver',paragraphs:['En hållbar process behöver förena humanitärt tillträde, säkerhetsarrangemang och en politisk horisont. Om någon av delarna saknas blir de andra svårare att upprätthålla.','Omvärlden måste dessutom redovisa vilka brott mot avtalet som har verifierats och vilka som fortfarande är påståenden. Tydlighet kring fakta minskar utrymmet för propaganda och förhastade beslut.']}
 ],
 'rysk-mobilisering-ukraina':[
  {heading:'Från rekrytering till stridsvärde',paragraphs:['En mobiliseringsorder skapar inte omedelbart ett fungerande förband. Soldater behöver befäl, utbildning, samband, skydd, sjukvård, transporter och ammunition. Flaskhalsen kan därför ligga i organisationen snarare än i antalet personer.','Ryssland kan ändå använda numerär för att hålla en längre front, rotera vissa förband och tvinga Ukraina att sprida sina resurser. Även enheter med begränsad kvalitet kan få strategisk betydelse om de frigör mer erfarna soldater till prioriterade avsnitt.']},
  {heading:'Ukrainas svåra personalekvation',paragraphs:['Ukraina måste försvara landet utan att tömma ekonomin på arbetskraft. Varje ny mobilisering påverkar företag, skatteintäkter och familjer samtidigt som slitna soldater behöver vila och ersättas.','Det gör rättvisa och tydliga regler avgörande. Om bördorna uppfattas som ojämnt fördelade kan rekryteringen försvåras och förtroendet för staten minska.']},
  {heading:'Vad Europa kan och inte kan ersätta',paragraphs:['Europeiska länder kan bidra med utbildning, ammunition, luftförsvar och finansiering men inte ersätta Ukrainas egen personal. Stödet kan däremot öka varje soldats effekt och minska förlusterna.','Långsiktiga leveransavtal är viktigare än korta besked. En förutsägbar plan gör det möjligt för Ukraina att dimensionera förband och för europeisk industri att investera i produktion.']}
 ],
 'eu-budgetens-maktkamp':[
  {heading:'Var pengarna kan tas ifrån',paragraphs:['Om den totala ramen ska minska samtidigt som försvar och konkurrenskraft prioriteras måste etablerade utgifter pressas tillbaka. Jordbruksstöd och regionalpolitik är de största och mest politiskt skyddade områdena, vilket gör konflikten konkret i varje medlemsland.','Besparingar kan också ske genom hårdare villkor, mer nationell medfinansiering eller genom att program slås samman. Varje modell flyttar kostnader och makt på olika sätt.']},
  {heading:'Gemensam skuld förändrar unionen',paragraphs:['Gemensam upplåning ger EU möjlighet att agera snabbt och i stor skala, men skapar långvariga gemensamma betalningsåtaganden. Det är därför både ett finansieringsinstrument och ett steg mot djupare politisk integration.','Sveriges motstånd bygger på risken att tillfälliga krislösningar blir permanenta. Förespråkarna menar i stället att gemensamma säkerhetsproblem kräver gemensam finansiering och att splittrade nationella satsningar blir dyrare.']},
  {heading:'Den svenska kalkylen',paragraphs:['Sverige bör inte bara räkna nettobetalningen. Forskningsmedel, industriprojekt, regional utveckling och ett starkare europeiskt försvar kan ge värden som inte syns i den årliga avgiften.','Samtidigt behövs tydlig kontroll av resultat. En större budget utan uppföljning riskerar att försvaga förtroendet, medan en alltför liten ram kan lämna EU med stora löften men otillräcklig kapacitet.']}
 ]
};
