export const internationalFeatures=[
{slug:'australien-eu-ny-allians',section:'Europa · Australien',title:'Australien söker en närmare allians med EU',intro:'USA:s handelskonflikter och en mer osäker säkerhetspolitik får Australien att undersöka ett djupare samarbete med Europa.',published:'26 september 2026',body:[
{heading:'Relationerna håller på att ritas om',paragraphs:['Australien diskuterar en närmare och mer självständig relation med Europeiska unionen. Bakgrunden är att landets traditionella beroende av USA blivit mer riskfyllt när Washington kombinerar handelspolitiska konflikter med en mindre förutsägbar försvarslinje.','Samtidigt är Kina Australiens viktigaste handelspartner. Canberra behöver därför stärka sina alternativ utan att bryta vare sig säkerhetssamarbetet med USA eller de ekonomiska banden till Kina. EU framstår som en möjlig tredje pelare.']},
{heading:'Ett samarbete med tydliga gränser',paragraphs:['Ett närmande kan omfatta handel, kritiska mineraler, försvarsteknik, forskning och gemensamma regler. Kanada har blivit en förebild för hur ett land utanför Europa kan knytas närmare unionen utan medlemskap.','Men avståndet är stort och EU är ingen fullständig ersättare för USA:s militära kapacitet. Det mest realistiska är därför en bredare portfölj av partnerskap som minskar Australiens sårbarhet och samtidigt ger Europa bättre tillgång till råvaror och inflytande i Indo-Pacific.']}],
sources:[{label:'Deutsche Welle om Australiens möjliga EU-allians',url:'https://www.dw.com/en/australia-considers-its-own-unique-alliance-with-the-eu/video-79420024'}]},
{slug:'aten-explosion-utredning',section:'Europa · Grekland',title:'Aten söker svar efter den dödliga explosionen',intro:'Minst sex människor har dött efter en explosion i ett flerfamiljshus. Nu riktas uppmärksamheten mot orsaken, byggnadssäkerheten och stödet till de drabbade.',published:'26 september 2026',body:[
{heading:'Räddningsarbetet övergår i utredning',paragraphs:['Grekiska myndigheter utreder den kraftiga explosion som förstörde delar av ett flerfamiljshus i Aten. Minst sex människor har dött och räddningspersonal har sökt genom rasmassorna efter fler drabbade.','I det första skedet har flera möjliga orsaker diskuterats. Myndigheterna behöver nu säkra teknisk bevisning innan de kan slå fast om explosionen berodde på gas, ett tekniskt fel eller något annat.']},
{heading:'Säkerhetsfrågan blir större än ett hus',paragraphs:['När den akuta insatsen är avslutad väntar frågor om tillsyn, underhåll och hur äldre bostadshus skyddas mot gasläckor och bränder. En olycka av den här storleken kan leda till skärpta kontroller långt utanför den drabbade fastigheten.','Det är samtidigt viktigt att skilja bekräftade fakta från tidiga spekulationer. För de boende handlar den närmaste tiden om vård, tillfälliga bostäder och besked om när området kan bli säkert igen.']}],
sources:[{label:'The Guardian om explosionen i Aten',url:'https://www.theguardian.com/world/2026/sep/26/greek-authorities-seek-answers-after-six-killed-in-athens-apartment-block-explosion'}]},
{slug:'ai-forandrar-advokatbyraerna',section:'USA · Ekonomi och AI',title:'AI pressar advokatbyråernas mest lönsamma affärsmodell',intro:'När juridiskt arbete går snabbare ifrågasätter kunderna debitering per timme. Värdet flyttas från nedlagd tid till resultat, omdöme och ansvar.',published:'26 september 2026',body:[
{heading:'Den debiterade timmen utmanas',paragraphs:['Generativ AI kan söka i stora dokumentmängder, sammanfatta avtal och skapa första utkast på en bråkdel av den tid som tidigare krävdes. För advokatbyråer skapar det ett problem: effektiviteten ökar samtidigt som intäkterna ofta bygger på antalet arbetade timmar.','Företagskunder kräver därför rabatter, fasta priser och tydligare bevis för vilket värde byrån faktiskt tillför. Tekniken kan pressa priset på rutinuppgifter men göra erfarna juristers bedömningar och ansvar ännu viktigare.']},
{heading:'En ny fördelning av värde och risk',paragraphs:['Om betalningen i högre grad knyts till resultat behöver byråerna förstå sina kostnader och risker bättre. Den som använder AI effektivt kan få högre marginal, men bara om kvalitet, sekretess och kontroll fungerar.','Förändringen kan också påverka utbildningen av nya jurister. Juniora medarbetare har traditionellt lärt sig genom dokumentgranskning och research. När maskiner tar en större del av det arbetet måste byråerna skapa nya vägar till praktisk erfarenhet.']}],
sources:[{label:'New York Times om AI och advokatbyråernas prissättning',url:'https://www.nytimes.com/2026/09/26/business/dealbook/ai-law-discount-billable-hour.html'}]}
];
