export const internationalFeatures=[
{slug:'jemen-ny-front-varldshandel',section:'Mellanöstern',title:'Jemen blir en ny front – världshandeln hamnar åter i skottlinjen',intro:'De hårdaste striderna på flera år hotar civila och sjöfarten genom Bab al-Mandab.',published:'10 september 2026',body:[
{heading:'Striderna har återvänt',paragraphs:['Omkring 1 000 människor har dödats eller skadats och tiotusentals har tvingats lämna sina hem när striderna i Jemen åter blossat upp. Huthirörelsen har angripit Saudiarabien med robotar och drönare. Saudiarabien har svarat med omfattande flyganfall. Det är den allvarligaste upptrappningen sedan den FN-stödda vapenvilan 2022.','Den omedelbara utlösaren är den större Iran-konflikten, men kriget har djupare rötter. Huthierna och den internationellt erkända regeringen har kämpat om makten sedan 2014. Regionala aktörer har gjort landet till en arena för egna säkerhetsintressen.']},
{heading:'Sundet påverkar hela världen',paragraphs:['Bab al-Mandab binder samman Röda havet och Indiska oceanen. Omkring en tiondel av världens sjöhandel passerar sundet. När fartyg hotas väljer rederier den längre vägen runt Afrika. Det höjer kostnader, försenar leveranser och ökar bränsleförbrukningen.','Jemen var redan en av världens svåraste humanitära kriser. Nya strider gör hjälpleveranser farligare just när behoven växer. Utan en fristående fredsprocess riskerar civila att åter få bära den största kostnaden.']}],
sources:[{label:'The Guardian om upptrappningen i Jemen',url:'https://www.theguardian.com/world/2026/sep/10/violence-erupts-in-yemen-again-why-it-matters-globally-and-how-it-is-linked-to-the-us-iran-war'},{label:'FN:s humanitära samordning för Jemen',url:'https://www.unocha.org/yemen'},{label:'Al Jazeeras Jemenbevakning',url:'https://www.aljazeera.com/tag/yemen/'}]},
{slug:'extremvarme-ekonomisk-sakerhetsfraga',section:'Klimat',title:'Extremvärmen förändrar Europas ekonomi',intro:'Skördar, elproduktion, transporter och arbetsmiljö påverkas samtidigt efter ännu en rekordvarm sommar.',published:'10 september 2026',body:[
{heading:'Värmen flyttar in i ekonomin',paragraphs:['Augusti 2026 hör till de varmaste månader som har registrerats globalt. I Europa har värme, bränder och översvämningar orsakat dödsfall, evakueringar och stora skador. FN:s klimatchef Simon Stiell uppskattar sommarens europeiska ekonomiska kostnad till omkring 180 miljarder euro.','Kostnaden omfattar mer än förstörda byggnader. Företag tappar arbetstid, elnät belastas, kylning blir dyrare och transporter stoppas. När floder blir för grunda påverkas industrins frakter och energisystemets sårbarhet växer.']},
{heading:'Maten visar sambandet',paragraphs:['Extremvärmen påverkar skördar långt innan förändringen syns i butiken. Mindre produktion av spannmål, frukt och vindruvor kan höja priserna och öka beroendet av import. Flera producentländer kan drabbas samtidigt.','Klimatanpassning blir därför en fråga om lager, bevattning, grödval och handel. Den kan minska skadan men inte ersätta utsläppsminskningar. Klimatpolitik och ekonomisk säkerhet har blivit samma diskussion.']}],
sources:[{label:'The Guardian om klimatets ekonomiska följder',url:'https://www.theguardian.com/environment/2026/sep/10/august-joint-hottest-month-recorded-globally'},{label:'Copernicus Climate Change Service',url:'https://climate.copernicus.eu/'},{label:'FN:s klimatkonvention',url:'https://unfccc.int/'}]},
{slug:'ai-risk-fran-spekulation-till-politik',section:'Teknik',title:'AI-varningen flyttar in i politikens mötesrum',intro:'Experter varnar för framtida system som blir svåra att kontrollera, medan andra vill prioritera dagens konkreta skador.',published:'10 september 2026',body:[
{heading:'En risk som är svår att mäta',paragraphs:['Debatten om artificiell superintelligens har skärpts efter varningar från forskare, tidigare ministrar och personer inom AI-företag. De beskriver en risk att framtida system blir bättre än människor på nästan alla kognitiva uppgifter och kan agera på sätt som utvecklarna inte kan stoppa.','Sannolikheterna är omstridda. Det viktiga politiska faktumet är ändå att människor nära utvecklingen anser att följderna kan bli extrema. Riskens storlek måste bedömas tillsammans med osäkerheten.']},
{heading:'Dagens skador är redan synliga',paragraphs:['Kritiker pekar på diskriminerande beslut, desinformation, övervakning och koncentration av makt till ett fåtal företag. Motsättningen behöver inte vara total. Oberoende tester, dokumentation, incidentrapportering och tydligt ansvar hjälper mot både dagens och framtidens risker.','Företag har starka incitament att lansera först. Därför räcker frivilliga löften dåligt när kostnaden för försiktighet bärs av företaget men en möjlig skada delas av samhället. Internationella minimikrav kan minska risken utan att stoppa användbar utveckling.']}],
sources:[{label:'The Guardian om varningarna för superintelligens',url:'https://www.theguardian.com/technology/2026/sep/09/ai-superintelligence-risks-warnings-scientists-politicians'},{label:'FN:s Global Digital Compact',url:'https://www.un.org/global-digital-compact/en'},{label:'EU-kommissionen om AI Act',url:'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai'}]}
];
