import type { Article } from './articles';

const iranGulf160: Article = {
  slug: 'usa-iran-gulfstaterna', section: 'Världen · Mellanöstern', title: 'USA och Iran utbyter nya attacker – Gulfstaterna dras närmare konflikten',
  intro: 'USA och Iran har åter angripit varandras intressen. Attackerna berör nu också Jordanien och Förenade arabemiraten, samtidigt som sjöfarten genom Hormuzsundet och en ny amerikansk sanktionskampanj höjer den ekonomiska insatsen.',
  author: 'NackaSidans redaktion', published: '31 augusti 2026', updated: '31 augusti 2026 kl. 12.15', publishedAt: '2026-08-31T12:15:00+02:00', updatedAt: '2026-08-31T12:15:00+02:00', status: 'published', readingTime: '12 min',
  body: [
    { heading: 'Nya attacker efter en månads militär paus', paragraphs: ['USA och Iran har åter utbytt eld efter ungefär en månad utan motsvarande direkta angrepp. Enligt Reuters angrep amerikanska styrkor två iranska raketramper på Larakön i Hormuzsundet. USA uppgav att ramperna utgjorde ett omedelbart hot mot fartygstrafiken i den strategiska vattenvägen.', 'Iran svarade med ballistiska robotar mot två amerikanska baser i Jordanien, enligt iranska medier. Merparten av robotarna uppges ha skjutits ned. Händelseförloppet visar ändå hur snabbt ett begränsat angrepp kan följas av vedergällning på ett annat lands territorium och därmed vidga konfliktens geografiska område.', 'Uppgifterna om skador och förluster var fortfarande ofullständiga. Det är därför viktigt att skilja bekräftade omständigheter från parternas egna militära påståenden. I ett pågående krig kan både skadebilder och beskrivningar av avsikten bakom ett angrepp ändras när oberoende uppgifter blir tillgängliga.'] },
    { heading: 'Förenade arabemiraten hamnar närmare frontlinjen', paragraphs: ['Förenade arabemiraten uppgav att luftförsvaret hade stoppat en iransk drönare över emiratiskt territorialvatten. Iran hävdade att drönare hade angripit flygbasen Al Minhad, men Förenade arabemiraten förnekade att basen träffats. Den skillnaden är central: en bekräftad attack mot basen skulle vara ett tydligare steg in i konflikten än en avvärjd drönare.', 'Gulfstaterna har länge försökt kombinera säkerhetssamarbete med USA med fungerande relationer till Iran. De vill undvika att deras territorium används som avstamp för en regional upptrappning, men amerikanska baser, luftförsvar och logistiska nav gör dem samtidigt till en del av den militära infrastrukturen. När projektiler når deras luftrum blir avståndet mellan diplomatisk balansgång och direkt inblandning mycket kort.'] },
    { heading: 'Khargön: dramatiskt påstående utan verifiering', paragraphs: ['USA:s president Donald Trump publicerade ett AI-genererat videoklipp och skrev att Khargön, navet för en mycket stor del av Irans oljeexport, höll på att förstöras. Reuters hade vid publiceringen inte funnit belägg för att en sådan attack ägt rum. Varken Vita huset eller Pentagon hade bekräftat den. Materialet ska därför inte behandlas som dokumentation av en verklig händelse.', 'Ett verkligt angrepp mot Kharg skulle kunna få stora följder för Irans exportkapacitet och världsmarknaden för olja. Men även ett obelagt påstående kan påverka förväntningar, riskpremier och militär beredskap innan det har hunnit kontrolleras.'] },
    { heading: 'Washington kombinerar militärt och ekonomiskt tryck', paragraphs: ['Parallellt med attackerna signalerar den amerikanska regeringen en hårdare ekonomisk kampanj. Finansminister Scott Bessent sade till Reuters att nya sekundära sanktioner sannolikt kommer att presenteras varje vecka, inledningsvis med fokus på banker och finansiella nätverk som möjliggör handel med Iran.', 'Sekundära sanktioner kan också drabba företag och banker i andra länder som fortsätter göra affärer med iranska aktörer. Strategin ska höja priset för Irans handel utan att enbart förlita sig på nya stora militära operationer, men kan samtidigt skapa konflikter med länder som inte accepterar Washingtons krav.'] },
    { heading: 'Hormuzsundet är konfliktens ekonomiska centrum', paragraphs: ['Sjöfarten genom Hormuzsundet har minskat kraftigt under hot om minor, attacker och beslag. En stor del av världens sjöburna handel med olja och flytande naturgas passerar normalt genom området. Redan risken för nya avbrott påverkar fraktpriser, försäkringskostnader och oljepris.', 'Det gör sundet till den punkt där regionala attacker kan översättas till högre kostnader långt från Mellanöstern. För Europa och Sverige kan följderna märkas som dyrare drivmedel, större inflationsrisk och svårare beslut för centralbanker och industriföretag.'] }
  ],
  knowledge: [{ label: 'Bekräftat', text: 'USA angrep raketramper på Larakön och Iran svarade mot amerikanska mål i Jordanien.' }, { label: 'Gulfstaterna', text: 'Förenade arabemiraten uppger att en iransk drönare stoppades men förnekar att Al Minhad-basen träffades.' }, { label: 'Obekräftat', text: 'Det fanns inga belägg för Trumps påstående om ett angrepp mot Khargön.' }, { label: 'Nästa steg', text: 'USA förbereder återkommande sekundära sanktioner, först mot banker.' }],
  facts: ['Larakön och Khargön är två skilda platser med olika strategisk betydelse.', 'Hormuzsundet är en central passage för internationell handel med olja och gas.', 'Sekundära sanktioner kan riktas mot aktörer i tredje land.', 'AI-genererat material är inte bevis för att en militär attack har inträffat.'],
  analysis: 'Den omedelbara risken ligger inte främst i att någon sida redan har beslutat om ett fullskaligt regionalt krig, utan i att deras sätt att signalera beslutsamhet gör kontrollen svårare. USA beskriver angreppet på Larakön som skydd för sjöfarten. Iran behöver visa att ett angrepp får ett svar. När vedergällningen riktas mot amerikanska mål i Jordanien och en drönare når emiratiskt område får Gulfstaterna bära en större del av risken trots att de vill undvika kriget. Jordanien och Förenade arabemiraten är beroende av amerikanska säkerhetsgarantier men behöver också förhindra att deras baser, hamnar och luftrum gör dem till självklara mål. Ju fler stater som måste aktivera luftförsvar, desto större blir risken för felbedömningar och krav på motåtgärder. Hormuz förstärker denna logik. Iran behöver inte stänga passagen helt för att skapa ekonomisk effekt; osäkerhet kan räcka för att fartyg ska avvakta och försäkringspremier stiga. En taktiskt begränsad attack kan därmed få strategiska följder genom energi och inflation. Washingtons sekundära sanktioner öppnar samtidigt en andra front. För att bli effektiva måste USA få banker, rederier, raffinaderier och handelspartner i andra länder att rätta sig efter dem. Det kan pressa Irans intäkter men också skapa friktion med Kina och andra stater. Kombinationen av militära angrepp och ekonomisk isolering kan öka förhandlingsviljan, men kan lika gärna stärka Teherans uppfattning att eftergifter inte ger säkerhet. Det AI-genererade klippet om Kharg visar slutligen att informationsmiljön själv är en säkerhetsrisk. Ett presidentuttalande om ett centralt oljenav kan flytta marknader och påverka motpartens beredskap även utan verifierade bilder. För Sverige är den direkta militära risken liten, men följderna kan bli dyrare energi, ny inflationspress, högre transportkostnader och ökad osäkerhet på finansmarknaderna. Konflikten måste därför följas på tre nivåer samtidigt: angrepp och svar, Gulfstaternas handlingsutrymme och världsekonomins känslighet för störningar i Hormuz.',
  consequences: ['Jordanien och Förenade arabemiraten kan tvingas stärka luftförsvar och diplomati.', 'Minskad trafik genom Hormuz kan höja olje-, frakt- och försäkringskostnader.', 'Sekundära sanktioner kan pressa Iran men också skärpa USA:s motsättningar med handelspartner.', 'AI-genererade påståenden kan skapa marknadsreaktioner innan fakta är fastställda.', 'Europa kan möta ny inflationspress om energipriserna förblir höga.'],
  sources: [{ label: 'Reuters: USA och Iran utbyter eld; Bessent signalerar fler sanktioner – originalartikeln', url: 'https://www.reuters.com/world/middle-east/us-iran-exchange-fire-flare-up-bessent-signals-more-sanctions-2026-08-31/', type: 'Redaktionell källa' }], tags: ['USA','Iran','Gulfstaterna','Hormuzsundet'], related: ['veckans-analys']
};

const ostlig159: Article = {
  slug: 'ostlig-forbindelse-nationell-plan-2026', section: 'Nacka · Trafik',
  title: 'Östlig förbindelse tillbaka i nationella planen – en miljard till planering av 34-miljardersprojektet',
  intro: 'Regeringen har tagit in Östlig förbindelse i den nationella planen och avsätter en miljard kronor för att starta planeringen. Den föreslagna vägtunneln mellan Nacka och Ropsten beräknas enligt Nacka kommun kosta omkring 34 miljarder kronor i 2023 års prisnivå.',
  author: 'NackaSidans redaktion', published: '13 augusti 2026', updated: '13 augusti 2026 kl. 09.50', publishedAt: '2026-08-13T09:50:00+02:00', updatedAt: '2026-08-13T09:50:00+02:00', status: 'published', homepage: { role: 'lead', order: 0 },
  teaserTitle: 'Östlig förbindelse tillbaka – staten avsätter en miljard', teaserSummary: 'Projektet ska knyta ihop Södra och Norra länken. Men från planeringspengar till färdig tunnel återstår stora beslut.', readingTime: '8 min',
  body: [
    { heading: 'Från avvecklat projekt till ny planering', paragraphs: ['Östlig förbindelse har haft en krokig historia. Trafikverket avvecklade tidigare projektet efter att det inte kom med i den nationella transportplanen. Nu har förutsättningarna ändrats.', 'Den 27 april 2026 meddelade regeringen att förbindelsen tas med i den nationella planen. En miljard kronor avsätts för att påbörja planeringen.'] },
    { heading: '34 miljarder – men ännu ingen färdig tunnel', paragraphs: ['Nacka kommun anger en beräknad totalkostnad på omkring 34 miljarder kronor i 2023 års prisnivå. Den miljard som nu avsatts är alltså planeringsmedel och ska inte tolkas som full finansiering av hela anläggningen.', 'Det är en avgörande skillnad. Innan byggstart krävs fortsatt planering, tekniska utredningar, miljöprövning, finansieringsbeslut och en genomförbar tidplan.'] },
    { heading: 'Ska sluta vägringen runt Stockholm', paragraphs: ['Grundidén är att knyta samman Södra länken vid Sickla med Norra länken i området kring Värtan och Ropsten. Därmed skulle en saknad länk i ringleden runt Stockholm fyllas.', 'För Nacka och Värmdö är argumentet framför allt förbättrad framkomlighet och ett mindre sårbart trafiksystem. Kommunen lyfter även näringsliv, arbetsmarknad och totalförsvar som motiv.'] },
    { heading: 'Avsiktsförklaringen kom redan 2025', paragraphs: ['I oktober 2025 skrev staten, Nacka kommun, Stockholms stad och Region Stockholm under en avsiktsförklaring om Östlig förbindelse. Samtidigt skrevs ett tilläggsavtal om finansieringen av tunnelbaneutbyggnaden.', 'Beskedet våren 2026 innebär att projektet går från politisk avsikt till finansierad planeringsstart, men det är fortfarande långt mellan planering och färdig trafikled.'] },
    { heading: 'Det här måste NackaSidan granska', paragraphs: ['Den centrala frågan framåt är inte bara om tunneln byggs, utan vad den slutligen kostar, hur den finansieras, vilken trafiknytta den beräknas ge och vilka miljöeffekter som följer.', 'NackaSidan kommer därför att skilja på planeringsbeslut, byggbeslut och faktisk finansiering. Ett projekt på tiotals miljarder behöver följas över många år för att läsarna ska kunna se hur kalkyl, tidplan och politiska löften förändras.'] }
  ],
  knowledge: [{ label: 'Planeringsmedel', text: '1 miljard kronor.' }, { label: 'Beräknad kostnad', text: 'Cirka 34 miljarder kronor i 2023 års prisnivå.' }, { label: 'Sträckning', text: 'Föreslagen länk mellan Nacka/Sickla och Ropsten/Värtan.' }, { label: 'Besked', text: 'Nationella planen, 27 april 2026.' }],
  facts: ['Östlig förbindelse ska knyta samman Norra och Södra länken.', 'En avsiktsförklaring skrevs under av staten, Nacka, Stockholm och Region Stockholm i oktober 2025.', 'Projektet hade tidigare avvecklats efter att inte ha ingått i nationell plan.'],
  analysis: 'Den stora journalistiska risken är att blanda ihop en miljard i planeringsmedel med ett finansierat byggprojekt. Först när staten redovisar genomförande, finansiering och tidplan går det att bedöma hur nära en faktisk tunnel Stockholm har kommit.',
  consequences: ['Planeringsarbetet kan nu återstarta med statlig finansiering.', 'Nacka och Värmdö kan på sikt få en ny nord-sydlig vägförbindelse.', 'Projektets mycket stora totalkostnad gör finansieringen till en central framtida fråga.'],
  sources: [{ label: 'Nacka kommun: Östlig förbindelse med i nationell plan', url: 'https://www.nacka.se/kommun--politik/nyheter-kommun-politik/2026/04/ostlig-forbindelse-med-i-nationell-plan/', type: 'Primärkälla' }, { label: 'Nacka kommun: avsiktsförklaring 2025', url: 'https://www.nacka.se/kommun--politik/nyheter-kommun-politik/2025/10/avsiktsforklaring-gallande-ostlig-forbindelse-och-tillaggsavtal-for-tunnelbanan-paskrivna/', type: 'Primärkälla' }],
  tags: ['Nacka','Trafik','Östlig förbindelse','Infrastruktur'], related: ['nacka-investeringar-2026-2028','sickla-2030-tunnelbana-bostader']
};

const investments158: Article = {
  slug: 'nacka-investeringar-2026-2028', section: 'Nacka · Ekonomi', title: 'Nacka investerar 1,9 miljarder i stadsutveckling – här är projekten som får mest pengar', intro: 'Nacka kommun planerar stadsutvecklingsinvesteringar på 1,9 miljarder kronor under 2026–2028.', author: 'NackaSidans redaktion', published: '13 augusti 2026', updated: '13 augusti 2026 kl. 09.44', publishedAt: '2026-08-13T09:44:00+02:00', updatedAt: '2026-08-13T09:44:00+02:00', status: 'published', homepage: { role: 'top', order: 0 }, teaserTitle: '1,9 miljarder till Nackas stadsutveckling', teaserSummary: 'Värmdövägen, Sydöstra Boo, Nacka strand, Orminge och Bytespunkt Nacka hör till de stora projekten.', readingTime: '8 min', body: [{ heading: '580 miljoner 2026', paragraphs: ['Investeringsplanen innehåller 1 900 miljoner kronor 2026–2028.', 'Fördelningen är 580, 560 och 760 miljoner kronor.'] }], knowledge: [{ label: 'Totalt', text: '1,9 miljarder kronor.' }], facts: ['Värmdövägen hör till de stora projekten.'], analysis: 'Uppföljning av utfall är lika viktig som budget.', consequences: ['Investeringarna påverkar framtida kapitalkostnader.'], sources: [{ label: 'Nacka kommun: Mål och budget 2026–2028', url: 'https://www.nacka.se/4ace44/globalassets/kommun-politik/dokument/ekonomi-statistik/budget/mal-och-budget-for-nacka-kommun-2026-2028.pdf', type: 'Primärkälla' }], tags: ['Nacka','Ekonomi'], related: ['ostlig-forbindelse-nationell-plan-2026'] };

const parking157: Article = { slug: 'nacka-parkeringsavgifter-2026', section: 'Nacka · Trafik', title: 'Nya parkeringsavgifter i Nacka – här är reglerna och varför kommunen ändrar systemet', intro: 'Nacka kommun inför och utökar parkeringsavgifter successivt.', author: 'NackaSidans redaktion', published: '13 augusti 2026', updated: '13 augusti 2026 kl. 19.05', publishedAt: '2026-08-13T19:05:00+02:00', updatedAt: '2026-08-13T19:05:00+02:00', status: 'published', homepage: { role: 'top', order: 1 }, teaserTitle: 'Nackas nya parkeringsavgifter', teaserSummary: 'Avgifterna införs successivt.', readingTime: '6 min', body: [{ heading: 'Införs stegvis', paragraphs: ['Genomförandet sker successivt.', 'Skyltningen avgör reglerna.'] }], knowledge: [{ label: 'Vardagar', text: 'Grundmodell 07.00–19.00.' }], facts: ['Tidsbegränsning kan förekomma.'], analysis: 'Parkering är trafik- och stadsutveckling.', consequences: ['Kontrollera skyltning.'], sources: [{ label: 'Nacka kommun: parkeringsavgifter', url: 'https://www.nacka.se/stadsutveckling-trafik/trafik-och-resande/parkering/parkeringsavgifter-och-boendeparkering/fragor-och-svar-andring-och-utokning-av-parkeringsavgifter-och-boendeparkering/', type: 'Primärkälla' }], tags: ['Nacka','Trafik'], related: ['ostlig-forbindelse-nationell-plan-2026'] };

const budget156: Article = { slug: 'nacka-budget-2026-skola-skatt', section: 'Nacka · Ekonomi', title: 'Så fördelas Nackas skattepengar 2026 – skolan får 3,5 miljarder samtidigt som skatten sänks', intro: 'Nacka kommuns budget kombinerar skattesänkning med stora utgifter.', author: 'NackaSidans redaktion', published: '13 augusti 2026', updated: '13 augusti 2026', publishedAt: '2026-08-13T18:30:00+02:00', updatedAt: '2026-08-13T18:30:00+02:00', status: 'published', homepage: { role: 'top', order: 2 }, teaserTitle: 'Nackas budget 2026', teaserSummary: 'Utbildning får 3 521 miljoner kronor.', readingTime: '8 min', body: [{ heading: 'Utbildning', paragraphs: ['Utbildning är största posten.', 'Omsorg följer därefter.'] }], knowledge: [{ label: 'Skatt', text: '17,78.' }], facts: ['Utbildning: 3 521 mnkr.'], analysis: 'Låg skatt kombineras med investeringar.', consequences: ['Utfallet behöver följas.'], sources: [{ label: 'Nacka kommun: budget', url: 'https://www.nacka.se/kommun--politik/ekonomi-och-statistik/mal-och-budget/', type: 'Primärkälla' }], tags: ['Nacka','Ekonomi'], related: ['ostlig-forbindelse-nationell-plan-2026'] };

const centralaNacka155: Article = { slug: 'centrala-nacka-omtag-2026', section: 'Nacka · Centrala Nacka', title: 'Centrala Nacka gör om planen – 4 500 bostäder och 3 500 arbetsplatser står kvar som mål', intro: 'Kommunen har beslutat om ett samlat omtag.', author: 'NackaSidans redaktion', published: '13 augusti 2026', updated: '13 augusti 2026', publishedAt: '2026-08-13T00:25:00+02:00', updatedAt: '2026-08-13T00:25:00+02:00', status: 'published', homepage: { role: 'top', order: 3 }, teaserTitle: 'Centrala Nacka gör om planen', teaserSummary: 'Målen ligger kvar.', readingTime: '8 min', body: [{ heading: 'Omtaget', paragraphs: ['Ny inriktning beslutades 15 juni 2026.', 'Planeringen fortsätter.'] }], knowledge: [{ label: 'Bostäder', text: '4 500.' }], facts: ['Tunnelbana planeras 2030.'], analysis: 'Genomförandet förändras.', consequences: ['Etapper kan ändras.'], sources: [{ label: 'Nacka kommun: Centrala Nacka', url: 'https://www.nacka.se/stadsutveckling-trafik/har-planerar-och-bygger-vi/sok-projekt-pa-namn/centrala-nacka/', type: 'Primärkälla' }], tags: ['Nacka'], related: ['ostlig-forbindelse-nationell-plan-2026'] };

const sickla154: Article = { slug: 'sickla-2030-tunnelbana-bostader', section: 'Nacka · Sickla', title: 'Sickla 2030: 4 500 nya bostäder och åtta minuter till T-Centralen', intro: 'Sickla står inför en stor omvandling.', author: 'NackaSidans redaktion', published: '13 augusti 2026', updated: '13 augusti 2026', publishedAt: '2026-08-13T00:15:00+02:00', updatedAt: '2026-08-13T00:15:00+02:00', status: 'published', homepage: { role: 'top', order: 4 }, teaserTitle: 'Sickla 2030', teaserSummary: 'Tunnelbana och bostäder förändrar Sickla.', readingTime: '7 min', body: [{ heading: 'Tunnelbanan', paragraphs: ['Öppning planeras 2030.', 'Restid cirka åtta minuter.'] }], knowledge: [{ label: 'Bostäder', text: 'Omkring 4 500.' }], facts: ['Tunnelbanan planeras öppna 2030.'], analysis: 'Kollektivtrafik och stadsutveckling binds samman.', consequences: ['Servicebehovet ökar.'], sources: [{ label: 'Nacka kommun: Sickla', url: 'https://www.nacka.se/stadsutveckling-trafik/har-planerar-och-bygger-vi/sok-projekt-pa-namn/sickla/', type: 'Primärkälla' }], tags: ['Nacka','Sickla'], related: ['ostlig-forbindelse-nationell-plan-2026'] };

export const localArticles153: Article[] = [iranGulf160, ostlig159, investments158, parking157, budget156, centralaNacka155, sickla154];
