import type { Article } from './articles';

const budget156: Article = {
  slug: 'nacka-budget-2026-skola-skatt', section: 'Nacka · Ekonomi',
  title: 'Så fördelas Nackas skattepengar 2026 – skolan får 3,5 miljarder samtidigt som skatten sänks',
  intro: 'Nacka kommuns budget för 2026 kombinerar en skattesänkning med stora utgifter för utbildning, omsorg, trafik och fritid. Vi går igenom vart pengarna går och vilka prioriteringar som blir viktigast att följa under året.',
  author: 'NackaSidans redaktion', published: '13 augusti 2026', updated: '13 augusti 2026 kl. 18.30', publishedAt: '2026-08-13T18:30:00+02:00', updatedAt: '2026-08-13T18:30:00+02:00', status: 'published', homepage: { role: 'lead', order: 0 },
  teaserTitle: 'Nackas budget 2026 – mer till skolan och lägre kommunalskatt', teaserSummary: 'Utbildning står för 3 521 miljoner kronor i kommunens budget. Samtidigt sänks kommunalskatten till 17,78 kronor per hundralapp.', readingTime: '8 min',
  body: [
    { heading: 'Kommunens viktigaste ekonomiska beslut', paragraphs: ['Kommunfullmäktige antog Mål och budget 2026–2028 den 17 november 2025. Dokumentet styr hur kommunens resurser ska fördelas och innehåller både driftbudget och investeringar.', 'Tre prioriteringar lyfts särskilt fram för 2026: barn och utbildning, en aktiv fritid och mer pengar kvar hos hushållen.'] },
    { heading: '3,5 miljarder till utbildning', paragraphs: ['Utbildning är den största enskilda posten i den redovisade fördelningen av skattepengarna: 3 521 miljoner kronor. Omsorg och stöd följer med 2 330 miljoner kronor.', 'Natur och trafik får 521 miljoner kronor, fritid 248 miljoner och kultur 167 miljoner. För NackaSidan blir det viktigt att följa hur budgetnivåerna omsätts i faktisk kvalitet och service.'] },
    { heading: 'Skatten sänks till 17,78', paragraphs: ['Kommunalskatten i Nacka sänks 2026 med tio öre till 17,78 kronor per hundralapp. Region Stockholms skatt sänks samtidigt med fem öre till 12,33.', 'Skattesänkningen gör budgetens balans extra intressant: kommunen vill både hålla nere skatten och finansiera växande behov i en kommun med över 113 000 invånare.'] },
    { heading: 'Investeringarna kräver ekonomiska marginaler', paragraphs: ['Budgetdokumentet slår fast att kommunen behöver resultatöverskott för att kunna finansiera investeringar och hantera oväntade förändringar. Målet för 2026–2028 är ett resultatöverskott på minst 2,0 procent i den ordinarie verksamheten.', 'Det innebär att en del av den ekonomiska styrningen handlar om att skapa marginaler för framtida investeringar, inte bara om årets löpande verksamhet.'] },
    { heading: 'Det här kommer NackaSidan att följa', paragraphs: ['Budgeten är ett löfte om prioriteringar, men uppföljningen visar om pengarna faktiskt räcker. Därför kommer vi att jämföra budgeten med kommunens tertialbokslut, investeringarnas kostnadsutveckling och verksamheternas resultat.', 'Särskilt intressant blir skolan, omsorgen, trafiken och de stora stadsutvecklingsprojekten. Där finns både de största beloppen och frågor som påverkar många Nackabor direkt.'] }
  ],
  knowledge: [{ label: 'Kommunalskatt', text: '17,78 kronor per hundralapp 2026.' }, { label: 'Utbildning', text: '3 521 miljoner kronor.' }, { label: 'Omsorg och stöd', text: '2 330 miljoner kronor.' }, { label: 'Resultatmål', text: 'Minst 2,0 procents överskott i ordinarie verksamhet 2026–2028.' }],
  facts: ['Budgeten antogs av kommunfullmäktige den 17 november 2025.', 'Natur och trafik budgeteras till 521 miljoner kronor.', 'Fritid budgeteras till 248 miljoner kronor och kultur till 167 miljoner kronor.'],
  analysis: 'Den centrala ekonomiska frågan 2026 är hur Nacka kombinerar låg skatt med växande service- och investeringsbehov. Budgeterade belopp säger inte ensamma om verksamheten fungerar; därför behöver kostnader, resultat och investeringsutfall följas tillsammans under året.',
  consequences: ['Hushållen får en mindre sänkning av kommunalskatten.', 'Skola och omsorg fortsätter dominera kommunens resursfördelning.', 'Stora investeringar gör kommunens resultatmarginal och kostnadskontroll viktiga att bevaka.'],
  sources: [{ label: 'Nacka kommun: Mål och budget 2026–2028', url: 'https://www.nacka.se/kommun--politik/ekonomi-och-statistik/mal-och-budget/', type: 'Primärkälla' }, { label: 'Nacka kommun: Så fördelas skattepengarna 2026', url: 'https://www.nacka.se/kommun--politik/nyheter-kommun-politik/2025/11/ta-del-av-mal-och-budget-for-2026-2028/', type: 'Primärkälla' }, { label: 'Nacka kommun: Ekonomi och statistik', url: 'https://www.nacka.se/kommun--politik/ekonomi-och-statistik/', type: 'Primärkälla' }],
  tags: ['Nacka', 'Ekonomi', 'Budget', 'Skatt', 'Skola'], related: ['centrala-nacka-omtag-2026', 'sickla-2030-tunnelbana-bostader']
};

const centralaNacka155: Article = {
  slug: 'centrala-nacka-omtag-2026', section: 'Nacka · Centrala Nacka', title: 'Centrala Nacka gör om planen – 4 500 bostäder och 3 500 arbetsplatser står kvar som mål', intro: 'Efter att projektet Mötesplats Nacka pausades 2024 har kommunen beslutat om ett samlat omtag för Centrala Nacka.', author: 'NackaSidans redaktion', published: '13 augusti 2026', updated: '13 augusti 2026 kl. 00.25', publishedAt: '2026-08-13T00:25:00+02:00', updatedAt: '2026-08-13T00:25:00+02:00', status: 'published', homepage: { role: 'top', order: 0 }, teaserTitle: 'Centrala Nacka gör om planen efter pausat jätteprojekt', teaserSummary: 'Målet om 4 500 bostäder och 3 500 arbetsplatser ligger kvar.', readingTime: '8 min', body: [{ heading: 'Beslutet som ändrar spelplanen', paragraphs: ['Kommunstyrelsen beslutade den 15 juni 2026 om en ny övergripande inriktning.', 'Planeringen görs om efter att Mötesplats Nacka pausades.'] }, { heading: 'Tunnelbanan sätter tidslinjen', paragraphs: ['Tunnelbanan till Nacka planeras öppna 2030.', 'Åren fram till dess blir avgörande för samordningen av stadsutvecklingen.'] }], knowledge: [{ label: 'Bostäder', text: 'Omkring 4 500 bostäder.' }, { label: 'Arbetsplatser', text: 'Omkring 3 500 arbetsplatser.' }], facts: ['Mötesplats Nacka pausades 2024.'], analysis: 'Omtaget förändrar sambanden mellan idrott, bostäder, handel och offentliga rum.', consequences: ['Genomförandet kan förändras.'], sources: [{ label: 'Nacka kommun: Centrala Nacka', url: 'https://www.nacka.se/stadsutveckling-trafik/har-planerar-och-bygger-vi/sok-projekt-pa-namn/centrala-nacka/', type: 'Primärkälla' }], tags: ['Nacka','Centrala Nacka'], related: ['nacka-budget-2026-skola-skatt']
};

const sickla154: Article = { slug: 'sickla-2030-tunnelbana-bostader', section: 'Nacka · Sickla', title: 'Sickla 2030: 4 500 nya bostäder och åtta minuter till T-Centralen', intro: 'Sickla står inför en av Nackas största omvandlingar.', author: 'NackaSidans redaktion', published: '13 augusti 2026', updated: '13 augusti 2026 kl. 00.15', publishedAt: '2026-08-13T00:15:00+02:00', updatedAt: '2026-08-13T00:15:00+02:00', status: 'published', homepage: { role: 'top', order: 1 }, teaserTitle: 'Sickla 2030 – staden växer kring tunnelbanan', teaserSummary: 'Omkring 4 500 bostäder och tunnelbana förändrar Sickla.', readingTime: '7 min', body: [{ heading: 'Åtta minuter till T-Centralen', paragraphs: ['Enligt kommunen ska resan ta omkring åtta minuter när tunnelbanan öppnar 2030.', 'Utvecklingen sker i många parallella projekt.'] }], knowledge: [{ label: 'Bostäder', text: 'Omkring 4 500 nya bostäder.' }], facts: ['Tunnelbanan planeras öppna 2030.'], analysis: 'Kollektivtrafik och bostadsbyggande binds samman.', consequences: ['Servicebehovet ökar.'], sources: [{ label: 'Nacka kommun: Sickla', url: 'https://www.nacka.se/stadsutveckling-trafik/har-planerar-och-bygger-vi/sok-projekt-pa-namn/sickla/', type: 'Primärkälla' }], tags: ['Nacka','Sickla'], related: ['nacka-budget-2026-skola-skatt'] };

export const localArticles153: Article[] = [budget156, centralaNacka155, sickla154];
