import { editorial373 } from './editorial373';

export const nackaDeepDive = [
  ...editorial373,
  { section:'Nacka · Stadsutveckling', title:'Birka blir en av valets stora lokala stridsfrågor', summary:'Planprogrammet öppnar för omkring 900 bostäder, två förskolor och ett vård- och omsorgsboende nära Järla. Planerna innebär samtidigt att 26 villor kan rivas.', why:'Birka samlar flera av Nackas största konflikter i en fråga: bostadsbyggande, tunnelbana, kulturmiljö och förtätning.', date:'23 augusti 2026', href:'https://www.svt.se/nyheter/lokalt/stockholm/26-villor-planeras-rivas-i-nacka-ska-ersattas-med-900-lagenheter', source:'SVT Nyheter' },
  { section:'Val 2026', title:'Tre veckor kvar till valet – förtidsröstningen börjar på onsdag', summary:'Den 13 september är det val till kommun, region och riksdag. Förtidsröstningen startar den 26 augusti och pågår fram till valdagen.', why:'Nu går den lokala valrörelsen in i sitt avgörande skede och sakfrågorna blir viktigare än valaffischerna.', date:'23 augusti 2026', href:'https://www.nacka.se/kommun--politik/delta-och-paverka/val-2026/', source:'Nacka kommun' },
  { section:'Nacka · Stadsutveckling', title:'11 300 nya bostäder planeras på Västra Sicklaön fram till 2035', summary:'Kommunens långsiktiga planering omfattar 11 300 nya bostäder och 10 000 arbetsplatser på Västra Sicklaön, kopplat till tunnelbanans utbyggnad.', why:'Omvandlingen påverkar trafik, skolor, service, bostadsmarknad och Nackas karaktär under lång tid.', date:'23 augusti 2026', href:'https://www.nacka.se/stadsutveckling-trafik/har-planerar-och-bygger-vi/', source:'Nacka kommun' },
  { section:'Nacka · Bygg', title:'Finnbergets bergrum går vidare i planprocessen', summary:'Detaljplanen för Finnbergets bergrum på Västra Sicklaön gick ut på granskning den 18 augusti.', why:'Planprocesserna visar var nästa våg av byggande kan komma och ger boende möjlighet att följa utvecklingen före beslut.', date:'18 augusti 2026', href:'https://www.nacka.se/stadsutveckling-trafik/har-planerar-och-bygger-vi/', source:'Nacka kommun' },
  { section:'Nacka · Bygg', title:'Traversen på Västra Sicklaön är också aktuell i planprocessen', summary:'Detaljplanen för Traversen, del av Sicklaön 83:56 med flera, gick ut på granskning den 13 augusti.', why:'Flera parallella detaljplaner visar hur snabbt Västra Sicklaön förändras inför tunnelbanans öppnande.', date:'13 augusti 2026', href:'https://www.nacka.se/stadsutveckling-trafik/har-planerar-och-bygger-vi/', source:'Nacka kommun' },
  { section:'Nacka · Trafik', title:'Tre broar längs Saltsjöbadsleden underhålls fram till november', summary:'Mellan augusti och november genomförs underhållsarbeten på tre broar nära trafikplats Fisksätra.', why:'Arbetena kan påverka vardagsresor under hösten och är viktiga att följa för boende i Fisksätra och Saltsjöbaden.', date:'11 augusti 2026', href:'https://www.nacka.se/stadsutveckling-trafik/trafik-och-resande/nyheter-om-trafik-vagar-och-resande/', source:'Nacka kommun' },
  { section:'Nacka · Trafik', title:'Talluddsvägen byggs om för lägre hastigheter och säkrare hållplatser', summary:'Trafikmiljön vid busshållplatserna Fredriksbergsvägen förbättras med tydligare avgränsning mellan trafikslagen.', why:'Små lokala trafikprojekt kan ha stor betydelse för säkerheten för gående, cyklister och kollektivtrafikresenärer.', date:'5 augusti 2026', href:'https://www.nacka.se/stadsutveckling-trafik/trafik-och-resande/nyheter-om-trafik-vagar-och-resande/', source:'Nacka kommun' },
  { section:'Nacka · Park & fritid', title:'Kyrkviksparken går in i slutskedet', summary:'Den östra delen av Kyrkviksparken närmar sig färdigställande med nya möjligheter till rekreation, naturupplevelser och aktiviteter vid vattnet.', why:'När Nacka förtätas blir kvaliteten på parker och offentliga miljöer en allt viktigare del av stadsutvecklingen.', date:'4 augusti 2026', href:'https://www.nacka.se/stadsutveckling-trafik/nyheter-om-stadsutveckling-och-trafik/', source:'Nacka kommun' },
  { section:'Nacka · Klimat & utemiljö', title:'Hög brandrisk har försenat slåttern längs vägkanterna', summary:'Kommunen uppger att den långvariga torrperioden och förhöjda brandrisken gjort att gräset längs vissa vägkanter fått stå högre än vanligt.', why:'Extremt väder påverkar redan den kommunala driften och visar hur klimatrisker blir konkreta lokala frågor.', date:'17 augusti 2026', href:'https://www.nacka.se/stadsutveckling-trafik/nyheter-om-stadsutveckling-och-trafik/', source:'Nacka kommun' },
  { section:'Nacka · Bostäder', title:'Jarlaberg växer vidare – 80 nya bostäder byggs vid Enspännarvägen', summary:'Arbetet med Enspännarvägens norra kvarter har startat. Cirka 80 bostäder planeras med preliminär inflyttning 2028.', why:'Projektet är en del av försöket att knyta ihop Jarlaberg och Nacka strand med Centrala Nacka och tunnelbanan.', date:'23 augusti 2026', href:'https://www.nacka.se/stadsutveckling-trafik/nyheter-om-stadsutveckling-och-trafik/2026/05/byggstart-for-enspannarvagens-norra-kvarter/', source:'Nacka kommun' }
] as const;
