import type { Article } from './articles';

export const stockholmArticles163: Article[] = [
  {
    slug:'se-alert-test-stockholm-7-september',
    section:'Stockholm · Beredskap',
    title:'SE-Alert testas i Stockholm – mobilvarningen ska nå människor snabbare',
    intro:'Klockan 15.00 den 7 september testar myndigheterna SE-Alert i Stockholms län. Systemet ska göra det möjligt att skicka geografiskt riktade varningar och viktig information direkt till mobiltelefoner vid allvarliga händelser.',
    author:'NackaSidans redaktion',
    published:'7 september 2026', updated:'7 september 2026 kl. 14.10',
    publishedAt:'2026-09-07T14:10:00+02:00', updatedAt:'2026-09-07T14:10:00+02:00',
    status:'published', homepage:{role:'lead',order:0},
    teaserTitle:'SE-Alert testas i Stockholm i dag',
    teaserSummary:'Det nya varningssystemet provas klockan 15.00 och ska komplettera dagens kanaler för viktig samhällsinformation.',
    readingTime:'8 min',
    body:[
      {heading:'Detta händer i dag',paragraphs:['Region Stockholm uppger att SE-Alert testas måndagen den 7 september klockan 15.00. Personer som befinner sig i det berörda området kan få ett testmeddelande direkt i mobilen.','Testet är en del av införandet av en kanal som ska kunna användas när myndigheter snabbt behöver nå människor i ett bestämt geografiskt område. Mottagaren behöver därför förstå att dagens meddelande är ett prov och inte en verklig varning.']},
      {heading:'Ett komplement till befintliga varningar',paragraphs:['Mobilvarningen ersätter inte andra etablerade kanaler. Viktigt meddelande till allmänheten, radio, myndigheters webbplatser och lokal information fortsätter att vara centrala när samhället hanterar en allvarlig händelse.','Styrkan med en geografiskt riktad mobilvarning är snabbheten och möjligheten att nå även personer som inte aktivt följer nyhetsmedier.']},
      {heading:'Analys: Tekniken måste skapa förtroende',paragraphs:['Ett varningssystem bedöms inte bara efter hur många telefoner som nås. Budskapet måste vara begripligt, avsändaren tydlig och instruktionen möjlig att följa. Om tester eller skarpa varningar uppfattas som oklara finns en risk att mottagare vänjer sig vid att ignorera dem.','För Stockholm är frågan särskilt viktig eftersom stora flöden av pendlare, besökare och turister rör sig mellan kommuner varje dag. En geografisk avgränsning måste fungera även när människor snabbt byter område.']},
      {heading:'Konsekvenser för invånarna',paragraphs:['Vid en verklig händelse kan några minuters tidigare information påverka hur människor väljer resväg, söker skydd eller undviker ett riskområde. Samtidigt behöver personer utan kompatibel mobil eller med särskilda tillgänglighetsbehov fortsatt nås genom andra kanaler.','Efter testet blir det viktigt att redovisa räckvidd, tekniska fel och om meddelandet var tillräckligt tydligt. Öppen uppföljning är en förutsättning för att systemet ska få förtroende.']},
      {heading:'Detta bör följas efter testet',paragraphs:['Regionen och ansvariga myndigheter bör beskriva hur många som nåddes och vilka telefoninställningar som kan påverka mottagningen. Det behövs också tydlig information om skillnaden mellan ett test, en rekommendation och en akut instruktion.','NackaSidan följer resultaten och hur systemet ska användas i kollektivtrafiken, vården och de olika stadsdelarna.']}
    ],
    knowledge:[{label:'Tid',text:'Testet sker den 7 september klockan 15.00.'},{label:'Syfte',text:'Att snabbt kunna skicka geografiskt riktad samhällsinformation till mobiler.'}],
    facts:['SE-Alert testas i Stockholms län.','Meddelandet är ett test, inte en skarp varning.','Systemet ska komplettera andra varningskanaler.'],
    analysis:'SE-Alert kan förkorta tiden mellan ett myndighetsbeslut och att människor i ett riskområde får användbar information. Nyttan avgörs dock av räckvidd, tydlighet, tillgänglighet och hur väl kanalen samspelar med radio, VMA och lokal kriskommunikation.',
    consequences:['Snabbare information vid allvarliga händelser.','Krav på tydliga instruktioner och fungerande tillgänglighet.','Behov av offentlig uppföljning efter testet.'],
    sources:[{label:'Region Stockholm: SE-Alert testas måndag den 7 september',url:'https://www.regionstockholm.se/nyheter/2026/09/se-alert-testas-mandag-den-7-september/',type:'Primärkälla'}],
    tags:['Stockholm','Beredskap','SE-Alert','Säkerhet'], related:[]
  },
  {
    slug:'massling-tolv-fall-region-stockholm',
    section:'Stockholm · Hälsa',
    title:'Tolv mässlingsfall bekräftade i Region Stockholm',
    intro:'Region Stockholm har bekräftat tolv fall av mässling. Nio fall kopplas till smitta under festivalen Urkult och tre till personer som smittats av festivalbesökare.',
    author:'NackaSidans redaktion',
    published:'7 september 2026', updated:'7 september 2026 kl. 13.35',
    publishedAt:'2026-09-07T13:35:00+02:00', updatedAt:'2026-09-07T13:35:00+02:00',
    status:'published', homepage:{role:'feature',order:1},
    teaserTitle:'Tolv mässlingsfall i Stockholmsregionen',
    teaserSummary:'Smittskyddet följer en smittkedja med koppling till en festival i Sollefteå.',
    readingTime:'8 min',
    body:[
      {heading:'Smittkedjan kartläggs',paragraphs:['Region Stockholm uppger att tolv fall har bekräftats. Nio personer bedöms ha smittats under festivalen Urkult i Sollefteå och tre av personer som varit där.','Uppgifterna visar att smittan har förts vidare efter festivalen. Smittspårning och snabb information till personer som kan ha exponerats är därför centrala delar av arbetet.']},
      {heading:'Mässling är mycket smittsamt',paragraphs:['Mässling sprids genom luften och kan smitta innan den sjuke själv förstår att symtomen beror på mässling. Feber, hosta och utslag är typiska tecken, men medicinsk bedömning ska göras av vården.','Den som misstänker mässling bör kontakta vården innan ett fysiskt besök, så att andra patienter inte utsätts för smitta i väntrum.']},
      {heading:'Analys: Lokal smitta kräver regional överblick',paragraphs:['Stockholmsregionen har stor daglig rörlighet. En smittkedja kan snabbt beröra kollektivtrafik, arbetsplatser, skolor och vårdmottagningar i flera kommuner. Därför räcker det inte att följa ett enskilt bostadsområde.','Vaccinationstäckningen är det viktigaste långsiktiga skyddet, men i ett pågående läge är snabb smittspårning och korrekt information avgörande för att begränsa spridningen.']},
      {heading:'Konsekvenser för vård och invånare',paragraphs:['Vården behöver kunna separera misstänkta fall från andra patienter och samtidigt svara på frågor utan att skapa onödig oro. Invånare behöver veta var den senaste officiella informationen finns.','Läget bör beskrivas med exakta, daterade siffror. Antalet bekräftade fall kan förändras och äldre uppgifter ska inte presenteras som dagens lägesbild.']},
      {heading:'Detta behöver följas',paragraphs:['Fortsatt rapportering bör visa om nya fall tillkommer, om smittkedjorna är kända och vilka råd smittskyddet ger. Uppgifter om enskilda personer ska samtidigt skyddas.','NackaSidan länkar därför direkt till Region Stockholms uppdaterade information och skiljer bekräftade uppgifter från redaktionell analys.']}
    ],
    knowledge:[{label:'12 fall',text:'Bekräftade fall enligt Region Stockholms uppdatering.'},{label:'9 + 3',text:'Nio festivalrelaterade fall och tre sekundärsmittade.'}],
    facts:['Tolv fall har bekräftats.','Nio fall kopplas till festivalen Urkult.','Tre personer har smittats av personer som varit på festivalen.'],
    analysis:'Det avgörande är om smittspårningen kan ringa in alla kedjor. Stockholms stora rörlighet gör samordnad regional information viktig, samtidigt som proportionerna måste hållas tydliga för att undvika ryktesspridning.',
    consequences:['Ökat behov av smittspårning.','Vården måste minska risken för exponering i väntrum.','Aktuella vaccinationsuppgifter blir viktigare.'],
    sources:[{label:'Region Stockholm: Uppdaterad information om antal mässlingsfall',url:'https://www.regionstockholm.se/nyheter/2026/09/uppdaterad-information-om-antal-masslingsfall/',type:'Primärkälla'}],
    tags:['Stockholm','Hälsa','Mässling','Region Stockholm'], related:['se-alert-test-stockholm-7-september']
  },
  {
    slug:'stockholms-lan-112000-fler-2035',
    section:'Stockholm · Befolkning',
    title:'Stockholms län väntas växa med 112 000 invånare till 2035',
    intro:'En ny regional prognos pekar mot fortsatt befolkningstillväxt men också färre unga och betydligt fler äldre. För kommunerna förändrar det behoven av bostäder, skolor, vård och kollektivtrafik.',
    author:'NackaSidans redaktion',
    published:'7 september 2026', updated:'7 september 2026 kl. 12.40',
    publishedAt:'2026-09-07T12:40:00+02:00', updatedAt:'2026-09-07T12:40:00+02:00',
    status:'published', homepage:{role:'feature',order:2},
    teaserTitle:'Länet kan växa med 112 000 invånare',
    teaserSummary:'Fler äldre och färre unga förändrar planeringen i Stockholms kommuner.',
    readingTime:'10 min',
    body:[
      {heading:'Tillväxten fortsätter i lägre takt',paragraphs:['Region Stockholms prognos visar att länets befolkning väntas öka med omkring 112 000 personer fram till 2035. Barnafödandet är lågt och väntas enligt prognosen öka först efter 2030.','En prognos är inte ett facit. Flyttning, konjunktur, bostadsbyggande och politiska beslut kan förändra utvecklingen, men underlaget används redan i långsiktig planering.']},
      {heading:'Åldersstrukturen förändras',paragraphs:['Antalet äldre väntas öka tydligt medan antalet unga minskar. Det innebär att en växande totalbefolkning inte automatiskt ger större elevkullar i alla delar av länet.','Skillnaderna mellan kommuner och stadsdelar kan vara stora. Därför behöver investeringar bedömas lokalt och inte enbart utifrån länets totalsiffra.']},
      {heading:'Analys: Två planeringsproblem samtidigt',paragraphs:['Regionen måste både skapa kapacitet för fler invånare och flytta resurser när befolkningens ålder förändras. Det kan innebära mindre skolbehov i ett område samtidigt som behovet av äldreomsorg och tillgänglig kollektivtrafik ökar.','Bostadsmarknaden är en nyckel. Om rätt bostäder inte byggs där människor kan och vill bo påverkas både flyttkedjor och arbetsmarknadens tillgång till personal.']},
      {heading:'Konsekvenser för Stockholm och Nacka',paragraphs:['Kommunerna behöver samordna bostadsbyggande med spår, bussar, vårdcentraler och annan service. Projekt som försenas kan skapa trängsel långt innan ny kapacitet är färdig.','Fler äldre ställer också krav på tillgängliga bostäder. När äldre kan flytta till ändamålsenliga bostäder kan större bostäder frigöras för barnfamiljer, men sådana flyttkedjor uppstår inte av sig själva.']},
      {heading:'Så bör prognosen följas',paragraphs:['Det behövs årliga jämförelser mellan prognos och utfall, uppdelade på kommun, stadsdel och ålder. Även färdigställda bostäder och faktisk kapacitet i kollektivtrafik och vård bör följas.','En transparent uppföljning gör det möjligt att ändra investeringar i tid i stället för att hålla fast vid antaganden som inte längre gäller.']}
    ],
    knowledge:[{label:'112 000',text:'Prognostiserad ökning i Stockholms län till 2035.'},{label:'Efter 2030',text:'Barnafödandet väntas enligt prognosen börja öka.'}],
    facts:['Länets befolkning väntas öka till 2035.','Antalet äldre väntas öka tydligt.','Antalet unga väntas minska.'],
    analysis:'Den stora frågan är inte bara hur många fler som bor i länet utan var de bor och vilken ålder de har. Infrastruktur och välfärd behöver planeras mot flera möjliga utfall, eftersom felinvesteringar blir dyra och långvariga.',
    consequences:['Större behov av äldreomsorg och tillgängliga bostäder.','Skolkapacitet kan behöva omfördelas.','Bostäder och kollektivtrafik måste planeras tillsammans.'],
    sources:[{label:'Region Stockholm: Befolkningen väntas öka med 112 000 personer',url:'https://www.regionstockholm.se/nyheter/2026/09/befolkningen-i-stockholms-lan-vantas-oka-med-112-000-personer-fram-till-2035/',type:'Primärkälla'}],
    tags:['Stockholm','Befolkning','Bostäder','Kollektivtrafik'], related:[]
  },
  {
    slug:'gotgatan-tunnelarbete-vecka-37',
    section:'Södermalm · Trafik',
    title:'Ny etapp för tunnelarbetet under Götgatan',
    intro:'Arbetet med tunneln under Götgatan går vidare. Under vecka 37 möter projektet boende och verksamheter vid byggområdets norra entré för att svara på frågor om nästa etapp.',
    author:'NackaSidans redaktion',
    published:'7 september 2026', updated:'7 september 2026 kl. 11.55',
    publishedAt:'2026-09-07T11:55:00+02:00', updatedAt:'2026-09-07T11:55:00+02:00',
    status:'published', homepage:{role:'feature',order:3},
    teaserTitle:'Tunnelarbetet under Götgatan går in i ny etapp',
    teaserSummary:'Boende och företag kan träffa projektet under vecka 37.',
    readingTime:'7 min',
    body:[
      {heading:'Information på plats',paragraphs:['Region Stockholm meddelar att arbetet med tunneln under Götgatan snart går vidare till nästa etapp. Under vecka 37 finns representanter vid det nuvarande byggområdets norra entré.','Syftet är att berätta om kommande arbeten och svara på frågor från boende, pendlare och verksamheter.']},
      {heading:'Lokala störningar kan få bred effekt',paragraphs:['Götgatan är både ett lokalt stråk på Södermalm och en viktig förbindelse för gång, cykel, handel och kollektivtrafik. Förändringar i framkomlighet kan därför påverka fler än dem som bor närmast byggområdet.','Exakta avstängningar och tider bör alltid kontrolleras mot projektets aktuella information innan en resa.']},
      {heading:'Analys: Förutsägbarhet är avgörande',paragraphs:['Stora arbeten mitt i en tät stadsdel går sällan att genomföra utan störningar. Konflikten står ofta mellan behovet av snabb byggtakt och behovet av tillgång till butiker, bostäder och säkra passager.','Tidiga besked och en realistisk tidplan gör det lättare för småföretag och boende att planera. När information ändras sent flyttas en större del av kostnaden från projektet till omgivningen.']},
      {heading:'Konsekvenser för Södermalm',paragraphs:['Tillfälliga omledningar kan ändra kundflöden och restider. Säkerheten för gående och cyklister behöver följas när rörelsemönster flyttas.','Mötet på plats ger invånarna en möjlighet att få detaljer, men informationen behöver även finnas digitalt för den som inte kan delta.']},
      {heading:'Detta behöver följas',paragraphs:['Kommande rapportering bör redovisa etapper, beräknade sluttider, förändrade passager och hur tillgängligheten säkras. Eventuella förseningar bör dateras och förklaras.','NackaSidan följer särskilt hur arbetet påverkar resor mellan Södermalm, Slussen, Nacka och Värmdö.']}
    ],
    knowledge:[{label:'Vecka 37',text:'Projektet finns på plats för att informera och svara på frågor.'},{label:'Plats',text:'Byggområdets norra entré vid Götgatan.'}],
    facts:['Arbetet går vidare till nästa etapp.','Information ges på plats under vecka 37.','Region Stockholm är källa till uppgifterna.'],
    analysis:'Projektets legitimitet påverkas av hur tydligt störningar, tidplan och alternativ kommuniceras. Ett lokalt vägarbete kan få regional påverkan när det ligger nära ett av Stockholms viktigaste bytesområden.',
    consequences:['Ändrade gång-, cykel- och trafikflöden.','Påverkan på lokala verksamheter.','Behov av uppdaterad reseinformation.'],
    sources:[{label:'Region Stockholm: Träffa oss och ställ frågor om arbetena på Götgatan',url:'https://www.regionstockholm.se/nyheter/2026/09/traffa-oss-och-stall-fragor-om-arbetena-pa-gotgatan/',type:'Primärkälla'}],
    tags:['Stockholm','Södermalm','Götgatan','Trafik'], related:[]
  },
  {
    slug:'arkipelag-sveriges-oscarsbidrag',
    section:'Stockholm · Kultur',
    title:'Stockholmsfilmen ”Arkipelag” blir Sveriges Oscarsbidrag',
    intro:'Alex Schulmans ”Arkipelag”, inspelad i Stockholms skärgård och samproducerad av Film Stockholm, har valts till Sveriges bidrag i kategorin bästa internationella långfilm.',
    author:'NackaSidans redaktion',
    published:'7 september 2026', updated:'7 september 2026 kl. 10.45',
    publishedAt:'2026-09-07T10:45:00+02:00', updatedAt:'2026-09-07T10:45:00+02:00',
    status:'published', homepage:{role:'feature',order:4},
    teaserTitle:'”Arkipelag” är Sveriges Oscarsbidrag',
    teaserSummary:'Filmen är inspelad i Stockholms skärgård och samproducerad av Film Stockholm.',
    readingTime:'7 min',
    body:[
      {heading:'Svenska Filminstitutet har valt filmen',paragraphs:['Svenska Filminstitutet har utsett ”Arkipelag” till Sveriges bidrag till den 99:e Oscarsgalan. Filmen är inspelad i Stockholms skärgård och Film Stockholm är samproducent.','Valet innebär inte att filmen redan är Oscarsnominerad. Först offentliggörs en kortlista och därefter de slutliga nomineringarna.']},
      {heading:'Vägen till galan',paragraphs:['Enligt Region Stockholm presenteras kortlistan med femton filmer den 15 december. De slutliga nomineringarna offentliggörs den 21 januari och Oscarsgalan hålls den 14 mars 2027.','Under tiden väntar internationell lansering och kampanjarbete, där distribution, festivalnärvaro och mottagande påverkar filmens möjligheter.']},
      {heading:'Analys: Mer än kulturell prestige',paragraphs:['Ett svenskt Oscarsbidrag med tydlig Stockholmsanknytning fungerar som skyltfönster för regionens inspelningsmiljöer och filmkompetens. Effekten kan märkas i efterfrågan på teknisk personal, lokaler och framtida produktioner.','Samtidigt ska den ekonomiska effekten inte överdrivas. Ett valt bidrag garanterar varken nominering eller nya investeringar. Långsiktig nytta kräver stabil finansiering och kompetens mellan enskilda framgångar.']},
      {heading:'Konsekvenser för regionens filmbransch',paragraphs:['Uppmärksamheten kan stärka Film Stockholms nätverk och skärgårdens attraktivitet som inspelningsplats. Lokala leverantörer kan gynnas om fler produktioner väljer regionen.','Framgången väcker också frågan om hur offentliga filmsatsningar ska värderas: genom priser, arbetstillfällen, publik eller en kombination.']},
      {heading:'Detta händer härnäst',paragraphs:['Nästa tydliga kontrollpunkt är kortlistan den 15 december. Fram till dess bör rapporteringen skilja mellan Sveriges val av bidrag och en faktisk Oscarsnominering.','NackaSidan följer filmens internationella väg och vad uppmärksamheten betyder för kulturproduktionen i Stockholm.']}
    ],
    knowledge:[{label:'15 december',text:'Kortlistan med femton filmer offentliggörs.'},{label:'14 mars 2027',text:'Den 99:e Oscarsgalan hålls i Los Angeles.'}],
    facts:['”Arkipelag” är Sveriges Oscarsbidrag.','Filmen är inspelad i Stockholms skärgård.','Film Stockholm är samproducent.'],
    analysis:'Utnämningen ger Stockholms filmbransch internationell synlighet, men det verkliga värdet beror på om uppmärksamheten omsätts i fler produktioner, kompetens och hållbara arbetstillfällen.',
    consequences:['Ökad synlighet för skärgården som inspelningsmiljö.','Möjlighet till fler regionala filmproduktioner.','Större uppmärksamhet kring offentlig filmfinansiering.'],
    sources:[{label:'Region Stockholm: ”Arkipelag” är Sveriges Oscarsbidrag',url:'https://www.regionstockholm.se/nyheter/2026/09/film-stockholms-samproduktion-arkipelag-ar-sveriges-oscarsbidrag/',type:'Primärkälla'}],
    tags:['Stockholm','Kultur','Film','Skärgården'], related:[]
  }
];
