import type { WeekendArticle } from './weekend';

type Draft = {
 slug:string; section:string; title:string; intro:string;
 focus:string; context:string; perspective:string; next:string;
 sources:{label:string;url:string}[];
};

const published='15 september 2026';

function article(d:Draft):WeekendArticle {
 return {
  slug:d.slug, section:d.section, title:d.title, intro:d.intro, published, readingTime:'18 min',
  news:[
   {heading:'Det aktuella läget',paragraphs:[
    d.focus,
    `${d.context} Det gör frågan större än den enskilda händelsen. Den handlar också om vilka val människor, företag och offentliga institutioner gör när gamla vanor möter nya villkor.`
   ]},
   {heading:'Varför frågan har blivit viktig nu',paragraphs:[
    `${d.perspective} Förändringen märks sällan på en gång. Den byggs upp genom många små beslut och blir tydlig först när vardagen, ekonomin eller det offentliga samtalet börjar fungera på ett nytt sätt.`,
    `Det finns samtidigt skäl att undvika snabba slutsatser. En trend kan vara stark i vissa grupper och svag i andra. NackaSidans läsning skiljer därför mellan det som redan går att belägga, det som är en rimlig utveckling och det som fortfarande är osäkert.`
   ]},
   {heading:'Människorna bakom utvecklingen',paragraphs:[
    `Bakom de stora orden finns konkreta erfarenheter. Hushåll väger tid mot pengar, verksamheter väger kvalitet mot kostnad och beslutsfattare väger kortsiktiga krav mot långsiktigt ansvar. Det är i dessa avvägningar som ${d.section.toLowerCase()} blir begripligt.`,
    `Skillnaderna i resurser spelar roll. Den som har tid, kapital och kunskap kan lättare prova nytt eller skydda sig mot risker. Den som redan lever med små marginaler får ofta bära en större del av osäkerheten. Därför behöver både möjligheter och fördelning finnas med i analysen.`
   ]},
   {heading:'Vad händer härnäst?',paragraphs:[
    d.next,
    `Det viktigaste framöver är öppen uppföljning. Nya besked bör jämföras med faktiska resultat, inte bara ambitioner. För läsaren betyder det att följa utvecklingen över tid, kontrollera ursprungskällorna och vara beredd att ompröva den första bilden.`
   ]}
  ],
  analysis:[
   `Utvecklingen visar hur snabbt ett avgränsat ämne kan bli en bred samhällsfråga. Teknik, ekonomi, kultur och politik påverkar varandra, och en förändring på ett område skapar ofta oväntade följder på ett annat.`,
   `Den centrala målkonflikten står mellan snabb anpassning och uthållig kvalitet. Den som agerar tidigt kan vinna fördelar, men också låsa fast sig vid en lösning som ännu inte är prövad. Den som väntar får mer kunskap men riskerar att hamna efter.`,
   `En rimlig slutsats är därför att kombinera försiktighet med praktiska försök. Små, mätbara steg ger bättre underlag än stora löften. Transparens om kostnader, osäkerhet och vem som påverkas är avgörande för förtroendet.`
  ],
  consequences:[
   'Beslut som verkar små i dag kan få större betydelse när de upprepas över tid.',
   'Skillnader mellan grupper och platser kan öka om tillgången till resurser är ojämn.',
   'Tydliga källor och återkommande uppföljning blir viktigare än snabba bedömningar.',
   'Frågan kommer att kräva nya avvägningar mellan kvalitet, kostnad och ansvar.'
  ],
  sources:d.sources
 };
}

const drafts:Draft[]=[
 {slug:'hostmenyer-stockholm-2026',section:'Stockholmskrogar',title:'Höstens Stockholmskrogar söker värme, enkelhet och tydligare värde',intro:'När kostnaderna är höga prövas restaurangernas förmåga att ge gästen en minnesvärd kväll utan att menyn känns överlastad.',focus:'Stockholms restauranger går in i hösten med ett tydligt dubbelt tryck: gästerna vill ha kvalitet men granskar priset hårdare. Kortare menyer, fler rätter för delning och tydligare säsongsråvaror har därför blivit viktiga verktyg.',context:'Krogen är både kultur och kalkyl. Svamp, kål, rotfrukter och långkok kan skapa djup utan att varje tallrik bygger på dyra prestigeingredienser.',perspective:'Det intressanta är inte en enskild nyöppning utan hur hela krogscenen anpassar sitt erbjudande.',next:'Under hösten blir det värt att följa portionsstorlek, menypris, bokningsvillkor och hur väl restaurangerna tar hand om allergier och alkoholfria dryckesval.',sources:[{label:'Guide Michelin – Stockholm',url:'https://guide.michelin.com/se/en/stockholm-region/stockholm/restaurants'},{label:'Visit Stockholm – restauranger',url:'https://www.visitstockholm.com/eat-drink/restaurants/'}]},
 {slug:'svamp-mat-vin-host-2026',section:'Mat & vin',title:'Svampens djup möter vinets syra – så byggs höstens måltid',intro:'Ett reportage om råvaran som kan bära en hel middag och om varför vinvalet bör följa tillagningen snarare än prislappen.',focus:'Höstens svamp fungerar som mer än tillbehör. Stekning, torkning och långsam tillagning lockar fram olika nivåer av sälta, nötighet och umami, vilket gör att samma råvara kan möta både friska vita viner och lätta röda.',context:'Till en krämig svamprätt behövs ofta syra som bryter fettet. Till hårt stekt svamp kan ett lätt rött vin med måttliga tanniner fungera bättre än ett kraftigt vin.',perspective:'Mat och vin blir mest användbart när råden utgår från smak, tillagning och sällskapets behov.',next:'Kontrollera alltid aktuellt sortiment, pris och alkoholhalt. Ett torrt alkoholfritt alternativ med syra ska behandlas som ett fullvärdigt val vid bordet.',sources:[{label:'Livsmedelsverket – svamp',url:'https://www.livsmedelsverket.se/livsmedel-och-innehall/mat-och-dryck/svamp'},{label:'Systembolaget – mat och dryck',url:'https://www.systembolaget.se/dryck-till-mat/'}]},
 {slug:'stockholm-vardagsstad-2026',section:'Stockholm',title:'Stockholm efter sommaren – när vardagsstaden åter tar över',intro:'Skolor, pendling och arbetsplatser fyller staden igen. Då blir de små bristerna i trafik och service snabbt synliga.',focus:'När höstens vardag börjar samtidigt för hundratusentals människor ställs stadens system inför sitt verkliga prov. Restider, byten, skolvägar och tillgång till service betyder mer än visioner om framtida stadsdelar.',context:'Stockholm är en regional arbetsmarknad där kommungränserna sällan motsvarar människors rörelser.',perspective:'Vardagsstaden bedöms inte efter invigningar utan efter om resan, hämtningen och arbetspasset går att få ihop.',next:'Följ förseningar, kapacitet och tillgänglighet under flera veckor. Enstaka störningar säger lite, men återkommande mönster visar var investeringar behövs.',sources:[{label:'Region Stockholm – trafik och kollektivtrafik',url:'https://www.regionstockholm.se/verksamhet/kollektivtrafik/'},{label:'Stockholms stad – trafik och gator',url:'https://trafik.stockholm/'}]},
 {slug:'kulturarbete-ai-2026',section:'Kulturdebatt',title:'När AI blir kulturarbetare måste människans ansvar bli tydligare',intro:'Den nya kulturstriden gäller inte bara upphovsrätt utan också vad publiken har rätt att veta om hur ett verk har skapats.',focus:'Generativ AI används allt oftare för idéarbete, översättning, bild, ljud och redigering. Verktygen kan sänka trösklar men skapar samtidigt frågor om samtycke, ersättning och vem som står bakom ett uttryck.',context:'Kulturens värde ligger inte enbart i slutprodukten. Process, erfarenhet och avsändare påverkar hur ett verk förstås.',perspective:'Debatten blir fattig om den reduceras till teknikoptimism mot teknikrädsla.',next:'Branschen behöver tydligare märkning, avtal och redovisning av träningsdata. Publiken behöver kunna skilja mänskligt skapande, maskinstöd och helt genererat material.',sources:[{label:'EU-kommissionen – AI-förordningen',url:'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai'},{label:'PRV – upphovsrätt',url:'https://www.prv.se/sv/upphovsratt/'}]},
 {slug:'usa-mellanarsval-vardagsfragor-2026',section:'USA',title:'USA:s mellanårsval avgörs också vid köksbordet',intro:'Bakom de nationella konflikterna finns väljarnas bedömning av priser, arbete, trygghet och framtidstro.',focus:'Inför mellanårsvalet försöker båda partierna göra nationella konflikter begripliga i vardagen. Ekonomi, migration, abort, sjukvård och presidentmakt vävs samman med kandidaternas lokala förutsättningar.',context:'USA har inget enda nationellt val utan hundratals delstats- och kongressval med olika väljargrupper och regler.',perspective:'Opinionsmätningar om presidenten räcker därför inte för att förstå mandatfördelningen.',next:'Följ kandidatrekrytering, valdeltagande, poströstning och konkurrensen i ett begränsat antal jämna distrikt. Små förskjutningar kan ändra kontrollen över kongressen.',sources:[{label:'Federal Election Commission',url:'https://www.fec.gov/'},{label:'U.S. House – valinformation',url:'https://www.house.gov/the-house-explained'}]},
 {slug:'eu-konkurrenskraft-sakerhet-2026',section:'EU',title:'EU söker en ekonomisk modell för en hårdare värld',intro:'Unionen vill stärka industri, försvar och energi samtidigt som klimatmål och statsfinanser ska hållas samman.',focus:'EU:s ekonomiska debatt kretsar kring hur investeringar kan öka utan att den inre marknaden splittras. Stora medlemsländer har större utrymme för stöd, medan mindre länder behöver gemensamma regler som hindrar en subventionskapplöpning.',context:'Säkerhetspolitik, energi och konkurrenskraft har blivit delar av samma diskussion.',perspective:'Unionens styrka är skalan, men besluten blir långsamma när kostnader och vinster fördelas olika.',next:'De kommande besluten om budget, industri och gemensam finansiering visar om medlemsländerna kan omsätta målen i faktiska investeringar.',sources:[{label:'Europeiska kommissionen – konkurrenskraft',url:'https://commission.europa.eu/topics/competitiveness_en'},{label:'Europeiska rådet',url:'https://www.consilium.europa.eu/sv/european-council/'}]},
 {slug:'analog-vardag-ny-trend-2026',section:'Nya trender',title:'Det analoga gör comeback – men mobilen försvinner inte',intro:'Papperskalendrar, enkla telefoner och fysiska möten lockar människor som vill återta kontrollen över sin uppmärksamhet.',focus:'En växande grupp försöker skapa friktion i det digitala livet. Notiser stängs av, anteckningar flyttas till papper och vissa aktiviteter görs utan telefon i rummet.',context:'Det är mindre en flykt från teknik än ett försök att välja när tekniken ska få avbryta.',perspective:'Trenden säger något om hur uppmärksamhet har blivit en knapp resurs.',next:'Det avgörande blir om vanorna håller när arbetsliv, skola och service fortsätter att kräva digital närvaro.',sources:[{label:'Internetstiftelsen – Svenskarna och internet',url:'https://svenskarnaochinternet.se/'},{label:'Folkhälsomyndigheten – psykisk hälsa',url:'https://www.folkhalsomyndigheten.se/livsvillkor-levnadsvanor/psykisk-halsa-och-suicidprevention/'}]},
 {slug:'svensk-politik-efter-valdagen-2026',section:'Politisk debatt',title:'Efter valdagen börjar den svårare uppgiften: att få makten att fungera',intro:'Mandat är början, inte slutet. Regeringsbildning och budget kräver kompromisser som partierna sällan beskriver fullt ut före valet.',focus:'När rösterna har lagts flyttas politiken från budskap till förhandling. Partier måste översätta vallöften till majoriteter, utskottsarbete och en budget som faktiskt kan genomföras.',context:'Det svenska parlamentariska systemet belönar förmågan att samarbeta men gör också ansvaret svårare att avläsa.',perspective:'Den demokratiska kvaliteten avgörs av hur öppet partierna redovisar sina kompromisser.',next:'Följ talmansrundor, budgetbesked och vilka löften som prioriteras när allt inte kan genomföras samtidigt.',sources:[{label:'Valmyndigheten',url:'https://www.val.se/'},{label:'Sveriges riksdag – så bildas regeringen',url:'https://www.riksdagen.se/sv/sa-fungerar-riksdagen/demokrati/sa-bildas-regeringen/'}]},
 {slug:'makroekonomi-vandning-2026',section:'Makroekonomi',title:'Återhämtningen syns först i statistiken och sist i hushållens trygghet',intro:'Lägre inflation räcker inte. Arbete, räntor och reala inkomster avgör när en ekonomisk vändning känns verklig.',focus:'Makroekonomin kan förbättras samtidigt som hushållen fortsätter vara försiktiga. Prisnivån ligger kvar även när inflationstakten sjunker, och arbetsmarknaden reagerar ofta senare än produktionen.',context:'Sverige påverkas samtidigt av utvecklingen i USA, euroområdet, Kina och Japan genom handel, valutor och finansiering.',perspective:'Det viktiga är inte en enskild prognos utan om flera indikatorer pekar åt samma håll.',next:'Följ sysselsättning, reallöner, konsumtion, konkurser och bostadsbyggande tillsammans. Då blir det lättare att skilja en statistisk rekyl från en bred återhämtning.',sources:[{label:'Konjunkturinstitutet',url:'https://www.konj.se/'},{label:'SCB – Sveriges ekonomi',url:'https://www.scb.se/hitta-statistik/temaomraden/sveriges-ekonomi/'}]},
 {slug:'hostens-bocker-lasning-2026',section:'Böcker',title:'Höstens läsning söker det långsamma perspektivet',intro:'När nyhetsflödet blir snabbare växer behovet av romaner och sakprosa som stannar kvar i en fråga.',focus:'Höstens bokutgivning möter en publik som både vill förstå samtiden och lämna den för en stund. Romanen erbjuder erfarenhet och flertydighet, medan sakprosan kan ge sammanhang åt frågor som annars passerar som rubriker.',context:'Bokhandel, bibliotek och digitala abonnemang formar vilka titlar som faktiskt når läsaren.',perspective:'Den viktigaste kulturfrågan är inte hur många böcker som ges ut utan vilka som får tid att bli lästa.',next:'Följ bibliotekens köer, kritikens bredd och om mindre förlag lyckas nå ut när uppmärksamheten koncentreras till ett fåtal titlar.',sources:[{label:'Svenska Förläggareföreningen',url:'https://forlaggare.se/'},{label:'Kungliga biblioteket – biblioteksstatistik',url:'https://www.kb.se/samverkan-och-utveckling/biblioteksstatistik.html'}]},
 {slug:'uppmarksamhet-psykologi-2026',section:'Psykologi',title:'Uppmärksamheten är inte trasig – den är överbelastad',intro:'Koncentrationsproblem handlar ofta mindre om karaktär och mer om en miljö byggd för avbrott.',focus:'Många beskriver svårigheter att läsa, arbeta eller vila utan att kontrollera en skärm. Förklaringen finns i samspelet mellan stress, sömn, vanor och en digital miljö som belönar snabb respons.',context:'Självkritik kan göra problemet värre genom att varje avbrott tolkas som ett personligt misslyckande.',perspective:'Psykologiskt hållbara förändringar börjar ofta med miljön snarare än viljestyrkan.',next:'Små experiment är mest användbara: avgränsade notistider, telefonen utanför sovrummet och tydliga perioder för ostört arbete.',sources:[{label:'1177 – stress',url:'https://www.1177.se/liv--halsa/stresshantering-och-somn/stress/'},{label:'Folkhälsomyndigheten – psykisk hälsa',url:'https://www.folkhalsomyndigheten.se/livsvillkor-levnadsvanor/psykisk-halsa-och-suicidprevention/'}]},
 {slug:'simone-weil-uppmarksamhet-2026',section:'Filosofi',title:'Simone Weil och uppmärksamheten som moralisk handling',intro:'Att verkligen se en annan människa kan vara svårare och viktigare än att snabbt formulera en åsikt.',focus:'Simone Weil beskrev uppmärksamhet som ett öppet och krävande väntande. Den som lyssnar utan att omedelbart fylla tystnaden med sin egen berättelse kan upptäcka behov som annars förblir osynliga.',context:'I dagens flöden belönas snabb reaktion, säkerhet och tydlig grupptillhörighet.',perspective:'Weils filosofi gör långsamheten till en etisk fråga, inte bara en produktivitetsmetod.',next:'Pröva hennes tanke i vardagen: läs en text färdigt, låt en annan person tala till punkt och skilj observation från omedelbar värdering.',sources:[{label:'Stanford Encyclopedia of Philosophy – Simone Weil',url:'https://plato.stanford.edu/entries/simone-weil/'},{label:'Internet Encyclopedia of Philosophy – Simone Weil',url:'https://iep.utm.edu/simone-weil/'}]},
 {slug:'valet-1976-femtio-ar-2026',section:'Historisk långläsning',title:'Valet 1976 – maktskiftet som förändrade bilden av Sverige',intro:'För 50 år sedan bröts ett mycket långt socialdemokratiskt regeringsinnehav. Händelsen visar hur makt kan skifta innan samhällets grundmönster gör det.',focus:'Riksdagsvalet 1976 ledde till ett historiskt regeringsskifte. Kärnkraft, ekonomi och frågan om långvarigt maktinnehav möttes i en valrörelse där oppositionen lyckades göra förändring möjlig utan att lova ett helt annat samhällssystem.',context:'Maktskiftet var både dramatiskt och institutionellt ordnat, vilket säger något viktigt om svensk demokratisk stabilitet.',perspective:'Fem decennier senare går det att se valet som början på en mer rörlig politisk tid.',next:'Jämför samtidens kampanjmaterial, valresultat och efterföljande regeringsbeslut. Historien blir tydligare när efterhandsbilden prövas mot dokumenten.',sources:[{label:'Valmyndigheten – historisk valstatistik',url:'https://www.val.se/valresultat/riksdag-region-och-kommun.html'},{label:'Riksarkivet',url:'https://riksarkivet.se/'}]},
 {slug:'stadstrad-varme-2026',section:'Miljö',title:'Stadsträdet har blivit klimatinfrastruktur',intro:'Skugga, svalka och vattenhantering gör träden till en praktisk del av stadens beredskap.',focus:'När täta stadsdelar blir varmare får parker, träd och genomsläpplig mark en ny roll. De är inte bara miljöer för rekreation utan system som kan dämpa värme och ta hand om kraftiga regn.',context:'Nyttan kommer långsamt eftersom stora träd tar årtionden att utveckla sina viktigaste funktioner.',perspective:'Det gör varje beslut om mark, ledningar och byggande till en fråga om framtida motståndskraft.',next:'Kommuner behöver redovisa överlevnad, krontäckning och skötsel över tid, inte bara antalet nyplanterade träd.',sources:[{label:'Naturvårdsverket – klimatanpassning',url:'https://www.naturvardsverket.se/amnesomraden/klimatanpassning/'},{label:'SMHI – klimatanpassning',url:'https://www.smhi.se/klimat/klimatanpassning'}]},
 {slug:'kvantsensorer-forskning-2026',section:'Forskning och framsteg',title:'Kvantsensorer kan bli genombrottet som märks före kvantdatorn',intro:'Extremt känsliga mätningar kan förändra medicin, navigation och geologi långt innan den universella kvantdatorn är vardag.',focus:'Kvantsensorer använder kvantmekaniska effekter för att mäta tid, gravitation, magnetfält och rörelse med mycket hög precision. Tekniken utvecklas i flera spår och vissa tillämpningar ligger närmare praktisk användning än storskalig kvantberäkning.',context:'Mätningar är en underskattad grund för tekniska språng. Bättre sensorer kan göra gamla system betydligt mer användbara.',perspective:'Den viktiga frågan är när laboratoriets precision kan bevaras i robust och rimligt prissatt utrustning.',next:'Följ oberoende tester, standardisering och verkliga pilotprojekt. Ett pressmeddelande är början på granskningen, inte beviset på ett genombrott.',sources:[{label:'Vetenskapsrådet',url:'https://www.vr.se/'},{label:'EU Quantum Technologies Flagship',url:'https://qt.eu/'}]},
 {slug:'hostresor-tag-2026',section:'Resor',title:'Höstresan börjar på perrongen – men enkelheten avgör',intro:'Nattåg och längre tågresor lockar med tid, utsikt och lägre utsläpp. Bokningen är fortfarande den svaga länken.',focus:'Tågresan har blivit en del av upplevelsen för fler resenärer, särskilt när målet är en europeisk stad eller en svensk naturdestination. Samtidigt kan flera operatörer, separata biljetter och otydliga rättigheter göra planeringen svår.',context:'Resenären jämför inte bara pris utan även restid, sovkomfort, bytesrisk och möjligheten att arbeta eller vila.',perspective:'Det hållbara alternativet vinner först när det också är begripligt och pålitligt.',next:'Kontrollera hela reskedjan, marginalen vid byten och vilka ersättningsregler som gäller när biljetterna är separata.',sources:[{label:'EU – tågresenärers rättigheter',url:'https://europa.eu/youreurope/citizens/travel/passenger-rights/rail/index_sv.htm'},{label:'Trafikverket – tågtrafik',url:'https://www.trafikverket.se/resande-och-trafik/jarnvag/'}]},
 {slug:'kulturhost-scener-skarmar-2026',section:'Kultur',title:'Kulturhösten rör sig mellan scenen, skärmen och det gemensamma rummet',intro:'Böcker, film, musik, opera, teater och tv-serier konkurrerar om samma tid men erbjuder helt olika sätt att vara publik.',focus:'Höstens kulturkonsumtion sker i ett överflöd. Premiärer och släpp avlöser varandra, medan den verkliga bristen är sammanhängande tid och gemensam uppmärksamhet.',context:'Den levande scenen erbjuder närvaro och risk. Skärmen erbjuder tillgänglighet och räckvidd. Boken erbjuder ett långsammare inre rum.',perspective:'Kulturens värde kan därför inte reduceras till publikmängd eller strömmade minuter.',next:'Följ både de stora institutionerna och de mindre scenerna. Bredden i vilka verk som får produceras avgör framtidens kultur mer än enskilda topplistor.',sources:[{label:'Kulturrådet',url:'https://www.kulturradet.se/'},{label:'Kungliga Operan',url:'https://www.operan.se/'}]},
 {slug:'veckans-reportage-somnen-2026',section:'Veckans reportage',title:'Sömnen – nattens arbete som avgör dagens liv',intro:'Varför sover vi, vad förstör sömnen och hur kan en bättre natt byggas utan att sömnen själv blir ännu ett prestationskrav?',focus:'Sömn är en aktiv biologisk process där återhämtning, minne, känsloreglering och kroppens system samspelar. Ändå behandlas natten ofta som den tid som kan beskäras när arbete, skärmar och vardagskrav tränger sig på.',context:'Problemet är att sömn inte kan beordras fram. Ju hårdare en människa försöker tvinga sig att somna, desto mer vaksam kan kroppen bli.',perspective:'Ett bättre sömnmönster byggs oftare genom regelbundenhet, dagsljus, rörelse och en lugnare kväll än genom jakten på en perfekt siffra.',next:'Den som har långvariga eller allvarliga besvär bör söka vård. För andra är en enkel sömndagbok och små förändringar under flera veckor mer informativa än en enstaka dålig natt.',sources:[{label:'1177 – sömnsvårigheter',url:'https://www.1177.se/liv--halsa/stresshantering-och-somn/somnsvarigheter/'},{label:'Folkhälsomyndigheten – sömn',url:'https://www.folkhalsomyndigheten.se/livsvillkor-levnadsvanor/psykisk-halsa-och-suicidprevention/'}]}
];

export const weekendCurrentArticles:WeekendArticle[]=drafts.map(article);
