export type WeekendFinalExtension={sections:{heading:string;paragraphs:string[]}[];conclusion:string[]};

export const weekendFinalExtensions:Record<string,WeekendFinalExtension>={
'helg-stockholmskrogar-kvarterskrogen-aterkomst':{sections:[
{heading:'Tre krogar, tre ekonomiska verkligheter',paragraphs:['En liten kvarterskrog kan bygga sin ekonomi på återkommande gäster och måttlig snittnota, men är känslig för varje tom sittning. En destinationskrog kan ta mer betalt och locka gäster längre bortifrån, men måste ständigt leva upp till höga förväntningar. En stor kedja kan pressa inköp och marknadsföring men riskerar ett mer utbytbart uttryck.','Skillnaderna påverkar menyn. Den lilla krogen behöver råvaror som kan användas i flera rätter. Destinationskrogen kan köpa exklusivare produkter men får större svinnrisk. Kedjan arbetar med standardisering för att samma rätt ska fungera oavsett personal och kväll.','För gästen betyder detta att priset måste förstås i relation till formatet. En enkel rätt kan vara prisvärd om råvara, tillagning och service håller hög nivå. En avancerad meny kan vara svag om upplevelsen inte motiverar tidsåtgången och totalnotan.']},
{heading:'En öppnare restaurangjournalistik',paragraphs:['Helg ska ange när ett omdöme bygger på ett redaktionellt besök och när artikeln sammanfattar verifierade menyer, guider och offentliga uppgifter. Den skillnaden är central för läsarens förtroende.','Recensionen bör följa upp förändring. En ny kökschef, kraftigt ändrade priser eller nytt koncept kan göra ett äldre omdöme missvisande. Därför dateras bedömningen och länkas till restaurangens aktuella information.','Krogens roll i stadsdelen ska också beskrivas. Tillgänglighet, öppettider, ljudnivå och möjlighet att äta utan en lång förbokning avgör om platsen fungerar som kvarterskrog eller främst som destination.']}],
conclusion:['Stockholmskrogen måste bedömas som matupplevelse, arbetsplats och lokal institution.','Prisvärde handlar om helheten och inte om låg kostnad i sig.','Återkommande uppföljning gör recensionen mer rättvis än en permanent topplista.']},
'helg-mat-smak-forst-mindre-svinn':{sections:[
{heading:'Från inköpslista till färdig måltid',paragraphs:['Planeringen börjar med att inventera kyl, frys och skafferi. Därefter väljs måltider som använder de känsligaste råvarorna först. En inköpslista byggd på det som saknas blir kortare och minskar risken för dubbla köp.','Tillagningen kan organiseras så att ugn och spis används effektivt. Flera plåtar kan rostas samtidigt och en gryta kan ge bas till mer än en rätt. Det sparar energi och tid utan att maten behöver serveras likadant.','Efter måltiden avgör förpackning och datum om resterna blir resurs eller avfall. Små genomskinliga kärl, tydlig märkning och en bestämd restdag skapar ett system som fungerar även när veckan blir stressig.']},
{heading:'När hälsa, ekonomi och klimat möts',paragraphs:['De tre målen sammanfaller ofta men inte alltid. En billig måltid kan vara näringsmässigt svag, en hälsosam råvara kan ha hög klimatpåverkan och ett klimatsmart alternativ kan vara svårt att hitta i hela landet.','Därför bör råd beskriva kompromisser. Baljväxter, fullkorn och säsongsgrönsaker är ofta starka på flera mått, men individuella behov, allergier och kulturella matvanor måste räknas in.','Den bästa vardagsförändringen är den som kan upprepas. Ett ambitiöst schema som överges efter två veckor ger mindre effekt än några stabila rätter som hushållet verkligen tycker om.']}],
conclusion:['Bra matplanering börjar med befintliga råvaror.','Hållbarhet behöver väga samman hälsa, kostnad, klimat och genomförbarhet.','Små bestående vanor är viktigare än korta perioder av perfektion.']},
'helg-vin-syra-struktur-mat':{sections:[
{heading:'Så byggs en vinlista för hemmet',paragraphs:['Ett litet grundsortiment kan täcka många middagar: ett friskt vitt, ett fylligare vitt, ett lätt rött, ett strukturerat rött och ett torrt alkoholfritt alternativ. Det är mer användbart än flera flaskor med samma smakprofil.','Förvaring ska vara mörk, sval och stabil. Flaskor som ska drickas inom kort behöver ingen avancerad vinkällare, men värme och stora temperaturväxlingar försämrar kvaliteten. Öppnade flaskor håller längre med kyla och så liten luftkontakt som möjligt.','Inköpet blir mer träffsäkert när varje flaska har ett tänkt användningsområde. Att köpa enbart efter rabatt eller poäng riskerar ett skåp fullt av vin som inte passar den mat man faktiskt lagar.']},
{heading:'Restaurangens vinpaket under lupp',paragraphs:['Ett vinpaket ska tillföra något till rätterna och inte bara höja notan. Gästen bör få veta mängd, antal glas och om alkoholfria parningar erbjuds med samma omsorg.','Påslaget finansierar lager, glas, personal och risken att öppnade flaskor inte säljs. Men en hög marginal behöver motsvaras av kunskap, temperatur, servering och ett urval som gästen inte enkelt får hemma.','Helgs granskning kommer därför att bedöma kombinationen, informationen och totalpriset. Ett billigare vin kan vara det bästa valet om det är skickligare matchat.']}],
conclusion:['Ett genomtänkt litet sortiment är bättre än många slumpmässiga flaskor.','Vinpaket ska bedömas efter matmatchning och totalvärde.','Alkoholfria parningar ska få samma redaktionella uppmärksamhet.']},
'helg-stockholm-staden-mellan-barn-och-aldre':{sections:[
{heading:'Investeringarna som låser framtiden',paragraphs:['Tunnelbana, vägar, skolor och sjukhus har lång livslängd. Beslut som fattas med dagens prognos påverkar invånare långt efter att befolkningsutvecklingen förändrats. Därför måste stora projekt prövas mot flera scenarier.','Etappindelning kan minska risken. Kapacitet byggs då ut när behovet bekräftas, men mark och anslutningar reserveras från början. Metoden kräver politisk disciplin eftersom den synliga invigningen kommer senare.','Underhåll konkurrerar samtidigt med nya projekt. En ny anläggning är lättare att presentera än renovering, men eftersatt underhåll kan ge större framtida kostnader och plötsliga avbrott.']},
{heading:'Vardagsstaden som mått',paragraphs:['Restid bör mätas från dörr till dörr och inte bara som minuter på tåget. Byten, gångväg, trängsel och pålitlighet avgör om kollektivtrafiken är ett realistiskt alternativ.','Tillgång till service handlar om mer än avstånd. Öppettider, språk, digitala krav och fysisk tillgänglighet kan göra en närliggande verksamhet svår att använda.','Stockholmspolitiken behöver därför komplettera stora tillväxttal med konkreta vardagsmått. När utvecklingen redovisas stadsdel för stadsdel blir det tydligare vilka investeringar som faktiskt förbättrar människors liv.']}],
conclusion:['Långlivade investeringar måste klara flera demografiska scenarier.','Underhåll är en central del av tillväxtpolitiken.','Vardagens tillgänglighet är ett bättre framgångsmått än enbart befolkningsökning.']},
'helg-kulturdebatt-vem-far-ta-plats':{sections:[
{heading:'Kanon, kvalitet och urval',paragraphs:['Varje kulturinstitution gör ett urval. En kanon kan ge gemensamma referenser och bevara verk, men kan också göra historiska maktförhållanden till norm. Debatten bör handla om hur urvalet görs och hur det kan omprövas.','Kvalitet är inte helt subjektiv. Hantverk, originalitet, sammanhang och verkan kan diskuteras med argument. Men bedömningen sker alltid från en position och behöver möta andra perspektiv.','Att lägga till nya röster innebär inte nödvändigtvis att äldre verk försvinner. Ett bredare samtal kan i stället förändra hur klassiker läses och vilka frågor som ställs till dem.']},
{heading:'Kritikens försvagade ekonomi',paragraphs:['När redaktioner minskar kulturbevakningen blir recensionerna färre och lanseringsmaterial får större utrymme. Det försvagar den oberoende mellanhand som hjälper publiken att värdera utbudet.','Frilansande kritiker arbetar ofta under stor tidspress. Kortare texter kan vara skarpa, men komplexa verk behöver ibland utrymme för referat, kontext och invändning.','Helg ska därför ge kritik plats utan krav på omedelbar konflikt. En recension får gärna vara tydlig, men tydlighet ska komma från argument och exempel, inte från överdrift.']}],
conclusion:['Kulturens urval måste kunna både bevara och ompröva.','Kvalitetsomdömen blir trovärdiga genom argument, inte auktoritet.','Oberoende kritik är en del av kulturens infrastruktur.']},
'helg-usa-mellanarsvalet-som-maktprov':{sections:[
{heading:'Representanthuset och senaten fungerar olika',paragraphs:['Alla mandat i representanthuset väljs vartannat år, vilket gör kammaren känslig för nationella opinionssvängningar. Senatens sexåriga mandat och rullande val ger större kontinuitet men också en karta som varierar mellan valen.','En knapp majoritet kan få svårt att hålla ihop i kontroversiella frågor. Enstaka ledamöter får större förhandlingsmakt och utskottsordföranden kan styra vilka förslag och utredningar som går vidare.','Presidenten behåller betydande verkställande makt även med en fientlig kongress, men budget, lagstiftning och utnämningar kan bromsas. Konflikten flyttar då ofta till domstolar och myndighetsbeslut.']},
{heading:'Vad omvärlden bör följa',paragraphs:['Utrikespolitik påverkas inte alltid snabbt av ett mellanårsval, men finansiering och tillsyn kan förändras. Stöd till allierade, sanktioner och försvarsbudget blir möjliga konfliktpunkter.','Marknader följer särskilt risken för budgetstopp, skuldtakskonflikter och förändrade skatter. Ett delat styre kan stoppa stora reformer men också öka osäkerheten kring nödvändiga beslut.','För Europa är USA:s långsiktiga åtaganden viktigare än en enskild kampanjfras. Analysen måste skilja retorik, presidentens befogenheter och beslut som kräver kongressens stöd.']}],
conclusion:['Kongressens två kamrar skapar olika maktbalanser.','En liten majoritet kan vara formellt stark men praktiskt instabil.','Omvärlden bör följa budget och institutionella beslut snarare än enbart kampanjretorik.']},
'helg-eu-tillvaxt-utan-fart':{sections:[
{heading:'Den inre marknaden som ofullbordat projekt',paragraphs:['Varor rör sig relativt fritt, men tjänster, kapital och digital verksamhet möter fortfarande nationella hinder. Det begränsar företagens möjlighet att växa över hela unionen och minskar konkurrensen.','Gemensamma regler kan sänka kostnaden när de ersätter 27 system. Men regler kan också bli en börda om de läggs ovanpå nationella krav eller tolkas olika. Genomförandet är därför lika viktigt som lagtexten.','Små företag har minst resurser att hantera skillnaderna. Förenkling bör mätas i faktisk tid och kostnad för företag, inte i antalet initiativ som kommissionen presenterar.']},
{heading:'Arbetskraft, migration och demografi',paragraphs:['Många EU-länder får en äldre befolkning och färre personer i arbetsför ålder. Produktivitet, längre arbetsliv och migration blir tre möjliga svar, men vart och ett kräver politiska val.','Arbetskraftsinvandring fungerar bäst när utbildning erkänns, språk kan läras och bostäder finns nära jobb. Utan integration riskerar både ekonomisk potential och politiskt stöd att gå förlorade.','Fri rörlighet kan fylla brist i ett land men skapa kompetensflykt i ett annat. En gemensam marknad behöver därför också investeringar i de regioner som förlorar unga och utbildade.']}],
conclusion:['Den inre marknadens återstående hinder är främst praktiska och nationella.','Demografin gör arbetskraft och produktivitet till långsiktiga kärnfrågor.','Fri rörlighet skapar vinster men också regionala kostnader som måste hanteras.']},
'helg-nya-trender-ai-blir-osynlig':{sections:[
{heading:'AI och den professionella identiteten',paragraphs:['När en modell kan göra ett första utkast förändras vad det innebär att vara skicklig. Värdet flyttas mot problemformulering, urval, kontroll och ansvar för slutresultatet.','Nybörjare kan producera mer men riskerar att missa fel som en erfaren person ser. Samtidigt kan experter tappa färdighet om de alltid accepterar automatiska förslag. Organisationen behöver därför planera hur kompetens ska tränas.','Yrkesstolthet kan påverkas när arbetet reduceras till att godkänna maskinens text. Ett bra införande låter tekniken ta repetitiva delar och bevarar meningsfullt omdöme hos människan.']},
{heading:'Den nya informationsmiljön',paragraphs:['Billig generering gör det möjligt att skapa stora mängder trovärdig text, bild och ljud. Problemet blir mindre att producera information och mer att fastställa ursprung, ansvar och tillförlitlighet.','Märkning kan hjälpa men är inte fullständig. Metadata kan försvinna och bedragare följer inte regler. Källkritik behöver därför kombineras med teknisk proveniens och kända publiceringskedjor.','Redaktioner måste vara öppna med när AI används, vilka delar som kontrollerats av människor och hur rättelser görs. Förtroende byggs genom process, inte genom ett allmänt påstående om ansvar.']}],
conclusion:['AI förändrar yrkesrollen lika mycket som produktionshastigheten.','Kompetensförlust är en risk som måste mätas.','Tillförlitlig information kräver spårbar publiceringskedja och tydligt ansvar.']},
'helg-politisk-debatt-loften-och-finansiering':{sections:[
{heading:'Reformens juridiska väg',paragraphs:['Ett politiskt löfte kan kräva utredning, remiss, lagrådsgranskning, riksdagsbeslut och myndighetsföreskrifter. Varje steg kan ändra innehållet och tidsplanen.','EU-rätt, grundlag och kommunalt självstyre begränsar ibland vad regeringen kan göra ensam. Ett förslag som bortser från rättsliga nivåer riskerar att fastna även om pengar finns.','Den seriösa granskningen bör därför fråga vilka beslut som krävs och om berörda aktörer har hörts. Genomförandet börjar långt före den dag en lag träder i kraft.']},
{heading:'När reformen möter verkligheten',paragraphs:['En reform kan ge andra beteenden än avsett. Ett bidrag kan höja efterfrågan och priset, ett förbud kan flytta verksamhet och en ny skatt kan ändra investeringar. Sådana reaktioner måste ingå i analysen.','Pilotprojekt kan visa praktiska problem men behöver vara tillräckligt representativa. Ett framgångsrikt försök i en liten kommun går inte automatiskt att skala till hela landet.','Efter införandet ska data publiceras även om resultatet går emot regeringens förväntan. Rättelse och omprövning är tecken på fungerande politik, inte automatiskt på misslyckande.']}],
conclusion:['Juridisk genomförbarhet är lika viktig som politisk vilja.','Beteendeeffekter kan förändra både kostnad och resultat.','Öppen utvärdering ska planeras innan reformen startar.']},
'helg-makroekonomi-fem-ekonomier':{sections:[
{heading:'Produktivitet, löner och levnadsstandard',paragraphs:['Produktivitet beskriver hur mycket värde som skapas per arbetad timme. På lång sikt avgör den utrymmet för högre reallöner, men fördelningen mellan arbete och kapital påverkar vem som får vinsten.','AI-investeringar kan höja produktiviteten, men effekten kräver organisation, el, data och kompetens. Stora utgifter på teknik är inte samma sak som ett mätbart produktivitetslyft.','I tjänstesektorer som vård och utbildning är produktivitet svårare att mäta. Fler behandlade patienter kan vara effektivitet eller försämrad kvalitet beroende på resultatet.']},
{heading:'Skulden efter räntevändningen',paragraphs:['När gamla lån läggs om till högre ränta ökar kostnaden gradvis för stater, företag och hushåll. Effekten kan fortsätta även efter att centralbanken slutat höja eftersom hela skuldstocken inte refinansieras samtidigt.','Hög skuld är inte automatiskt ohållbar. Tillväxt, ränta, valuta och vem som äger skulden spelar roll. Men stort ränteutrymme minskar möjligheten att finansiera försvar, välfärd och investeringar.','För Kina är lokala myndigheter och fastighetsrelaterad skuld central. För USA är federal skuld och obligationsmarknad viktig. I Sverige ligger en stor del av räntekänsligheten hos hushållen.']}],
conclusion:['Produktivitet måste översättas till reallön och kvalitet för att märkas i vardagen.','Skuldens struktur är viktigare än en enda totalsiffra.','Ränteeffekter kommer med olika fördröjning i de fem ekonomierna.']},
'helg-bocker-lasning-som-motstand':{sections:[
{heading:'Hur en bok blir synlig',paragraphs:['Förlag, bokhandel, bibliotek, medier och sociala plattformar påverkar vilka titlar läsaren möter. Ett stort utbud betyder inte automatiskt mångfald om uppmärksamheten koncentreras till ett fåtal lanseringar.','Algoritmiska rekommendationer kan hjälpa läsaren hitta smala böcker men tenderar också att förstärka tidigare val. Mänsklig kuratering kan bryta mönstret och placera verk i ett oväntat sammanhang.','Litteraturkritiken har därför en upptäckande uppgift. Den ska inte bara recensera de böcker som redan har störst marknadsföring.']},
{heading:'Att läsa tillsammans',paragraphs:['Bokcirkeln gör läsningen social utan att alla behöver tolka verket lika. Skillnader i erfarenhet visar detaljer som en ensam läsare kan missa.','Ett bra samtal skiljer mellan vad texten faktiskt gör och vilka associationer den väcker. Båda är värdefulla, men de är olika slags påståenden.','Skolor och bibliotek kan använda gemensam läsning för att bygga språk och demokratisk samtalsförmåga. Samtalet behöver tid och en miljö där oenighet inte behandlas som misslyckande.']}],
conclusion:['Synlighet är en egen maktfråga på bokmarknaden.','Oberoende urval behövs för att bredda läsningen.','Gemensam läsning tränar både tolkning och respektfull oenighet.']},
'helg-psykologi-oro-och-kontroll':{sections:[
{heading:'Barn, unga och oro',paragraphs:['Barns oro kan synas som magont, sömnproblem, irritation eller undvikande snarare än som tydliga ord. Vuxna behöver lyssna utan att omedelbart ge långa förklaringar eller lova att inget svårt kan hända.','Rutiner och förutsägbarhet kan skapa trygghet, men barnet behöver också gradvis få erfarenhet av att klara osäkerhet. Anpassningen ska vara varsam och ta hänsyn till ålder och situation.','När oro påverkar skola, relationer, sömn eller vardagsfunktion under längre tid bör elevhälsa eller vård kontaktas. Skuld ska aldrig läggas på barnet eller familjen.']},
{heading:'Arbetslivets oro',paragraphs:['Otydliga roller, låg kontroll och oförutsägbara krav kan skapa långvarig stress. Individuella avslappningsråd räcker inte när problemet finns i arbetsorganisationen.','Chefer behöver skilja tillfälliga arbetstoppar från en permanent obalans mellan krav och resurser. Prioriteringar måste innebära att något väljs bort, inte bara att nya uppgifter rangordnas.','Medarbetaren kan dokumentera belastning och söka stöd, men arbetsgivaren har ansvar för arbetsmiljön. Psykologisk kunskap får inte användas för att göra strukturella problem privata.']}],
conclusion:['Oro uttrycks olika hos barn och vuxna.','Stöd ska kombineras med gradvis förmåga att tåla osäkerhet.','Arbetsrelaterad stress kräver ofta organisatoriska förändringar.']},
'helg-filosofi-vad-ar-ett-gott-liv':{sections:[
{heading:'Rättvisa mellan generationer',paragraphs:['Dagens beslut om klimat, skuld och infrastruktur påverkar människor som ännu inte kan rösta. Frågan är hur deras intressen ska vägas mot dagens behov och rättigheter.','En strikt likabehandling över tid är omöjlig eftersom teknik, befolkning och resurser förändras. Men den nuvarande generationen kan undvika att lämna kostnader utan motsvarande tillgångar eller handlingsutrymme.','Försiktighetsprincipen ger skäl att undvika irreversibel skada, men kan inte stoppa all utveckling. Den måste kombineras med proportionalitet och kunskap.']},
{heading:'Teknik och människovärde',paragraphs:['När människor bedöms genom data finns en risk att det mätbara ersätter hela personen. Effektiva beslut kan ändå vara orättvisa om individen inte kan förstå eller bestrida dem.','Människovärde betyder att vissa intressen inte får reduceras till ekonomisk nytta. Samtidigt kräver offentlig politik prioriteringar när resurser är begränsade.','Filosofin hjälper oss att se var gränsen bör gå: vilka beslut kan optimeras, vilka kräver individuellt omdöme och vilka rättigheter får aldrig göras beroende av effektivitet.']}],
conclusion:['Framtida generationer behöver representeras i dagens beslut.','Irreversibla risker kräver särskild försiktighet.','Människan får inte reduceras till den data som är lättast att mäta.']},
'helg-historia-skotten-i-sarajevo':{sections:[
{heading:'Sverige och neutraliteten',paragraphs:['Sverige stod utanför kriget men påverkades av handel, blockader och livsmedelsbrist. Neutraliteten krävde diplomati gentemot båda sidor och skapade konflikter om export och försörjning.','Bristen ledde till köer, ransonering och politisk oro. Hungerkravallerna 1917 visade att ett land kunde skakas djupt av världskriget utan att själv delta militärt.','Krigsåren sammanföll med Sveriges demokratisering. Social oro, internationella revolutioner och politiska förhandlingar ökade trycket för parlamentarism och allmän rösträtt.']},
{heading:'Minnet av 1914',paragraphs:['Eftervärlden har ofta sökt en skyldig stat eller ledare. Historiker har i stället visat hur ansvar kan vara ojämnt fördelat men ändå delas av flera aktörer och beslut.','Minneskulturen skiljer sig mellan länder. I Storbritannien och Frankrike är västfrontens förluster centrala, medan östra Europas erfarenhet också handlar om revolution, nya gränser och imperiers sammanbrott.','Att studera 1914 är inte att leta efter en enkel mall för nutiden. Värdet ligger i att förstå eskalering, missbedömning och hur institutioner kan förlora kontrollen över en kris.']}],
conclusion:['Även neutrala Sverige förändrades av krigets ekonomi och politik.','Minnet av kriget ser olika ut beroende på nationell erfarenhet.','Historiska analogier är användbara först när skillnaderna också redovisas.']}
};
