export type WorldLongRead = {
  eyebrow: string;
  title: string;
  lead: string;
  news: string[];
  analysis: string[];
  depth: string[];
  sources: { label: string; href: string }[];
};

export const worldLongReads: WorldLongRead[] = [
{
 eyebrow:'USA–Iran · Säkerhet och energi',title:'USA och Iran i den kraftigaste upptrappningen på flera veckor',lead:'Nya amerikanska anfall och iranska motangrepp har åter flyttat konflikten närmare Gulfstaterna och världens viktigaste oljeled.',news:['USA:s militär uppger att den senaste vågen riktades mot luftförsvar, radar, marina resurser, minläggningsförmåga och kommunikation. Iran svarade mot amerikanska mål i Jordanien, Bahrain och Irak.','Sjöfarten genom Hormuz har samtidigt återhämtat sig delvis. Omkring 17 miljoner fat råolja passerade under måndagen, enligt USA:s energiminister, men attacker mot tankfartyg visar att leden fortfarande är utsatt.'],analysis:['Den omedelbara risken är en spiral där varje begränsad attack besvaras bredare. Gulfstaterna dras närmare konflikten när amerikanska baser och transportleder på deras territorier blir mål.','Energimarknaden reagerar inte bara på faktisk brist utan på risken för avbrott. Därför kan försäkringar, frakt och lagerhållning förbli dyra även när fartyg passerar.'],depth:['Hormuz är svårt att ersätta eftersom stora exportvolymer från Gulfregionen passerar en smal vattenväg. Alternativa rörledningar täcker bara en del av kapaciteten.','Diplomati måste därför både minska det militära våldet och skapa praktiska garantier för sjöfarten. Ett tillfälligt lugn utan övervakning förblir skört.'],sources:[{label:'Reuters – US military completed latest wave of strikes',href:'https://www.reuters.com/world/middle-east/us-military-says-it-completed-latest-wave-strikes-iran-2026-09-02/'},{label:'Reuters – 17 million barrels crossed Hormuz',href:'https://www.reuters.com/business/energy/us-energy-secretary-says-17-million-barrels-oil-transited-strait-hormuz-monday-2026-09-02/'}]
},
{
 eyebrow:'Ukraina · Kriget',title:'Kyiv angrips för sjunde dagen i rad',lead:'Ryska drönare fortsätter att slå mot huvudstadsregionen samtidigt som attacker mot energisystemet ökar trycket inför vintern.',news:['Elva människor skadades när bostäder och ett universitet i Kyiv träffades. I Odesa slogs elinfrastruktur ut och omkring 350 000 hushåll blev utan ström, enligt ukrainska uppgifter.','Larmen påverkar kollektivtrafik, undervisning och myndighetsarbete. Ukraina planerar att justera varningssystem och trafikregler för att vardagen ska fungera under återkommande attacker.'],analysis:['Den långa serien av anfall tyder på ett försök att nöta ned både luftförsvar och civilsamhälle. Varje drönare är billigare än många av robotarna som används för att skjuta ned den.','Energimålen pekar fram mot vintern. Även reparerbara skador kan bli strategiska om reservdelar, personal och luftvärn överbelastas samtidigt.'],depth:['Ukrainas problem är inte bara antalet luftvärnssystem utan tillgången på ammunition och förmågan att prioritera mellan städer, elnät och front.','Tysk-ukrainsk samproduktion av drönare och robotar kan stärka kapaciteten, men den förändrar inte läget om produktionen inte kan skalas snabbt.'],sources:[{label:'Reuters – Russia torments Kyiv with seventh day of strikes',href:'https://www.reuters.com/world/europe/russian-attacks-damage-infrastructure-ukraines-odesa-official-says-2026-09-02/'},{label:'Reuters – Ukraine and Germany finalise drone deal',href:'https://www.reuters.com/business/aerospace-defense/ukraine-is-finalising-drone-deal-with-germany-zelenskiy-says-2026-09-02/'}]
},
{
 eyebrow:'Nepal · Klimat och katastrof',title:'Räddare försöker nå arbetare instängda i kraftverkstunnlar',lead:'En vecka efter Himalayakatastrofen finns det fortfarande hopp om människor i torra utrymmen under vattenkraftverk, men räddningsarbetet är extremt svårt.',news:['Översvämningen efter en glaciärkollaps har dödat över 1 200 människor och lämnat tusentals saknade enligt de senaste myndighetsuppgifterna som Reuters redovisar.','Räddare pumpar syre mot möjliga torra kammare och får stöd från flera länder. Lera, rasrisk och enorma mängder bråte bromsar arbetet.'],analysis:['Katastrofen visar hur vattenkraft, vägar och samhällen i branta dalgångar kan drabbas samtidigt. När infrastrukturen förstörs försvåras även själva räddningen.','Dödstal och antal saknade förändras snabbt. Uppgifterna måste därför behandlas som preliminära och kopplas till tydligt angivna tidpunkter.'],depth:['Glaciärsjöar och instabila ismassor kräver gränsöverskridande varningssystem, eftersom vattenflöden inte följer nationsgränser.','Återuppbyggnaden behöver ompröva placering och dimensionering av kraftverk, broar och bosättningar i stället för att bara ersätta det som förstörts.'],sources:[{label:'Reuters – Nepal rescuers race to reach survivors',href:'https://www.reuters.com/business/environment/hopes-finding-survivors-dim-week-after-catastrophic-nepal-flood-2026-09-02/'},{label:'Reuters – Officials see chance trapped workers are alive',href:'https://www.reuters.com/world/china/good-chance-that-trapped-workers-are-still-alive-nepal-hydropower-plant-official-2026-09-02/'}]
},
{
 eyebrow:'USA–Kina · Rymdsäkerhet',title:'USA och Kina rustar för en möjlig konflikt i rymden',lead:'Teknik som kan manövrera, störa och närma sig andra satelliter gör omloppsbanan till en allt viktigare militär arena.',news:['Båda länderna utvecklar hemliga rymdfarkoster, manövrerbara satelliter och system för störning, övervakning och närkontakt i omloppsbana.','Teknik för reparation och tankning kan ha civila syften men också användas för att flytta eller oskadliggöra en motståndares satellit.'],analysis:['Militära och civila system delar samma miljö. Ett angrepp mot navigation eller kommunikation kan påverka banker, transporter, väderprognoser och räddningstjänst långt från slagfältet.','Den dubbla användningen gör avsikter svåra att bedöma. En servicefarkost kan uppfattas som ett vapen, vilket ökar risken för missförstånd.'],depth:['Rymdskrot gör fysiska angrepp farliga även för angriparen. Därför kan störning, cyberangrepp och tillfällig bländning bli mer sannolika verktyg.','Internationella regler ligger efter tekniken. Transparens kring närmanden och säkra avstånd kan bli lika viktigt som traditionell vapenkontroll.'],sources:[{label:'Reuters Insight – US and China arm for space warfare',href:'https://www.reuters.com/world/asia-pacific/us-china-arm-space-warfare-hunter-satellites-orbital-weapons-2026-09-02/'}]
},
{
 eyebrow:'Arktis · Grönland',title:'Danmark skickar värnpliktiga till Grönland',lead:'Den första större värnpliktsinsatsen i modern tid markerar att Arktis har blivit en konkret försvarsfråga för Danmark och Nato.',news:['Danska värnpliktiga deltar i arktisk utbildning och övningen Arctic Endurance inom Natos nya arktiska närvaro.','Insatsen följer ökade danska försvarsinvesteringar och återkommande amerikanskt intresse för Grönland, som Danmark och det grönländska självstyret har avvisat.'],analysis:['Utplaceringen är militärt begränsad men politiskt tydlig. Danmark vill visa faktisk närvaro och förmåga i ett område där Ryssland och Kina också ökar sin aktivitet.','Säkerhetspolitiken måste samtidigt förankras hos Grönlands befolkning. En förstärkning som uppfattas som styrd utifrån kan skapa nya konflikter om självbestämmande.'],depth:['Arktiska operationer kräver logistik, kommunikation och uthållighet i extremt klimat. Antalet soldater säger mindre än förmågan att försörja och leda dem.','Klimatförändringen öppnar längre sjöfartssäsonger och tillgång till resurser, vilket gör regionen mer ekonomiskt och militärt omstridd.'],sources:[{label:'Reuters – Denmark sends conscripts to Greenland',href:'https://www.reuters.com/world/denmark-sends-conscripts-greenland-arctic-tensions-grow-2026-09-02/'}]
},
{
 eyebrow:'Malta · Pressfrihet och rättsstat',title:'Affärsman frias från anklagelser om journalistmord',lead:'Yorgen Fenech har friats från anklagelser om att ha beställt mordet på Daphne Caruana Galizia, men rättsprocessens slut avslutar inte frågorna om Maltas institutioner.',news:['Juryn friade Fenech från medverkan till mord och deltagande i en kriminell sammanslutning. Han riskerade livstids fängelse om han hade dömts.','Tre personer som utförde mordet och andra med koppling till bomben har tidigare dömts. Caruana Galizias familj uttryckte besvikelse efter friandet.'],analysis:['En friande dom innebär att åtalet inte bevisades, inte att journalistens granskningar saknade betydelse. Rättssäkerheten kräver att den skillnaden hålls tydlig.','Fallet har blivit en europeisk symbol för riskerna när ekonomisk och politisk makt möter svaga kontrollinstitutioner och utsatta grävjournalister.'],depth:['Det långsiktiga måttet på ansvar är om staten skyddar journalister, utreder hot och gör offentliga beslutsvägar transparenta.','EU:s verktyg är främst politiska, rättsliga och ekonomiska. De fungerar bara om uppföljningen fortsätter även efter att den mest uppmärksammade rättegången är avslutad.'],sources:[{label:'Reuters – Malta court acquits businessman',href:'https://www.reuters.com/world/malta-court-acquits-businessman-car-bomb-murder-anti-corruption-journalist-2026-09-02/'},{label:'Reuters – Jury clears Fenech after two-month trial',href:'https://www.reuters.com/business/media-telecom/jury-considers-verdict-trial-over-killing-maltese-journalist-2026-09-02/'}]
}
];
