import Link from 'next/link';
import StockholmDiscovery from './StockholmDiscovery';
import { stockholmArticles163 } from '../../content/stockholmArticles163';
import { stockholmDistricts175 } from '../../content/stockholmDistricts175';
import { stockholmFront176, stockholmFrontRules176 } from '../../content/stockholmFront176';
import { stockholmTraffic168, stockholmTrafficEditorialRules168 } from '../../content/stockholmTraffic168';
import { stockholmHousingProjects170, stockholmHousingDesk170 } from '../../content/stockholmHousing170';
import { stockholmBusinessStories172, stockholmBusinessDesk172 } from '../../content/stockholmBusiness172';
import { stockholmCultureItems171, stockholmCultureDesk171 } from '../../content/stockholmCulture171';
import { stockholmSafetyStories174, stockholmSafetyDesk174 } from '../../content/stockholmSafety174';

export const metadata={title:'Stockholm | NackaSidan 2026',description:'Nyheter, trafik, politik, bostäder, kultur, näringsliv och stadsdelar i Stockholm.'};
const nav=[{label:'Senaste',anchor:'senaste'},{label:'Sök',anchor:'hitta'},{label:'Trafik',anchor:'stockholm-traffic'},{label:'Stadsdelar',anchor:'stadsdelar'},{label:'Bostäder',anchor:'stockholm-housing'},{label:'Näringsliv',anchor:'stockholm-business'},{label:'Kultur',anchor:'stockholm-culture'},{label:'Trygghet',anchor:'stockholm-safety'}];
function EmptyState({text}:{text:string}){return <p className="mt-3 rounded-lg bg-neutral-100 p-4 text-sm leading-6 text-neutral-600">{text}</p>}
function MiniCard({eyebrow,title,text,href}:{eyebrow:string,title:string,text?:string,href?:string}){return <article className="rounded-lg border border-neutral-200 p-4"><div className="text-xs font-bold uppercase tracking-wide text-neutral-500">{eyebrow}</div><h3 className="mt-2 text-lg font-black leading-snug">{href?<a className="hover:underline" href={href}>{title}</a>:title}</h3>{text?<p className="mt-2 text-sm leading-6 text-neutral-600">{text}</p>:null}{href?<a className="mt-3 inline-block text-sm font-bold underline underline-offset-4" href={href}>Öppna källan →</a>:null}</article>}

export default function StockholmPage(){
 const published=stockholmArticles163.filter(a=>a.status==='published');const lead=published.find(a=>a.homepage?.role==='lead')??published[0];const latest=[...published].sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,5);
 const searchDocuments=published.map(a=>({id:a.slug,title:a.title,summary:a.teaserSummary??a.intro,tags:a.tags,section:a.section,url:`/stockholm/artikel/${a.slug}`,publishedAt:a.publishedAt,status:a.status,districts:[]}));
 return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
  <header className="border-b-4 border-neutral-950 pb-7"><p className="text-sm font-semibold uppercase tracking-[.18em] text-neutral-500">NackaSidan 2026</p><div className="mt-2 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-5xl font-black tracking-tight sm:text-6xl">Stockholm</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-neutral-600">{stockholmFrontRules176.intro}</p></div><div className="text-sm text-neutral-500">Lokalt · Källmärkt · Tidsstämplat</div></div></header>
  <nav className="flex gap-5 overflow-x-auto border-b border-neutral-200 py-4 text-sm font-semibold">{nav.map(i=><a key={i.label} href={`#${i.anchor}`} className="whitespace-nowrap hover:underline">{i.label}</a>)}</nav>
  {lead&&<section id="senaste" className="grid gap-8 border-b border-neutral-300 py-9 lg:grid-cols-[2fr_1fr]"><article><p className="text-sm font-bold uppercase tracking-wide text-neutral-500">{lead.section}</p><h2 className="mt-2 max-w-4xl text-4xl font-black leading-tight sm:text-5xl"><Link href={`/stockholm/artikel/${lead.slug}`}>{lead.title}</Link></h2><p className="mt-4 max-w-3xl text-xl leading-8 text-neutral-600">{lead.intro}</p><div className="mt-5 flex gap-4 text-sm text-neutral-500"><span>{lead.published}</span><span>{lead.readingTime}</span></div><Link className="mt-6 inline-block font-bold underline underline-offset-4" href={`/stockholm/artikel/${lead.slug}`}>Läs hela artikeln</Link></article><aside className="border-t border-neutral-300 pt-5 lg:border-l lg:border-t-0 lg:pl-7 lg:pt-0"><h3 className="text-xl font-black">Senaste verifierat</h3><div className="mt-4 space-y-4">{latest.map(a=><Link key={a.slug} href={`/stockholm/artikel/${a.slug}`} className="block border-t border-neutral-200 pt-3 first:border-t-0 first:pt-0"><div className="text-xs font-bold uppercase text-neutral-500">{a.section}</div><div className="mt-1 font-bold leading-snug hover:underline">{a.teaserTitle??a.title}</div><div className="mt-1 text-xs text-neutral-500">{a.published}</div></Link>)}</div></aside></section>}
  <div id="hitta"><StockholmDiscovery documents={searchDocuments}/></div>
  <section id="stockholm-traffic" className="border-b border-neutral-300 py-9"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-neutral-500">Livebevakning</p><h2 className="text-3xl font-black">{stockholmTrafficEditorialRules168.title}</h2></div><span className="text-sm text-neutral-500">Färskhetsgräns: {stockholmTrafficEditorialRules168.freshnessMinutes} min</span></div>{stockholmTraffic168.length===0?<EmptyState text="Inga verifierade live-störningar visas just nu."/>:<div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{stockholmTraffic168.map(i=><MiniCard key={i.id} eyebrow={`${i.mode} · ${i.area}`} title={i.headline} text={i.summary} href={i.sourceUrl}/>)}</div>}</section>
  <section id="stadsdelar" className="border-b border-neutral-300 py-9"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-neutral-500">Nära dig</p><h2 className="text-3xl font-black">Stadsdel för stadsdel</h2></div><span className="text-sm text-neutral-500">Följ ditt Stockholm</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{stockholmDistricts175.map(d=><Link href={`/stockholm/stadsdel/${d.slug}`} key={d.slug} className="rounded-lg border border-neutral-200 p-4 transition hover:border-neutral-500 hover:bg-neutral-50"><h3 className="text-lg font-black">{d.name}</h3><p className="mt-2 text-sm leading-6 text-neutral-600">{d.focus.join(' · ')}</p><span className="mt-3 inline-block text-sm font-bold underline underline-offset-4">Öppna stadsdelen</span></Link>)}</div></section>
  <section className="py-9"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-wide text-neutral-500">Fyra lokala bevakningar</p><h2 className="text-3xl font-black">Staden bortom rubrikerna</h2></div><div className="grid gap-6 lg:grid-cols-2"><div id="stockholm-housing" className="border-t-4 border-neutral-950 pt-4"><h2 className="text-2xl font-black">{stockholmHousingDesk170.title}</h2><p className="mt-2 text-sm leading-6 text-neutral-600">{stockholmHousingDesk170.intro}</p>{stockholmHousingProjects170.length===0?<EmptyState text="Projektlistan fylls bara med verifierade uppgifter."/>:<div className="mt-4 grid gap-3">{stockholmHousingProjects170.map(p=><MiniCard key={p.id} eyebrow="Bostad" title={p.name}/>)}</div>}</div><div id="stockholm-business" className="border-t-4 border-neutral-950 pt-4"><h2 className="text-2xl font-black">{stockholmBusinessDesk172.title}</h2>{stockholmBusinessStories172.length===0?<EmptyState text="Inga företagsnyheter visas utan verifierad källa."/>:<div className="mt-4 grid gap-3">{stockholmBusinessStories172.map(s=><MiniCard key={s.id} eyebrow="Näringsliv" title={s.headline}/>)}</div>}</div><div id="stockholm-culture" className="border-t-4 border-neutral-950 pt-4"><h2 className="text-2xl font-black">{stockholmCultureDesk171.title}</h2>{stockholmCultureItems171.length===0?<EmptyState text="Kulturkalendern väntar på verifierade evenemang."/>:<div className="mt-4 grid gap-3">{stockholmCultureItems171.map(i=><MiniCard key={i.id} eyebrow="Kultur" title={i.title}/>)}</div>}</div><div id="stockholm-safety" className="border-t-4 border-neutral-950 pt-4"><h2 className="text-2xl font-black">{stockholmSafetyDesk174.title}</h2><p className="mt-2 text-sm leading-6 text-neutral-600">{stockholmSafetyDesk174.purpose}</p>{stockholmSafetyStories174.length===0?<EmptyState text="Trygghetsflödet visar bara verifierade händelser."/>:<div className="mt-4 grid gap-3">{stockholmSafetyStories174.map(s=><MiniCard key={s.id} eyebrow="Trygghet" title={s.headline}/>)}</div>}</div></div></section>
  <footer className="border-t border-neutral-300 py-6 text-sm text-neutral-500"><div className="flex flex-wrap items-center justify-between gap-3"><span>Källa först, tydlig tidsstämpel och skillnad mellan fakta och analys.</span><Link href="/sverige" className="font-bold underline underline-offset-4">Till Sverige →</Link></div></footer>
 </main>
}
