import Link from 'next/link';
import { getLiveNews } from '../../lib/liveNews';
import { getNewsHealth } from '../../lib/newsHealth';
import { getDeploymentIdentity } from '../../lib/deploymentIdentity';

export const revalidate = 900;

const reasonLabels: Record<string,string> = { SOURCE_DEGRADED:'En eller flera källor svarar inte', SOURCE_STALE:'En eller flera anslutna källor levererar för gammalt daterat innehåll', SOURCE_UNDATED:'En eller flera anslutna källor saknar daterat innehåll i aktuell radar', LOCAL_EMPTY:'Nacka/Lokalt saknar aktuella artiklar', RADAR_EMPTY:'Nyhetsradarn saknar aktuellt innehåll', CATEGORY_EMPTY:'En eller flera kategorier är tomma', ALL_SOURCES_DOWN:'Alla källor är nere', ALL_LOCAL_SOURCES_DOWN:'Alla Nacka/Lokalt-källor är nere', NEWS_STALE:'Den nyaste daterade artikeln är för gammal' };
const sourceStateLabels: Record<string,string> = { AKTIV:'Ansluten och färsk', GAMMAL:'Ansluten men gammal', INGEN_DATERAD_DATA:'Ansluten men saknar daterad artikel', NERE:'Källan svarar inte' };
const gateReasonLabels: Record<string,string> = { PROVENANCE_FAILED:'Production har inte godkänd deploy-proveniens.', READINESS_FAILED:'Nyhetsradarn är inte operativt redo.', HEALTH_WARNING:'Production är tillgänglig men hälsomodellen innehåller varningar.', PRODUCTION_IDENTITY_WARNING:'Production-identiteten behöver verifieras mot avsedd main-release.', ALL_CHECKS_PASSED:'Alla release-kontroller är godkända.' };
const remediationLabels: Record<string,string> = { VERIFY_DEPLOYMENT_PROVENANCE:'Verifiera Git-ref, commit och deployment-ID innan release godkänns.', OPEN_HEALTH_DIAGNOSTICS:'Öppna readiness och full health-diagnostik och åtgärda blockerande fel.', INVESTIGATE_HEALTH_WARNINGS:'Granska gamla, odaterade eller nedkopplade källor och följ utvecklingen.', VERIFY_PRODUCTION_IDENTITY:'Jämför production-identiteten med avsedd main-release.', NO_REMEDIATION_REQUIRED:'Ingen korrigerande åtgärd krävs. Fortsätt normal övervakning.' };

export default async function DriftstatusPage() {
  const radar=await getLiveNews(); const deployment=getDeploymentIdentity();
  const { unavailable,alerts,reasons,status,newestPublishedAt,newestAgeHours,staleAfterHours,sourceFreshness,staleSources,undatedSources,activeSources,downSources,sourceStaleAfterHours }=getNewsHealth(radar);
  const freshnessLabel=newestAgeHours===null?'Okänd':`${Math.round(newestAgeHours*10)/10} h`;
  const releaseStatus=!deployment.provenanceOk||status==='ÅTGÄRD'?'FAILED':status==='BEVAKA'?'BEVAKA':'VERIFIED';
  const releaseGate=releaseStatus==='FAILED'?'BLOCK':releaseStatus==='BEVAKA'?'ALLOW_WITH_WARNING':'ALLOW';
  const releaseGateReason=!deployment.provenanceOk?'PROVENANCE_FAILED':status==='ÅTGÄRD'?'READINESS_FAILED':status==='BEVAKA'?'HEALTH_WARNING':deployment.isProduction&&!deployment.isMainRef?'PRODUCTION_IDENTITY_WARNING':'ALL_CHECKS_PASSED';
  const remediationCode=releaseGateReason==='PROVENANCE_FAILED'?'VERIFY_DEPLOYMENT_PROVENANCE':releaseGateReason==='READINESS_FAILED'?'OPEN_HEALTH_DIAGNOSTICS':releaseGateReason==='HEALTH_WARNING'?'INVESTIGATE_HEALTH_WARNINGS':releaseGateReason==='PRODUCTION_IDENTITY_WARNING'?'VERIFY_PRODUCTION_IDENTITY':'NO_REMEDIATION_REQUIRED';
  const nextAction=remediationLabels[remediationCode];

  return <main style={{maxWidth:960,margin:'0 auto',padding:'72px 28px 100px'}}>
    <p style={{color:'#a61919',fontWeight:800,letterSpacing:2,fontSize:13}}>MAIN 359 · DRIFTSTATUS</p>
    <h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(48px,7vw,82px)',lineHeight:.98,margin:'12px 0 18px'}}>Nyhetsradarns status</h1>
    <p style={{fontFamily:'Georgia,serif',fontSize:20,lineHeight:1.45,maxWidth:760}}>Visuell kontroll av live-data, release-verifiering, release-gate, remediation, källhälsa och den deployment som faktiskt kör.</p>
    <nav aria-label="Driftverktyg" style={{display:'flex',flexWrap:'wrap',gap:10,marginTop:24}}>{[['/driftpanel','Öppna Driftpanelen'],['/api/release-verification','Release-verifiering API'],['/api/news-health','Visa health-JSON'],['/api/news-health/live','Liveness-probe'],['/api/news-health/ready','Readiness-probe'],['/api/incident-status','Incident-status API'],['/api/deployment','Deploy-proveniens API'],['/','Till startsidan']].map(([href,label])=><Link key={href} href={href} style={{border:'1px solid #111',padding:'10px 14px',textDecoration:'none',fontWeight:700}}>{label}</Link>)}</nav>
    <section aria-label="Release-gate" style={{marginTop:24,padding:22,border:'4px solid #111',background:releaseGate==='ALLOW'?'#eef4ec':releaseGate==='ALLOW_WITH_WARNING'?'#fff4d8':'#f7e7e7'}}><div style={{fontSize:13,fontWeight:900,letterSpacing:1.5}}>RELEASE-GATE</div><div style={{fontFamily:'Georgia,serif',fontSize:'clamp(40px,6vw,62px)',lineHeight:1,marginTop:8,overflowWrap:'anywhere'}}>{releaseGate}</div><div style={{marginTop:16}}><strong>Primär orsak:</strong> <code>{releaseGateReason}</code><div style={{marginTop:6}}>{gateReasonLabels[releaseGateReason]}</div></div></section>
    <section aria-label="Remediation" style={{marginTop:18,padding:'20px 22px',border:'3px solid #111',background:'#f7f5f1'}}><div style={{fontSize:13,fontWeight:900,letterSpacing:1.4}}>REKOMMENDERAD ÅTGÄRD</div><div style={{fontFamily:'monospace',fontWeight:800,fontSize:20,marginTop:10,overflowWrap:'anywhere'}}>{remediationCode}</div><div style={{fontFamily:'Georgia,serif',fontSize:23,lineHeight:1.4,marginTop:10}}>{nextAction}</div><div style={{marginTop:12}}><Link href="/api/release-verification" style={{fontWeight:800}}>Verifiera kod och release-gate i API →</Link></div></section>
    <section aria-label="Release-verifiering" style={{marginTop:18,padding:'20px 22px',border:'3px solid #111',background:releaseStatus==='VERIFIED'?'#eef4ec':releaseStatus==='BEVAKA'?'#fff4d8':'#f7e7e7'}}><div style={{fontSize:13,fontWeight:900,letterSpacing:1.4}}>RELEASE-VERIFIERING</div><div style={{fontFamily:'Georgia,serif',fontSize:42,lineHeight:1,marginTop:8}}>{releaseStatus}</div></section>
    <section aria-label="Deployment-identitet" style={{marginTop:24,padding:18,border:'1px solid #111',background:'#f7f5f1'}}><strong>Aktuell deployment</strong><div style={{marginTop:8,fontFamily:'monospace'}}>Commit: {deployment.shortCommitSha??'Okänd'} · Git-ref: {deployment.gitRef??'Okänd'} · Deployment-ID: {deployment.deploymentId??'Okänd'}</div></section>
    <section aria-label="Aktuell driftstatus" style={{marginTop:34,border:'3px solid #111',padding:'28px 26px',background:status==='STABIL'?'#eef4ec':'#f7eee5'}}><div style={{fontSize:13,fontWeight:900,letterSpacing:1.6}}>STATUS</div><div style={{fontFamily:'Georgia,serif',fontSize:54,lineHeight:1,marginTop:8}}>{status}</div>{alerts.length?<ul>{alerts.map(a=><li key={a}>{a}</li>)}</ul>:<p>Inga automatiska driftvarningar just nu.</p>}</section>
    {reasons.length?<section style={{marginTop:24}}><h2>Varför denna status?</h2>{reasons.map(r=><div key={r}><code>{r}</code> · {reasonLabels[r]??r}</div>)}</section>:null}
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:14,marginTop:28}}>{[[radar.items.length,'Aktuella artiklar'],[freshnessLabel,'Nyaste artikelns ålder'],[activeSources.length,'Aktiva källor'],[staleSources.length,'Gamla källor'],[undatedSources.length,'Utan daterad data'],[downSources.length,'Nere']].map(([v,l])=><div key={String(l)} style={{borderTop:'2px solid #111',paddingTop:12}}><strong style={{fontSize:34}}>{v}</strong><div>{l}</div></div>)}</section>
    <section style={{marginTop:24,padding:'16px 18px',background:'#f7f5f1'}}><strong>Färskhetskontroll:</strong> varning aktiveras efter {staleAfterHours} timmar. Källgräns: {sourceStaleAfterHours} timmar.{newestPublishedAt?<div>Nyaste daterade publicering: {new Date(newestPublishedAt).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm'})}.</div>:null}</section>
    <section style={{marginTop:34}}><h2>Status per källa</h2>{sourceFreshness.map(s=><div key={s.name} style={{borderTop:'1px solid #bbb',padding:'10px 0'}}><strong>{s.name}</strong> · {sourceStateLabels[s.state]??s.state} · {s.ageHours===null?'Okänd ålder':`${Math.round(s.ageHours*10)/10} h`}</div>)}</section>
    {unavailable.length?<section style={{marginTop:34}}><h2>Nedkopplade källor</h2><ul>{unavailable.map(f=><li key={f.name}>{f.name}</li>)}</ul></section>:null}
    <p style={{marginTop:28,fontSize:13,color:'#555'}}>Senast hämtad: {new Date(radar.fetchedAt).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm'})}. Data mellanlagras i 15 minuter.</p>
  </main>;
}
