import {dailyDeskUpdates,type DailyDeskKey} from '../content/dailyDeskUpdates';
import {getLiveNews} from '../lib/liveNews';

const deskSections:Partial<Record<DailyDeskKey,string[]>>={
 start:['Världen','Internationella medier','Sverige','Ekonomi','Kultur','Vetenskap','Sport'],senaste:['Världen','Internationella medier','Sverige','Stockholm','Ekonomi','Kultur','Vetenskap','Sport'],varlden:['Världen','Internationella medier'],sverige:['Sverige'],stockholm:['Stockholm'],eu:['EU'],ekonomi:['Ekonomi'],kultur:['Kultur'],vetenskap:['Vetenskap'],ai:['Vetenskap'],sport:['Sport'],analys:['Världen','EU','Sverige','Ekonomi','Vetenskap']
};
function updatedLabel(){return new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Stockholm'}).format(new Date())}
function timeLabel(value:string){return new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Stockholm'}).format(new Date(value))}
function ageLimit(desk:DailyDeskKey){return desk==='start'?24:desk==='sport'?48:72}

export default async function DailyDeskUpdate({desk}:{desk:DailyDeskKey}){
 if(desk==='helg'){const stories=dailyDeskUpdates.helg;return <div className="shell"><section className="section daily-desk-update" aria-labelledby="daily-helg" style={{borderTop:'4px solid #a61919',marginTop:28,paddingTop:22}}><div className="kicker">Aktuellt · Uppdaterad {updatedLabel()}</div><h2 id="daily-helg" style={{fontFamily:'Georgia,serif',fontSize:'clamp(30px,4vw,46px)',margin:'8px 0 22px'}}>Dagens uppdatering</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:24}}>{stories.map(story=><article key={story.title} style={{borderTop:'1px solid #222',paddingTop:16}}><div className="kicker">{story.section}</div><h3 style={{fontFamily:'Georgia,serif',fontSize:26,lineHeight:1.1}}>{story.title}</h3><p><strong>Själva nyheten.</strong> {story.news}</p><p><strong>Analys och konsekvenser.</strong> {story.analysis}</p><p><strong>Längre fördjupning.</strong> {story.depth}</p><div><strong>Källor.</strong>{story.sources.map(source=><div key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.label} ↗</a></div>)}</div></article>)}</div></section></div>}
 const live=await getLiveNews();const allowed=deskSections[desk]??[];const maxAge=ageLimit(desk)*60*60*1000;const now=Date.now();
 const stories=live.items.filter(item=>allowed.includes(item.section)||allowed.includes(item.sourceSection)).filter(item=>{const published=Date.parse(item.published);const age=now-published;return Number.isFinite(published)&&age>=0&&age<=maxAge}).sort((a,b)=>Date.parse(b.published)-Date.parse(a.published));
 const withImages=stories.filter(item=>Boolean(item.image));const selected=[...withImages,...stories.filter(item=>!item.image)].filter((item,index,array)=>array.findIndex(candidate=>candidate.link===item.link)===index).slice(0,3);if(!selected.length)return null;
 return <div className="shell"><section className="section daily-desk-update" aria-labelledby={`daily-${desk}`} style={{borderTop:'4px solid #a61919',marginTop:28,paddingTop:22}}><div className="kicker">Senaste {ageLimit(desk)} timmarna · Uppdaterad {updatedLabel()}</div><h2 id={`daily-${desk}`} style={{fontFamily:'Georgia,serif',fontSize:'clamp(30px,4vw,46px)',margin:'8px 0 22px'}}>Aktuellt just nu</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:24}}>{selected.map(story=><article key={story.link} style={{borderTop:'1px solid #222',paddingTop:16}}>{story.image&&<a href={story.link} target="_blank" rel="noopener noreferrer" style={{display:'block',aspectRatio:'16/9',overflow:'hidden',marginBottom:14}}><img src={story.image} alt="" loading="lazy" style={{width:'100%',height:'100%',objectFit:'cover'}}/></a>}<div className="kicker">{story.source} · {timeLabel(story.published)}</div><h3 style={{fontFamily:'Georgia,serif',fontSize:26,lineHeight:1.1}}><a href={story.link} target="_blank" rel="noopener noreferrer">{story.title}</a></h3>{story.summary&&<p>{story.summary}</p>}<a className="text-link" href={story.link} target="_blank" rel="noopener noreferrer">Läs hos källan →</a></article>)}</div></section></div>
}