import Link from 'next/link';
import { swedenDesk207 } from '../../content/swedenDesk207';
import { swedenElection209 } from '../../content/swedenElection209';
import { swedenEconomyDesk210 } from '../../content/swedenEconomy210';
import { swedenSocietyDesk211 } from '../../content/swedenSociety211';
import { swedenSecurityDesk212 } from '../../content/swedenSecurity212';
import { swedenRegions214 } from '../../content/swedenRegions214';
import { swedenCulture215 } from '../../content/swedenCulture215';
import { swedenSport216 } from '../../content/swedenSport216';
export const metadata={title:'Sverige | NackaSidan 2026',description:'Politik, ekonomi, samhälle, säkerhet, regioner, kultur och sport från hela Sverige.'};
const desks=[{id:'politik',title:swedenElection209.title,items:swedenElection209.topics},{id:'ekonomi',title:swedenEconomyDesk210.title,items:swedenEconomyDesk210.indicators},{id:'samhalle',title:swedenSocietyDesk211.title,items:swedenSocietyDesk211.beats.map(x=>x.title)},{id:'forsvar',title:swedenSecurityDesk212.title,items:swedenSecurityDesk212.areas},{id:'regioner',title:swedenRegions214.title,items:swedenRegions214.regions.map(x=>x.title)},{id:'kultur',title:swedenCulture215.title,items:swedenCulture215.areas},{id:'sport',title:swedenSport216.title,items:swedenSport216.areas}];
export default function SverigePage(){return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><header className="border-b-4 border-neutral-950 pb-7"><p className="text-sm font-bold uppercase tracking-[.2em] text-neutral-500">NackaSidan 2026</p><div className="mt-2 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-6xl font-black tracking-tight">{swedenDesk207.title}</h1><p className="mt-4 max-w-3xl text-xl leading-8 text-neutral-600">{swedenDesk207.promise}</p></div><div className="text-sm text-neutral-500">Hela landet · Källa först · Fakta före tempo</div></div></header><nav className="flex gap-5 overflow-x-auto border-b py-4 text-sm font-bold">{desks.map(s=><a key={s.id} href={`#${s.id}`} className="whitespace-nowrap hover:underline">{s.title}</a>)}</nav><section className="grid gap-8 border-b py-9 lg:grid-cols-[2fr_1fr]"><div><p className="text-sm font-bold uppercase tracking-wider text-neutral-500">Nationellt</p><h2 className="mt-2 text-4xl font-black leading-tight sm:text-5xl">Sveriges viktigaste frågor – samlade på en sida</h2><p className="mt-4 max-w-3xl text-xl leading-8 text-neutral-600">Valet, ekonomin, välfärden, säkerheten och utvecklingen utanför Stockholm får egna redaktionella ytor. Aktuella artiklar visas först efter källkontroll.</p></div><aside className="border-t pt-5 lg:border-l lg:border-t-0 lg:pl-7"><h3 className="text-xl font-black">Valet 2026</h3><p className="mt-3 leading-7 text-neutral-600">Sakfrågor, opinionsmätningar, faktakoll och vallöften får en central plats fram till valdagen.</p><div className="mt-5 text-sm font-bold">Nästa viktiga steg: röstkort och förtidsröstning i augusti.</div></aside></section><section className="grid gap-7 py-9 md:grid-cols-2 lg:grid-cols-3">{desks.map(s=><section id={s.id} key={s.id} className="border-t-4 border-neutral-950 pt-4"><h2 className="text-2xl font-black">{s.title}</h2><p className="mt-3 text-sm leading-6 text-neutral-600">{s.items.join(' · ')}</p><div className="mt-5 rounded-lg bg-neutral-100 p-4 text-sm text-neutral-500">Verifierade nyheter och analyser fylls på här.</div></section>)}</section><footer className="border-t py-6 text-sm text-neutral-500"><Link href="/stockholm" className="font-bold underline">Stockholm</Link> fortsätter som separat lokalredaktion.</footer></main>}
