type Match={title:string;link:string;source:string;published:string;score:number;eventScore:number;verdict:string;signals:string[]};
type Row={item:{title:string;source:string;category?:string;published?:string};query:string;matches:Match[];best:Match|null;confirmed:boolean};
type Data={generatedAt:string;checked:number;confirmed:number;probable:number;results:Row[]};

async function getData():Promise<Data>{
 const empty={generatedAt:'',checked:0,confirmed:0,probable:0,results:[]};
 try{const base=process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:'http://localhost:3000';const r=await fetch(`${base}/api/event-match`,{next:{revalidate:900}});if(!r.ok||!(r.headers.get('content-type')||'').includes('application/json'))return empty;return await r.json();}catch{return empty;}
}

export default async function Page(){const data=await getData();return <main style={{maxWidth:1120,margin:'0 auto',padding:'72px 28px 100px'}}>
<p style={{color:'#a61919',fontWeight:800,letterSpacing:2,fontSize:13}}>MAIN 22 · HÄNDELSEMATCHAREN</p>
<h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(54px,8vw,94px)',lineHeight:.95,margin:'12px 0 22px'}}>Är det verkligen samma händelse?</h1>
<p style={{maxWidth:820,fontFamily:'Georgia,serif',fontSize:20,lineHeight:1.45}}>Händelsematcharen granskar Källjägarens träffar och väger gemensamt händelsespråk, tid och konkreta fakta. En liknande rubrik räcker inte. Målet är att skilja verklig bekräftelse från artiklar som bara handlar om samma ämne.</p>
<section style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',borderTop:'1px solid #bbb',borderBottom:'3px solid #111',marginTop:42}}>{[['GRANSKADE',data.checked],['TROLIGA 68+',data.probable],['SAMMA HÄNDELSE 85+',data.confirmed]].map(([l,v])=><div key={String(l)} style={{padding:'25px 18px',borderRight:'1px solid #ddd'}}><strong style={{fontFamily:'Georgia,serif',fontSize:42}}>{v}</strong><div style={{fontSize:12,fontWeight:800,letterSpacing:1.4}}>{l}</div></div>)}</section>
<div style={{marginTop:18,padding:'14px 18px',background:'#f1eadf',borderLeft:'3px solid #a61919',fontSize:13}}><strong>Trösklar:</strong> 85–100 Samma händelse · 68–84 Trolig match · 45–67 Osäker · 0–44 Annan händelse. Resultatet är beslutsstöd och ersätter inte redaktionell slutkontroll.</div>
<section style={{marginTop:42}}>{data.results.map((row,i)=>{const b=row.best;const good=b&&b.eventScore>=85;return <article key={`${row.item.title}-${i}`} style={{display:'grid',gridTemplateColumns:'60px 1fr 230px',gap:20,padding:'28px 0',borderTop:'1px solid #ccc'}}><div style={{fontFamily:'Georgia,serif',fontSize:24,color:'#a61919'}}>{String(i+1).padStart(2,'0')}</div><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1.2,color:'#777'}}>{row.item.category||'NYHET'} · {row.item.source}</div><h2 style={{fontFamily:'Georgia,serif',fontSize:27,margin:'7px 0 10px'}}>{row.item.title}</h2>{b?<div style={{padding:'14px 16px',background:'#f6f2e9'}}><strong>{b.source}: {b.title}</strong><br/><span>{b.signals.length?b.signals.join(' · '):'svag händelseöverensstämmelse'}</span><br/><a href={b.link} target="_blank" rel="noreferrer" style={{fontWeight:800,color:'#111'}}>ÖPPNA KÄLLA ↗</a></div>:<div style={{fontStyle:'italic',color:'#666'}}>Ingen kandidat att händelsematcha.</div>}</div><div>{b?<><div style={{fontFamily:'Georgia,serif',fontSize:38,fontWeight:700}}>{b.eventScore}/100</div><div style={{display:'inline-block',marginTop:7,padding:'7px 10px',border:`1px solid ${good?'#27834a':b.eventScore>=68?'#a47b24':'#a61919'}`,fontWeight:800,fontSize:12}}>{b.verdict}</div></>:<div>—</div>}</div></article>})}</section>
<footer style={{borderTop:'3px solid #111',paddingTop:18,marginTop:30,fontSize:12}}>SIGNAL → KÄLLJÄGAREN → HÄNDELSEMATCHAREN → OBEROENDE STÖD → SLUTKONTROLL</footer>
</main>}
