import { runVerificationPipeline } from '../../lib/verificationPipeline';

export const revalidate = 900;

export default async function Page(){
  const data=await runVerificationPipeline(8);
  return <main style={{maxWidth:1120,margin:'0 auto',padding:'72px 28px 100px'}}>
<p style={{color:'#a61919',fontWeight:800,letterSpacing:2,fontSize:13}}>MAIN 23 · AUTOMATISKT VERIFIERINGSFLÖDE</p>
<h1 style={{fontFamily:'Georgia,serif',fontSize:'clamp(54px,8vw,94px)',lineHeight:.95,margin:'12px 0 22px'}}>Källjägaren matar Händelsematcharen automatiskt</h1>
<p style={{maxWidth:820,fontFamily:'Georgia,serif',fontSize:20,lineHeight:1.45}}>Main 23 kopplar ihop hela kedjan server-side. Nyhetsradarn väljer olösta konkreta signaler, Källjägaren söker andra källfamiljer och Händelsematcharen bedömer om träffen verkligen gäller samma händelse. Sidan behöver inte längre anropa sitt eget API under byggsteget.</p>
<section style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',borderTop:'1px solid #bbb',borderBottom:'3px solid #111',marginTop:42}}>{[['GRANSKADE',data.checked],['TROLIGA 68+',data.probable],['SAMMA HÄNDELSE 85+',data.confirmed]].map(([l,v])=><div key={String(l)} style={{padding:'25px 18px',borderRight:'1px solid #ddd'}}><strong style={{fontFamily:'Georgia,serif',fontSize:42}}>{v}</strong><div style={{fontSize:12,fontWeight:800,letterSpacing:1.4}}>{l}</div></div>)}</section>
<div style={{marginTop:18,padding:'14px 18px',background:'#f1eadf',borderLeft:'3px solid #a61919',fontSize:13}}><strong>Flöde:</strong> Signal → Källjägaren → Händelsematcharen → oberoende stöd → slutkontroll. 85–100 Samma händelse · 68–84 Trolig match · 45–67 Osäker · 0–44 Annan händelse. Ingen automatisk publicering.</div>
<section style={{marginTop:42}}>{data.results.map((row,i)=>{const b=row.best;const good=b&&b.eventScore>=85;return <article key={`${row.item.title}-${i}`} style={{display:'grid',gridTemplateColumns:'60px 1fr 230px',gap:20,padding:'28px 0',borderTop:'1px solid #ccc'}}><div style={{fontFamily:'Georgia,serif',fontSize:24,color:'#a61919'}}>{String(i+1).padStart(2,'0')}</div><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1.2,color:'#777'}}>{row.item.section||row.item.category||'NYHET'} · {row.item.source}</div><h2 style={{fontFamily:'Georgia,serif',fontSize:27,margin:'7px 0 10px'}}>{row.item.title}</h2><div style={{fontSize:12,color:'#666',marginBottom:10}}>Källjägarens sökning: {row.query||'—'}</div>{b?<div style={{padding:'14px 16px',background:'#f6f2e9'}}><strong>{b.source}: {b.title}</strong><br/><span>{b.signals.length?b.signals.join(' · '):'svag händelseöverensstämmelse'}</span><br/><a href={b.link} target="_blank" rel="noreferrer" style={{fontWeight:800,color:'#111'}}>ÖPPNA KÄLLA ↗</a></div>:<div style={{fontStyle:'italic',color:'#666'}}>Källjägaren hittade ingen tillräckligt lik oberoende publicering.</div>}</div><div>{b?<><div style={{fontFamily:'Georgia,serif',fontSize:38,fontWeight:700}}>{b.eventScore}/100</div><div style={{display:'inline-block',marginTop:7,padding:'7px 10px',border:`1px solid ${good?'#27834a':b.eventScore>=68?'#a47b24':'#a61919'}`,fontWeight:800,fontSize:12}}>{b.verdict}</div><div style={{fontSize:12,marginTop:8,color:'#666'}}>Rubrikmatchning: {b.score}%</div></>:<div style={{fontFamily:'Georgia,serif',fontSize:34}}>—</div>}</div></article>})}</section>
<footer style={{borderTop:'3px solid #111',paddingTop:18,marginTop:30,fontSize:12}}>MAIN 23 · AUTOMATISK KEDJA UTAN SELF-FETCH · REDAKTIONELL SLUTKONTROLL KRÄVS</footer>
</main>;
}
