import Link from 'next/link';

const stories=[
 {area:'AI & reglering',date:'28 augusti 2026',title:'EU kräver märkning av AI-innehåll och tydligare besked till användare',news:'Sedan den 2 augusti gäller AI-förordningens transparensregler. Användare ska informeras när de möter vissa AI-system, och genererat eller manipulerat innehåll ska i relevanta fall kunna identifieras och märkas.',analysis:'Reglerna flyttar ansvaret från den enskilda användarens källkritik till hela kedjan av modellföretag, plattformar och publicister. Den avgörande frågan blir om märkningen fungerar tekniskt även när innehåll kopieras, redigeras och sprids mellan tjänster.',source:'EU-kommissionen',url:'https://digital-strategy.ec.europa.eu/en/policies/guidelines-ai-transparency-obligations'},
 {area:'Medicin & AI',date:'Augusti 2026',title:'AI användes i realtid under synräddande hjärnkirurgi',news:'Ett system utvecklat vid University College London analyserade operationsvideo och hjälpte kirurger att identifiera känsliga anatomiska strukturer under ett ingrepp.',analysis:'Den kliniska nyttan ligger inte i att ersätta kirurgen utan i att ge ett extra beslutsstöd när marginalerna är små. Innan bred användning krävs oberoende validering, tydligt ansvar och studier av hur systemet fungerar på andra sjukhus och patientgrupper.',source:'University College London',url:'https://www.ucl.ac.uk/news/2026/aug/first-patient-live-ai-assisted-sight-saving-brain-surgery'},
 {area:'Klinisk forskning',date:'Augusti 2026',title:'NIH:s AI matchar patienter med relevanta kliniska studier',news:'NIH-forskare har utvecklat TrialGPT, ett system som kan identifiera kliniska studier där en person kan vara behörig och sammanfatta hur kriterierna stämmer med patientens uppgifter.',analysis:'Bättre matchning kan förkorta rekryteringstiden och göra fler studier möjliga. Samtidigt får ett urvalssystem inte dölja osäkerhet eller reproducera snedheter i vilka patienter som redan finns representerade i data och forskning.',source:'National Library of Medicine, NIH',url:'https://www.nlm.nih.gov/'},
 {area:'Bioteknik',date:'Augusti 2026',title:'AI hjälper forskare att konstruera genetiska kretsar',news:'Forskare vid Rice University beskriver en metod som producerar stora DNA-bibliotek och använder resultaten som träningsdata för modeller som föreslår nya genetiska kretsar.',analysis:'Metoden kan göra syntetisk biologi snabbare och mer systematisk, men en modellgenererad konstruktion är fortfarande en hypotes. Biologisk funktion, säkerhet och reproducerbarhet måste prövas experimentellt innan resultaten kan användas utanför laboratoriet.',source:'Rice University',url:'https://news.rice.edu/news/2026/scientists-demonstrate-first-time-use-ai-genetic-circuit-design'},
 {area:'Neuroteknik',date:'Augusti 2026',title:'Djupinlärning förbättrar kommunikationen med bioniska ögon',news:'Forskare vid UC Santa Barbara använder djupinlärning för att styra elektrisk stimulering i synbarken mer precist och därmed förbättra den information som ett bioniskt synsystem kan förmedla.',analysis:'Framsteget handlar ännu inte om normal syn, utan om tydligare och mer användbara synintryck. Vägen till vård kräver stabil hårdvara, långvarig säkerhet och tester som mäter faktisk vardagsnytta för användaren.',source:'UC Santa Barbara',url:'https://news.ucsb.edu/2026/022739/deep-learning-refines-how-bionic-eyes-communicate-brain'},
 {area:'Klimat & AI',date:'2026',title:'AI börjar förena väderprognoser och långsiktiga klimatmodeller',news:'En översikt i Nature Communications beskriver hur modeller tränade på stora mängder jordobservationer kan bidra både till kortsiktiga väderprognoser och långsiktig klimatanalys.',analysis:'En gemensam modellvärld kan ge snabbare beräkningar och bättre regional information. Men transparens, energianvändning och ojämn tillgång till beräkningskraft riskerar att skapa nya vetenskapliga och globala klyftor.',source:'Nature Communications',url:'https://www.nature.com/articles/s41467-026-75787-y'},
];
const watch=[
 ['Validering','Fungerar resultatet utanför forskarnas eget testmaterial?'],
 ['Reproducerbarhet','Kan en oberoende grupp upprepa resultatet?'],
 ['Säkerhet','Vad händer när modellen har fel eller möter en ny situation?'],
 ['Ansvar','Vem fattar beslutet och vem ansvarar för konsekvensen?'],
];

export const metadata={title:'Vetenskap & AI | NackaSidan 2026',description:'Dagens AI-, medicin-, klimat- och forskningsnyheter med analys och spårbara källor.'};

export default function Page(){return <main><div className="shell science-desk">
 <header className="science-head"><div className="kicker">Vetenskap & AI · Uppdaterad 28 augusti 2026</div><h1>Genombrotten, bevisen och konsekvenserna</h1><p className="lead">Vi följer AI, medicin, bioteknik, klimat och rymd – och skiljer ett lovande experiment från en metod som faktiskt är redo för samhället.</p><nav aria-label="Vetenskapsområden"><a href="#senaste">Senaste</a><a href="#analys">Analys</a><a href="#metod">Så granskar vi</a><Link href="/tema/ai">AI-temat</Link></nav></header>

 <section className="science-lead" id="senaste"><article><div className="kicker">Huvudnyhet · {stories[0].area}</div><h2>{stories[0].title}</h2><div className="science-part"><strong>Nyheten</strong><p>{stories[0].news}</p></div><div className="science-part science-part-analysis"><strong>Analys</strong><p>{stories[0].analysis}</p></div><a className="button" href={stories[0].url} target="_blank" rel="noopener noreferrer">Källa: {stories[0].source} ↗</a></article><aside><div className="kicker">Dagens bevakning</div><strong>6</strong><span>verifierade forskningsspår</span><hr/><p>Reglering, klinisk AI, bioteknik, neuroteknik och klimatmodeller.</p></aside></section>

 <section className="science-grid-section"><div className="science-title"><div><div className="kicker">Senaste nytt</div><h2>Forskningen vi följer</h2></div><span className="meta">Nyhet · Analys · Källa</span></div><div className="science-grid">{stories.slice(1).map((story,index)=><article key={story.title} className={index===0?'science-card science-card-wide':'science-card'}><div className="kicker">{story.area} · {story.date}</div><h3>{story.title}</h3><div className="science-part"><strong>Nyheten</strong><p>{story.news}</p></div><div className="science-part science-part-analysis"><strong>Analys</strong><p>{story.analysis}</p></div><a className="text-link" href={story.url} target="_blank" rel="noopener noreferrer">Källa: {story.source} ↗</a></article>)}</div></section>

 <section className="science-big-analysis" id="analys"><div><div className="kicker">Veckans stora analys</div><h2>AI flyttar från skärm till fysisk och medicinsk infrastruktur</h2><p>Laboratorieutrustning, kirurgi, kliniska studier och neuroproteser visar samma rörelse: modellerna lämnar chattfönstret och börjar påverka handlingar i den fysiska världen.</p></div><div><h3>Vad förändras?</h3><p>När ett AI-system bara föreslår text är ett fel ofta möjligt att rätta. När systemet påverkar en operation, ett experiment eller en patientmatchning kan felet få omedelbara följder. Kraven på validering, loggning, mänsklig kontroll och ansvar måste därför bli betydligt högre.</p><h3>Konsekvens för Sverige</h3><p>Svensk vård, forskning och industri kan vinna produktivitet, men införandet får inte gå snabbare än förmågan att granska systemen. Upphandling och tillsyn blir lika viktiga som själva modellen.</p></div></section>

 <section className="science-method" id="metod"><div className="science-title"><div><div className="kicker">Evidens före hype</div><h2>Fyra frågor före ordet genombrott</h2></div></div><div>{watch.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

 <section className="science-sources"><div className="kicker">Källor</div><h2>Primärkällor och forskningspubliceringar</h2><p>Varje nyhet ovan länkar direkt till universitetet, myndigheten eller tidskriften bakom uppgiften. Analysen är NackaSidans redaktionella bedömning.</p><div><a href="https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai" target="_blank" rel="noopener noreferrer">EU-kommissionen: AI-förordningen ↗</a><a href="https://www.nih.gov/" target="_blank" rel="noopener noreferrer">NIH: medicinsk forskning ↗</a><a href="https://science.nasa.gov/" target="_blank" rel="noopener noreferrer">NASA Science ↗</a><a href="https://www.nature.com/natmachintell/" target="_blank" rel="noopener noreferrer">Nature Machine Intelligence ↗</a></div></section>
 <section className="science-next"><Link className="button" href="/tema/ai">Fördjupa dig i AI-temat</Link><Link className="text-link" href="/senaste">Se dagens uppdateringar →</Link></section>
 </div></main>}
