import Link from 'next/link';
import DailyDeskUpdate from '../../components/DailyDeskUpdate';
import {election2026} from '../../content/election2026';

export const metadata={title:'Valet i Nacka 2026 | NackaSidan',description:'Valdagen, rösträkningen och de viktigaste sakfrågorna i Nacka och Sverige.'};
const nackaUrl='https://www.nacka.se/kommun--politik/delta-och-paverka/val-2026/';
const resultUrl='https://resultat.val.se/val2026';
const todayLabel=()=>new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Stockholm'}).format(new Date());

export default function ElectionPage(){return <main><div className="shell standard-section-page">
 <header className="border-b-4 border-neutral-950 pb-7"><p className="text-sm font-bold uppercase tracking-[.18em] text-red-800">Uppdaterad {todayLabel()}</p><h1 className="mt-2 text-5xl font-black tracking-tight sm:text-7xl">Valet 2026</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-neutral-600">Sverige röstar i dag. Vallokalerna är öppna klockan 8–20 och den preliminära rösträkningen börjar efter stängning.</p></header>
 <section className="border-b border-neutral-300 py-10"><p className="text-xs font-bold uppercase tracking-widest text-red-800">Direkt · Valdagen 13 september</p><h2 className="mt-1 text-3xl font-black sm:text-4xl">Följ rösträkningen</h2><div className="mt-6 grid gap-5 md:grid-cols-3"><a href={resultUrl} target="_blank" rel="noreferrer" className="border-t-4 border-neutral-950 pt-4"><h3 className="text-2xl font-black">Officiellt valresultat</h3><p className="mt-3 leading-7 text-neutral-600">Valmyndighetens preliminära resultat uppdateras när valdistrikten rapporterar.</p><span className="mt-4 inline-block font-bold underline">Öppna resultatet ↗</span></a><a href="https://www.svt.se/nyheter/inrikes/senaste-nytt-om-val-2026" target="_blank" rel="noreferrer" className="border-t-4 border-neutral-950 pt-4"><h3 className="text-2xl font-black">SVT:s valbevakning</h3><p className="mt-3 leading-7 text-neutral-600">Direktrapportering, analyser och valvaka under hela dagen och kvällen.</p><span className="mt-4 inline-block font-bold underline">Följ live ↗</span></a><a href={nackaUrl} target="_blank" rel="noreferrer" className="border-t-4 border-neutral-950 pt-4"><h3 className="text-2xl font-black">Valet i Nacka</h3><p className="mt-3 leading-7 text-neutral-600">Lokaler, praktisk information och kommunens officiella valuppgifter.</p><span className="mt-4 inline-block font-bold underline">Nacka kommun ↗</span></a></div></section>
 <section className="border-b border-neutral-300 py-10"><h2 className="text-3xl font-black sm:text-4xl">Sju frågor som avgör Nacka</h2><div className="mt-6 grid gap-5 md:grid-cols-2">{election2026.focus.map((focus,index)=><article key={focus} className="border-t-2 border-neutral-950 pt-4"><p className="text-xs font-bold uppercase tracking-wide text-red-800">Fråga {index+1}</p><h3 className="mt-2 text-2xl font-black">{focus}</h3></article>)}</div></section>
 <section className="py-8"><Link className="font-bold underline" href="/sverige">Sverige →</Link></section>
 </div><DailyDeskUpdate desk="sverige"/></main>}