import DailyDeskUpdate from '../../components/DailyDeskUpdate';
import Link from 'next/link';

const markets=[
 {name:'Stockholmsbörsen',ticker:'OMXS30',text:'Storbolagsindexet påverkas starkt av verkstad, banker, kronan och världshandeln.',url:'https://www.nasdaqomxnordic.com/index/index_info?Instrument=SE0000337842'},
 {name:'USA',ticker:'S&P 500',text:'USA-börsen styr den globala riskviljan. Räntor, teknikvinster och konjunkturdata är centrala.',url:'https://www.spglobal.com/spdji/en/indices/equity/sp-500/'},
 {name:'Europa',ticker:'STOXX 600',text:'Det breda Europaindexet speglar banker, industri, läkemedel och konsumentbolag.',url:'https://www.stoxx.com/index-details?symbol=SXXP'},
];
const currencies=[
 {pair:'EUR/SEK',value:'11,0835',note:'1 euro i kronor'},
 {pair:'USD/SEK',value:'cirka 9,52',note:'Beräknad korskurssats'},
 {pair:'GBP/SEK',value:'cirka 12,93',note:'Beräknad korskurssats'},
 {pair:'EUR/USD',value:'1,1643',note:'Dollar per euro'},
];
const forecasts=[
 {label:'BNP 2026',value:'2,5 %',trend:'Upp från 2,3 %',text:'Regeringens prognos pekar mot starkare tillväxt, men utfallet beror på konsumtion, export och jobb.'},
 {label:'Styrränta',value:'1,75 %',trend:'Oförändrad',text:'Riksbanken lämnade räntan oförändrad i augusti men ser viss sannolikhet för en senare höjning.'},
 {label:'KPIF juli',value:'0,7 %',trend:'Mål: 2 %',text:'Inflationen ligger under målet. Den låga nivån vägs mot riskerna för högre pristryck framöver.'},
 {label:'Nästa besked',value:'24 sep',trend:'Ny räntebana',text:'Septemberrapporten blir central för synen på bolån, krona och konjunktur.'},
];
const news=[
 {section:'Sverige · I dag',title:'BNP ökade under andra kvartalet 2026',text:'SCB:s nya nationalräkenskaper visar ökad aktivitet. Nästa fråga är om uppgången också syns i konsumtion, investeringar och arbetade timmar.',url:'https://www.scb.se/'},
 {section:'Sverige · I dag',title:'Detaljhandelns volym var i stort sett oförändrad i juli',text:'Den försiktiga handeln visar varför ett förbättrat makroläge inte automatiskt betyder att hushållen konsumerar mer.',url:'https://www.scb.se/'},
 {section:'Arbetsmarknad · I dag',title:'Efterfrågan på arbetskraft är på uppgång',text:'Det är en positiv tidig signal, men den behöver bekräftas av sysselsättning, arbetade timmar och lägre långtidsarbetslöshet.',url:'https://www.scb.se/'},
 {section:'Penningpolitik · 25 augusti',title:'Riksbanken höll styrräntan oförändrad',text:'Protokollet visar hur direktionen balanserar låg inflation mot risken för stigande pristryck och internationell osäkerhet.',url:'https://www.riksbank.se/sv/press-och-publicerat/notiser-och-pressmeddelanden/pressmeddelanden/2026/protokoll-fran-det-penningpolitiska-motet-den-19-augusti-2026/'},
];
export const metadata={title:'Ekonomi | NackaSidan 2026',description:'Börs, ekonominyheter, valutakurser, räntor och prognoser – med analys.'};

export default function Page(){return <main><div className="shell economy-desk">
 <header className="economy-head"><div><div className="kicker">Ekonomi · Uppdaterad 4 september 2026</div><p className="lead">Börs, nyheter, valutakurser och prognoser – med analys av vad siffrorna betyder för hushåll, företag och Sverige.</p></div><nav aria-label="Ekonomisidans avdelningar"><a href="#bors">Börs</a><a href="#nyheter">Nyheter</a><a href="#valutor">Valutor</a><a href="#prognoser">Prognoser</a></nav></header>
 <section className="economy-snapshot" aria-label="Dagens ekonomiska läge"><article><span>Styrränta</span><strong>1,75 %</strong><small>Från 26 augusti</small></article><article><span>KPIF</span><strong>0,7 %</strong><small>Juli · mål 2 %</small></article><article><span>EUR/SEK</span><strong>11,0835</strong><small>ECB · 27 augusti</small></article><article><span>BNP-prognos</span><strong>2,5 %</strong><small>Helåret 2026</small></article></section>

 <section className="economy-section" aria-labelledby="makro-rubrik"><div className="economy-title"><div><div className="kicker">Ny makroanalys · 3 september</div><h2 id="makro-rubrik">Världsekonomin i fem perspektiv</h2></div><span className="meta">Sverige · USA · EU · Japan · Kina</span></div><div className="economy-news-grid"><article className="economy-news-lead"><div className="kicker">Fördjupning</div><h3><Link href="/ekonomi/makrolaget">Makroläget i Sverige, USA, EU, Japan och Kina</Link></h3><p>En samlad genomgång av tillväxt, inflation, räntor, arbetsmarknad och de största riskerna – med en jämförande analys av vad utvecklingen betyder för svenska hushåll och företag.</p><Link className="text-link" href="/ekonomi/makrolaget">Läs hela makroanalysen →</Link></article></div></section>

 <section className="economy-section" id="bors"><div className="economy-title"><div><div className="kicker">Börs</div><h2>Marknadsläget</h2></div><p>Indexlänkar går till officiella indexleverantörer. Kurser kan vara fördröjda.</p></div><div className="economy-market-grid">{markets.map((m,i)=><article key={m.ticker} className={i===0?'economy-market-lead':''}><div className="market-label"><span>{m.name}</span><strong>{m.ticker}</strong></div><h3>Följ dagens handel</h3><p>{m.text}</p><a className="text-link" href={m.url} target="_blank" rel="noopener noreferrer">Öppna kursdata ↗</a></article>)}</div><div className="economy-analysis"><div className="kicker">Marknadsanalys</div><h3>Tre krafter styr börsen just nu</h3><div><p><strong>Räntan:</strong> En låg ränta stödjer värderingar och minskar finansieringskostnader, men osäkerheten om nästa steg kan skapa rörelser.</p><p><strong>Kronan:</strong> En svag krona kan gynna exportbolag men gör import, insatsvaror och resor dyrare.</p><p><strong>Konjunkturen:</strong> Starkare BNP är positivt, men börsen behöver också bättre orderingång, konsumtion och vinstprognoser.</p></div></div></section>

 <section className="economy-section" id="nyheter"><div className="economy-title"><div><div className="kicker">Ekonominyheter</div><h2>Dagens viktigaste</h2></div><span className="meta">Nyast först · källkontrollerat</span></div><div className="economy-news-grid">{news.map((n,i)=><article key={n.title} className={i===0?'economy-news-lead':''}><div className="kicker">{n.section}</div><h3><a href={n.url} target="_blank" rel="noopener noreferrer">{n.title}</a></h3><p>{n.text}</p><a className="text-link" href={n.url} target="_blank" rel="noopener noreferrer">Läs hos källan ↗</a></article>)}</div></section>

 <section className="economy-section" id="valutor"><div className="economy-title"><div><div className="kicker">Valutakurser</div><h2>Kronan mot omvärlden</h2></div><p>ECB:s referenskurser 27 augusti. Korskurser är avrundade beräkningar, inte köp- eller säljkurser.</p></div><div className="currency-grid">{currencies.map(c=><article key={c.pair}><span>{c.pair}</span><strong>{c.value}</strong><small>{c.note}</small></article>)}</div><div className="currency-explainer"><h3>Så påverkar valutan dig</h3><p><strong>Starkare krona:</strong> Import, bränsle och resor kan bli billigare, medan exportbolagens intäkter omräknade till kronor minskar.</p><p><strong>Svagare krona:</strong> Exporten kan få stöd, men hushåll och importberoende företag möter högre kostnader.</p><a className="text-link" href="https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html" target="_blank" rel="noopener noreferrer">ECB:s kurser ↗</a></div></section>

 <section className="economy-section" id="prognoser"><div className="economy-title"><div><div className="kicker">Prognoser</div><h2>Det ekonomerna följer framåt</h2></div><p>Prognoser är bedömningar, inte löften. Osäkerheten ökar längre fram.</p></div><div className="forecast-grid">{forecasts.map(f=><article key={f.label}><span>{f.label}</span><strong>{f.value}</strong><em>{f.trend}</em><p>{f.text}</p></article>)}</div><div className="economy-analysis economy-analysis-light"><div className="kicker">NackaSidans slutsats</div><h3>Återhämtningen ser bättre ut – men är ännu inte bred</h3><p>BNP och efterfrågan på arbetskraft ger försiktigt positiva signaler. Samtidigt är detaljhandeln svag. En hållbar vändning kräver att produktion, sysselsättning, reallöner och investeringar förbättras samtidigt.</p></div></section>

 <section className="economy-sources"><div className="kicker">Källor och transparens</div><h2>Primärkällorna bakom sidan</h2><div><a href="https://www.scb.se/" target="_blank" rel="noopener noreferrer">SCB: dagens statistik ↗</a><a href="https://www.riksbank.se/sv/penningpolitik/" target="_blank" rel="noopener noreferrer">Riksbanken: ränta och inflation ↗</a><a href="https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html" target="_blank" rel="noopener noreferrer">ECB: valutakurser ↗</a><a href="https://www.nasdaqomxnordic.com/" target="_blank" rel="noopener noreferrer">Nasdaq Nordic: börsdata ↗</a></div><p>Valuta- och marknadsdata kan ändras under dagen. Varje datapunkt är märkt med referensdag.</p></section>
 <section className="economy-next"><Link className="button" href="/sverige/artikel/sverige-ekonomi-laget-2026">Läs den stora ekonomiguiden</Link><Link className="text-link" href="/senaste">Se dagens uppdateringar →</Link></section>
 </div><DailyDeskUpdate desk="ekonomi"/></main>}
